# Experiment Eurythmy Letter

In [1]:
import sys
sys.path.append("../src")

In [2]:
from features.features_dataset import FeaturesDataset
from models.experiment import Experiment

In [3]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

## Import Dataset

In [4]:
norm_letters_signal_dataset_path= r"..\data\processed\feat_norm_letters_1_1_dataset_mean.pkl"
feat_dataset = FeaturesDataset.load(file_path= norm_letters_signal_dataset_path)
feat_dataset.features.shape

(8390, 187)

## Prepare Data

In [5]:
feat_dataset.prepare_dataset(drop_constant= False, drop_flatness_columns= True, drop_nan_columns= True)

Removing columns with NaN values: ['kurtosis', 'skewness']


In [6]:
feat_dataset.features.head()

id_measurement  id_performance    datetime  plant  generation  \
0               1               1  2023-04-29  salad           1   
1               1               1  2023-04-29  salad           1   
2               1               1  2023-04-29  salad           1   
3               1               1  2023-04-29  salad           1   
4               1               1  2023-04-29  salad           1   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             1              A1      -85.835655       90.291260   
1             1              G1      -96.628212       83.604851   
2             1              D1     -109.998672       89.973495   
3             1              A2      -83.306580       89.631935   
4             1              G2      -65.591743       89.487083   

   lib_mfcc_3_avg  lib_mfcc_4_avg  lib_mfcc_5_avg  lib_mfcc_6_avg  \
0       27.150677       24.450397       17.381523       14.476572   
1       26.647131       23.880787       17.142712       14.166664   
2       27.083378       24.341211       17.288652       14.374680   
3       26.564987       23.834097       16.861643       14.067777   
4       26.376032       23.637720       16.882397       13.740993   

   lib_mfcc_7_avg  lib_mfcc_8_avg  lib_mfcc_9_avg  lib_mfcc_10_avg  \
0       11.628652       10.253779        9.009523         8.263220   
1       11.311499        9.815317        8.509996         7.710995   
2       11.574939       10.197500        8.994436         8.182779   
3       11.136328        9.779285        8.568973         7.687598   
4       10.826669        9.959647        8.586371         7.815620   

   lib_mfcc_11_avg  lib_mfcc_12_avg  lib_mfcc_13_avg  lib_mfcc_1_std  \
0         7.481691         6.924080         6.325689       87.071404   
1         6.942698         6.384663         5.894090      107.289284   
2         7.339973         6.694422         6.222746       45.244011   
3         6.993852         6.350812         5.871837       39.551929   
4         6.835242         6.490175         5.785554       57.464516   

   lib_mfcc_2_std  lib_mfcc_3_std  lib_mfcc_4_std  lib_mfcc_5_std  \
0        0.980359        0.953386        0.947235        0.955398   
1       17.435492        0.894234        0.777028        1.745475   
2        0.859658        0.939066        0.948810        0.866550   
3        0.491159        0.504996        0.560510        0.462185   
4        0.788460        1.222857        1.200740        0.515309   

   lib_mfcc_6_std  lib_mfcc_7_std  lib_mfcc_8_std  lib_mfcc_9_std  \
0        0.965027        0.979433        0.972912        0.969672   
1        1.486925        1.322912        0.952002        0.781681   
2        0.917197        0.897436        0.912217        0.878173   
3        0.536993        0.503689        0.455105        0.462463   
4        0.505040        0.743336        0.627253        1.033373   

   lib_mfcc_10_std  lib_mfcc_11_std  lib_mfcc_12_std  lib_mfcc_13_std  \
0         0.946374         0.945209         0.952646         0.956299   
1         0.693320         0.757019         0.842326         0.944447   
2         0.894446         0.902890         0.967887         0.915868   
3         0.449083         0.490654         0.456090         0.447698   
4         0.488459         0.632174         0.794163         0.601958   

   zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0  0.000111     0.175157             3.270264                0.034481   
1  0.000078     0.127419             3.240312                0.040663   
2  0.000045     0.477437             3.255116                0.031493   
3  0.000178     0.162887             3.140661                0.056633   
4  0.000089     0.216644             3.242801                0.035025   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.083165               0.013287            0.040835   
1              0.091113               0.011048            0.080317   
2   

## RQ1

Is there any difference in the signals when someone is performing eurythmy?

In [7]:
rq1= feat_dataset.return_subset_given_research_question(1)

In [8]:
train_feat_dataset, _, test_feat_dataset= rq1.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= True)

### Data preparation

In [9]:
# Reduce the features that are correlated in the training data
train_cols, feat_stats= train_feat_dataset.reduce_features_based_on_target(corr_threshold=0.8)
test_feat_dataset.keep_only_specified_variable_columns(train_cols)

# Normalize features ?????
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)

Reduced variable features from initial count to 44.
Variable features were properly normalized using 'zscore' method.
Applied z-score normalization.


In [10]:
feat_stats.head(150)

0             1        p_value
mfcc_1_std                    1.551217e+01  2.218734e+01  9.097036e-199
mfcc_2_std                    5.282189e-01  7.459193e-01  4.377022e-197
mfcc_2_mean                   1.882892e+00  1.504516e+00  1.081632e-191
mfcc_4_mean                   3.336366e-01  2.682437e-01  5.327473e-185
mfcc_3_mean                   2.351813e-01  1.890637e-01  2.657564e-182
delta mfcc_1_std              2.090592e+01  2.969717e+01  3.554130e-182
mfcc_6_mean                   1.595409e-01  1.282071e-01  4.566490e-181
delta mfcc_2_std              7.208858e-01  1.003535e+00  1.690819e-179
mfcc_1_mean                  -4.309836e+01 -5.379855e+01  1.412527e-178
mfcc_8_mean                   8.711018e-02  7.006304e-02  1.379097e-169
mfcc_5_mean                   1.503639e-01  1.221089e-01  1.742345e-163
mfcc_7_mean                   8.501828e-02  6.876237e-02  6.148371e-158
mfcc_10_mean                  5.758656e-02  4.625490e-02  1.359175e-156
lib_mfcc_7_avg                1.027246e+01  1.109039e+01  4.913538e-151
mfcc_4_std                    1.327312e-01  1.606962e-01  4.338540e-147
lib_mfcc_8_avg                9.124544e+00  9.831847e+00  2.897438e-146
lib_mfcc_6_avg                1.269977e+01  1.367099e+01  3.049335e-143
mfcc_9_mean                   5.196816e-02  4.225819e-02  2.981857e-134
mfcc_12_mean                  4.160504e-02  3.378844e-02  1.235703e-129
lib_mfcc_9_avg                8.132185e+00  8.704272e+00  4.371107e-123
delta mfcc_4_std              1.850133e-01  2.201220e-01  4.382393e-121
spectral_spread_mean          1.211951e-01  9.958691e-02  9.798218e-119
mfcc_11_mean                  3.882023e-02  3.172973e-02  2.049993e-111
lib_mfcc_5_avg                1.534379e+01  1.640946e+01  2.092591e-108
mfcc_3_std                    1.143546e-01  1.316655e-01   1.919243e-99
lib_mfcc_10_avg               7.513696e+00  8.028686e+00   9.381099e-98
lib_mfcc_9_std                1.424961e+00  1.036183e+00   5.174330e-85
lib_mfcc_10_std               1.392885e+00  1.033815e+00   2.081444e-79
delta mfcc_3_std              1.609678e-01  1.823159e-01   2.480975e-76
lib_mfcc_8_std                1.439403e+00  1.065843e+00   1.292922e-73
lib_mfcc_11_avg               6.876606e+00  7.270745e+00   7.088467e-72
lib_mfcc_11_std               1.344417e+00  1.041993e+00   1.580803e-68
lib_mfcc_7_std                1.519038e+00  1.159747e+00   1.567404e-62
spectral_centroid_mean        4.979820e-02  4.196809e-02   6.132198e-61
delta spectral_spread_std     6.435433e-02  7.486984e-02   9.499383e-61
lib_mfcc_4_avg                2.165151e+01  2.278531e+01   4.183528e-58
spectral_spread_std           5.369478e-02  6.012850e-02   7.459542e-58
lib_mfcc_12_std               1.288270e+00  1.035926e+00   5.589423e-57
mfcc_6_std                    9.637278e-02  1.047259e-01   1.605841e-49
chroma_7_std                  3.784771e-02  3.056871e-02   1.005835e-48
delta chroma_7_std            5.148770e-02  4.148658e-02   1.863224e-46
lib_mfcc_13_std               1.257799e+00  1.042105e+00   8.840446e-46
lib_mfcc_3_avg                2.471061e+01  2.590116e+01   9.756704e-45
lib_mfcc_12_avg               6.436603e+00  6.756175e+00   9.856452e-45
lib_mfcc_6_std                1.666904e+00  1.334311e+00   2.070753e-40
chroma_5_std                  2.112111e-02  1.762913e-02   1.002161e-38
mfcc_5_std                    9.357972e-02  1.005386e-01   1.224508e-38
delta chroma_5_std            2.868842e-02  2.380683e-02   1.595934e-38
delta mfcc_6_std              1.364309e-01  1.463331e-01   6.696228e-34
chroma_std_std                3.832380e-03  3.160459e-03   1.602407e-30
delta chroma_std_std          5.407242e-03  4.462078e-03   2.478173e-28
chroma_7_mean                 1.931325e-02  1.510312e-02   2.910402e-28
lib_mfcc_13_avg               6.029712e+00  6.257576e+00   3.603288e-24
delta mfcc_5_std              1.327336e-01  1.405581e-01   6.469881e-24
energy_entropy_std            1.708034e-01  1.498092e-01   1.183149e-21
lib_mfcc_

In [11]:
train_feat_dataset.features.head()

id_measurement  id_performance    datetime   plant  generation  \
0             341              59  2023-07-27   basil           1   
1             370              64  2023-07-31  tomato           2   
2             458              79  2023-08-07   basil           2   
3             281              49  2023-07-17   basil           1   
4             595             102  2023-09-19   salad           4   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             0              G2        1.377359        0.061525   
1             0              O2        1.753532        0.065833   
2             3              L1        0.257775        0.496157   
3             3              D2       -1.079190       -0.119156   
4             0              G4        0.885542        0.119408   

   lib_mfcc_3_avg  lib_mfcc_13_avg  lib_mfcc_1_std  lib_mfcc_3_std  \
0       -1.029548        -0.233882        0.421467        0.145063   
1       -0.944990        -0.094143       -1.386619       -0.122261   
2        0.330683         0.199462       -0.202979       -0.072261   
3        0.495905         1.020374        1.602477        1.271753   
4       -0.895518        -1.633319       -1.519433       -0.137335   

   lib_mfcc_13_std  energy_mean  energy_entropy_mean  mfcc_9_mean  \
0         3.124360    -0.733673            -0.268481     0.652231   
1         1.773266    -1.243132            -0.902340     0.819088   
2        -0.142530    -0.986109            -0.280397     0.891003   
3         0.381257    -0.774608             0.034866    -2.641702   
4        -0.463067    -0.131292            -0.492647     0.440384   

   mfcc_11_mean  mfcc_13_mean  delta zcr_mean  delta energy_mean  \
0      1.203061      0.745552        0.004585          -0.466351   
1      0.683036      0.567494        0.748844          -0.003141   
2      0.695340     -0.148989        0.004585          -0.899053   
3     -1.095509     -1.811671        0.004585           0.058783   
4      0.216143      0.742770       -0.807333           0.171728   

   delta energy_entropy_mean  delta spectral_centroid_mean  \
0                   0.021075                     -0.036732   
1                  -0.784841                      1.212088   
2                  -0.597608                      0.543013   
3                   0.801992                     -1.043029   
4                   2.519842                     -1.156328   

   delta spectral_flux_mean  delta mfcc_3_mean  delta mfcc_5_mean  \
0                  0.168898           0.100105          -0.545485   
1                  0.265458           0.219724           0.196796   
2                 -0.074099           0.122335           0.136338   
3                 -0.207851          -0.582299          -0.608932   
4                 -0.182258           0.147204           0.028075   

   delta mfcc_6_mean  delta mfcc_7_mean  delta mfcc_8_mean  delta mfcc_9_mean  \
0          -0.939821          -0.737115           0.050218          -0.258694   
1          -0.014682          -0.349859          -0.216845           0.328264   
2          -0.063935          -0.020577          -0.042186           0.170478   
3          -0.628397          -0.359062          -0.307344          -0.261815   
4          -0.069313          -0.005800           0.207935           0.196215   

   delta mfcc_10_mean  delta mfcc_11_mean  delta mfcc_12_mean  \
0           -0.980795           -0.301172            1.436076   
1            0.194414           -0.237414           -0.123792   
2            0.191330            0.094049           -0.228889   
3           -0.192146           -0.209867           -0.343258   
4            0.005832            0.115730            0.387804   

   delta mfcc_13_mean  delta chroma_1_mean  delta chroma_10_mean  energy_std  \
0            0.692711             0.011268              0.002831    0.033069   
1            0.539527             2.808774              1.866594   -0.941966   
2           -0.497537             

In [12]:
test_feat_dataset.features.head()

id_measurement  id_performance    datetime   plant  generation  \
0              29               5  2023-05-18   salad           1   
1             453              78  2023-08-07   basil           1   
2             467              80  2023-08-07   salad           3   
3             374              65  2023-07-31  tomato           2   
4             540              93  2023-08-25   salad           3   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             0              A1        1.356651        0.292482   
1             0              A4        0.282308        0.489948   
2             0              G2       -0.261635        0.598862   
3             7              O2        2.211007        0.473628   
4             0              D1        0.060171        0.467523   

   lib_mfcc_3_avg  lib_mfcc_13_avg  lib_mfcc_1_std  lib_mfcc_3_std  \
0       -0.280452        -0.894066       -1.106874       -0.555395   
1        0.272371        -0.761095       -0.804739       -0.777955   
2        0.581525         0.395490        0.007289       -0.688728   
3        0.179504        -1.421178       -0.822051       -0.943051   
4        0.268370        -0.910004       -1.438499       -0.762338   

   lib_mfcc_13_std  energy_mean  energy_entropy_mean  mfcc_9_mean  \
0         0.277695    -0.845011            -0.253397     0.643787   
1        -0.805219    -0.019760             0.167190     0.776884   
2        -0.314916    -0.366589             0.070332    -0.386942   
3         0.366389    -0.940942            -0.870948    -2.058097   
4        -0.819537    -0.322182             0.061151     0.533057   

   mfcc_11_mean  mfcc_13_mean  delta zcr_mean  delta energy_mean  \
0      0.173811      0.966136        0.004585          -0.118803   
1      1.450099      0.168034        0.004585          -0.163154   
2     -0.543903     -1.268221        0.004585          -0.106472   
3     -2.122247     -0.996094        0.004585           0.765109   
4      0.137307      1.379305        0.004585           0.082018   

   delta energy_entropy_mean  delta spectral_centroid_mean  \
0                  -0.034703                      0.026669   
1                   0.004365                      0.091136   
2                   0.017203                      0.006301   
3                  -0.086881                      0.370595   
4                  -0.009984                      0.265838   

   delta spectral_flux_mean  delta mfcc_3_mean  delta mfcc_5_mean  \
0                 -0.198596           0.012886           0.236682   
1                  0.116779           0.164831           0.121855   
2                  0.034576           0.018272           0.022319   
3                 -0.203160           0.368842           0.359437   
4                 -0.091264           0.493620           0.475057   

   delta mfcc_6_mean  delta mfcc_7_mean  delta mfcc_8_mean  delta mfcc_9_mean  \
0           0.194438          -0.024680          -0.080664           0.013635   
1           0.184757           0.088217           0.099071           0.188832   
2           0.018958           0.016054           0.013055          -0.010004   
3           0.457717           0.210595           0.182175           0.282843   
4           0.477187           0.257992           0.228510           0.191046   

   delta mfcc_10_mean  delta mfcc_11_mean  delta mfcc_12_mean  \
0           -0.116880           -0.124179            0.318651   
1            0.190922            0.217789            0.224130   
2           -0.003202           -0.007450            0.017543   
3            0.067277            0.152166            0.170507   
4            0.190319            0.199437            0.238505   

   delta mfcc_13_mean  delta chroma_1_mean  delta chroma_10_mean  energy_std  \
0            0.391812            -0.009785              0.014432   -0.143464   
1            0.175478             0.015645              0.003276   -0.115978   
2            0.015495             

In [13]:
train_feat_dataset.print_target_distribution()

Counts and Percentages:
Class 0: Count = 3311, Percentage = 49.33%
Class 1: Count = 3401, Percentage = 50.67%


In [14]:
test_feat_dataset.print_target_distribution()

Counts and Percentages:
Class 0: Count = 838, Percentage = 49.94%
Class 1: Count = 840, Percentage = 50.06%


In [15]:
train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

In [16]:
experiment = Experiment(train_df, test_df, 'target')

In [ ]:
classifier_par_dict = {
            "svm": np.array([0.001, 0.01, 0.5, 1.0, 5.0, 10.0, 20.0]),
            "svm_rbf": np.array([0.001, 0.01, 0.5, 1.0, 5.0, 10.0, 20.0]),
            "randomforest": np.array([10, 25, 50, 100, 200, 500]),
            "gradientboosting": np.array([10, 25, 50, 100, 200, 500]),
            "extratrees": np.array([10, 25, 50, 100, 200, 500]),
            "gaussiannb": []  # Naive Bayes does not require parameter tuning for this example
        }

experiment.run_all_models(classifier_par_dict)

Running experiments for svm
F1 Score: 0.33359809372517873
Accuracy: 0.5005959475566151
Precision: 0.25029797377830754
Recall: 0.5
[[  0 838]
 [  0 840]]
F1 Score: 0.6562977604938802
Accuracy: 0.6591179976162098
Precision: 0.6643337444209537
Recall: 0.6590109671553586
[[477 361]
 [211 629]]
F1 Score: 0.6736155812726411
Accuracy: 0.6764004767580453
Precision: 0.6824376474739233
Recall: 0.6762913399249915
[[490 348]
 [195 645]]
F1 Score: 0.6806037178509226
Accuracy: 0.6829558998808105
Precision: 0.6883251983987639
Recall: 0.6828545857483805
[[501 337]
 [195 645]]
F1 Score: 0.6901542804996292
Accuracy: 0.6912991656734208
Precision: 0.6940393818831805
Recall: 0.6912276963291283
[[529 309]
 [209 631]]
F1 Score: 0.7012414681115327
Accuracy: 0.7020262216924911
Precision: 0.7040603075085834
Recall: 0.7019661325150586
[[546 292]
 [208 632]]
F1 Score: 0.7008002477084301
Accuracy: 0.701430274135876
Precision: 0.703042347936317
Recall: 0.7013765768837368
[[550 288]
 [213 627]]
Running experiments f

## RQ4

In [ ]:
rq4= feat_dataset.return_subset_given_research_question(4)
train_feat_dataset, _, test_feat_dataset= rq1.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= True)

# Reduce the features that are correlated in the training data
train_cols, feat_stats= train_feat_dataset.reduce_features_based_on_target(corr_threshold=0.8)
test_feat_dataset.keep_only_specified_variable_columns(train_cols)

# Normalize features ?????
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)


In [ ]:
feat_stats.head(150)

In [ ]:
train_feat_dataset.features.head()

In [ ]:
test_feat_dataset.features.head()

In [ ]:
train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

## RQ3

In [ ]:
### Data preparation

# Reduce the Dataset for the datapoints concerning rq3

rq3_train_feat_dataset= train_feat_dataset.copy()
processed_train_indexes, train_targets= ped.get_indexes_and_targets_by_rq(3, rq3_train_feat_dataset.features)
rq3_train_feat_dataset.features= rq3_train_feat_dataset.features.iloc[processed_train_indexes]
rq3_train_feat_dataset.features.reset_index(drop=True, inplace=True)

rq3_test_feat_dataset= test_feat_dataset.copy()
processed_test_indexes, test_targets= ped.get_indexes_and_targets_by_rq(3, rq3_test_feat_dataset.features)
rq3_test_feat_dataset.features= rq3_test_feat_dataset.features.iloc[processed_test_indexes]
rq3_test_feat_dataset.features.reset_index(drop=True, inplace=True)

# Reduce the features that are correlated in the training data
train_cols= rq3_train_feat_dataset.reduce_features(targets= train_targets, corr_threshold=0.75)
rq3_test_feat_dataset.keep_only_specified_variable_columns(train_cols)

# Normalize features
normalization_params= rq3_train_feat_dataset.normalize_features()
rq3_test_feat_dataset.apply_normalization(normalization_params)

rq3_train_feat_dataset.objective_features.head()

rq3_test_feat_dataset.objective_features.head()

train_loader= rq3_train_feat_dataset.get_variable_features_loader(train_targets)
test_loader= rq3_test_feat_dataset.get_variable_features_loader(test_targets)

# Train dataset
print_counts_and_percentages(train_targets)

# Test dataset
print_counts_and_percentages(test_targets)

### Training

num_epochs = 50

input_size= len(rq3_train_feat_dataset.variable_columns)
output_size= 4
num_epochs = 50

parameters = {
    'learning_rate': 0.0003,
    'dense_units': 64,
    'dense_layers': 1,
    'dropout_rate': 0
}

model = FullyConnectedClassifier(input_size= input_size, output_size= output_size, parameters= parameters)

model.train_model(train_loader, test_loader, num_epochs)

### Evaluation

test_predictions = model.predict(test_loader)

actual_labels = []
for _, labels in test_loader:
    actual_labels.extend(labels.tolist())

correct_predictions = sum(p == t for p, t in zip(test_predictions, actual_labels))
accuracy = correct_predictions / len(actual_labels)
print(f"Accuracy: {accuracy:.4f}")


from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix

# Assuming your task is a classification task
precision = precision_score(actual_labels, test_predictions, average='macro')
recall = recall_score(actual_labels, test_predictions, average='macro')
f1 = f1_score(actual_labels, test_predictions, average='macro')

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")

# Confusion Matrix
conf_matrix = confusion_matrix(actual_labels, test_predictions)
print("Confusion Matrix:\n", conf_matrix)

## RQ4

In [ ]:
### Data preparation

# Reduce the Dataset for the datapoints concerning rq4

rq4_train_feat_dataset= train_feat_dataset.copy()
processed_train_indexes, train_targets= ped.get_indexes_and_targets_by_rq(4, rq4_train_feat_dataset.features)
rq4_train_feat_dataset.features= rq4_train_feat_dataset.features.iloc[processed_train_indexes]
rq4_train_feat_dataset.features.reset_index(drop=True, inplace=True)

rq4_test_feat_dataset= test_feat_dataset.copy()
processed_test_indexes, test_targets= ped.get_indexes_and_targets_by_rq(4, rq4_test_feat_dataset.features)
rq4_test_feat_dataset.features= rq4_test_feat_dataset.features.iloc[processed_test_indexes]
rq4_test_feat_dataset.features.reset_index(drop=True, inplace=True)

# Reduce the features that are correlated in the training data
train_cols= rq4_train_feat_dataset.reduce_features(targets= train_targets, corr_threshold=0.75)
rq4_test_feat_dataset.keep_only_specified_variable_columns(train_cols)

# Normalize features
normalization_params= rq4_train_feat_dataset.normalize_features()
rq4_test_feat_dataset.apply_normalization(normalization_params)

rq4_train_feat_dataset.objective_features.head()

rq4_test_feat_dataset.objective_features.head()

train_loader= rq4_train_feat_dataset.get_variable_features_loader(train_targets)
test_loader= rq4_test_feat_dataset.get_variable_features_loader(test_targets)

# Train dataset
print_counts_and_percentages(train_targets)

# Test dataset
print_counts_and_percentages(test_targets)

### Training

num_epochs = 50

input_size= len(rq4_train_feat_dataset.variable_columns)
output_size= 4
num_epochs = 50

parameters = {
    'learning_rate': 0.0003,
    'dense_units': 64,
    'dense_layers': 2,
    'dropout_rate': 0.2
}

model = FullyConnectedClassifier(input_size= input_size, output_size= output_size, parameters= parameters)

model.train_model(train_loader, test_loader, num_epochs)

### Evaluation

test_predictions = model.predict(test_loader)

actual_labels = []
for _, labels in test_loader:
    actual_labels.extend(labels.tolist())

correct_predictions = sum(p == t for p, t in zip(test_predictions, actual_labels))
accuracy = correct_predictions / len(actual_labels)
print(f"Accuracy: {accuracy:.4f}")


from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix

# Assuming your task is a classification task
precision = precision_score(actual_labels, test_predictions, average='macro')
recall = recall_score(actual_labels, test_predictions, average='macro')
f1 = f1_score(actual_labels, test_predictions, average='macro')

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")

# Confusion Matrix
conf_matrix = confusion_matrix(actual_labels, test_predictions)
print("Confusion Matrix:\n", conf_matrix)