# Experiment Eurythmy Letter

In [1]:
from PlantReactivityAnalysis.features.features_dataset import FeaturesDataset
from PlantReactivityAnalysis.models.experiment import Experiment
from PlantReactivityAnalysis.config import PROCESSED_DATA_DIR

In [2]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# No normalize

## All waves

In [3]:
norm_letters_signal_dataset_path= r"..\data\processed\feat_raw_letters_1_1_dataset.pkl"
feat_dataset = FeaturesDataset.load(file_path=norm_letters_signal_dataset_path)
feat_dataset.features.shape

(8390, 187)

In [4]:
feat_dataset.features.head()

id_measurement  id_performance    datetime  plant  generation  \
0               1               1  2023-04-29  salad           1   
1               1               1  2023-04-29  salad           1   
2               1               1  2023-04-29  salad           1   
3               1               1  2023-04-29  salad           1   
4               1               1  2023-04-29  salad           1   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             1              A1     -875.934448       90.174561   
1             1              G1     -881.704285       82.757996   
2             1              D1     -910.192993       89.565781   
3             1              A2     -882.572571       89.329361   
4             1              G2     -857.099609       89.547325   

   lib_mfcc_3_avg  lib_mfcc_4_avg  lib_mfcc_5_avg  lib_mfcc_6_avg  \
0       27.036600       24.335978       17.266857       14.362387   
1       25.871546       23.203876       16.568825       13.680217   
2       26.833704       24.053741       17.038734       14.083481   
3       26.286102       23.565893       16.590597       13.793759   
4       26.392532       23.654797       16.990082       13.819170   

   lib_mfcc_7_avg  lib_mfcc_8_avg  lib_mfcc_9_avg  lib_mfcc_10_avg  \
0       11.513890       10.139982        8.895366         8.150114   
1       10.881258        9.404713        8.086088         7.254086   
2       11.297335        9.914130        8.742417         7.914444   
3       10.865271        9.511434        8.298739         7.412407   
4       10.877643       10.073779        8.636995         7.913766   

   lib_mfcc_11_avg  lib_mfcc_12_avg  lib_mfcc_13_avg  lib_mfcc_1_std  \
0         7.367686         6.810772         6.211969       80.213020   
1         6.448022         5.861232         5.357966      105.766289   
2         7.067588         6.395854         5.967819       28.670700   
3         6.718295         6.080798         5.607462       41.493301   
4         6.902275         6.574956         5.858723       47.930656   

   lib_mfcc_2_std  lib_mfcc_3_std  lib_mfcc_4_std  lib_mfcc_5_std  \
0        0.964405        0.915351        0.899567        0.918060   
1       19.532993        1.066367        0.911629        0.475148   
2        1.105085        0.961518        1.005593        0.891455   
3        0.539670        0.533153        0.578260        0.479409   
4        0.891346        1.438288        1.419913        0.598312   

   lib_mfcc_6_std  lib_mfcc_7_std  lib_mfcc_8_std  lib_mfcc_9_std  \
0        0.936695        0.952802        0.939777        0.936986   
1        0.472212        0.470265        0.211643        0.215753   
2        0.980889        0.943527        0.966510        0.908136   
3        0.545013        0.519312        0.465926        0.469057   
4        0.560690        0.867479        0.715572        1.146438   

   lib_mfcc_10_std  lib_mfcc_11_std  lib_mfcc_12_std  lib_mfcc_13_std  \
0         0.912120         0.908604         0.910060         0.925049   
1         0.384701         0.433127         0.414579         0.361710   
2         0.934234         0.942631         1.036578         0.945394   
3         0.469288         0.504040         0.476202         0.459609   
4         0.558412         0.738493         0.856107         0.679622   

   zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0  0.000111     0.173058             3.270264                0.034481   
1  0.000078     0.125596             3.240312                0.040663   
2  0.000045     0.464907             3.255116                0.031493   
3  0.000178     0.159426             3.140661                0.056633   
4  0.000089     0.214079             3.242801                0.035025   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.083165               0.013287            0.040835   
1              0.091113               0.011048            0.080317   
2   

In [5]:
feat_dataset.prepare_dataset(drop_constant= False, drop_flatness_columns= True, drop_nan_columns= True)

Removing columns with NaN values: ['kurtosis', 'skewness']


In [6]:
feat_dataset.features.shape

(8390, 179)

In [7]:
feat_dataset.features.head()

id_measurement  id_performance    datetime  plant  generation  \
0               1               1  2023-04-29  salad           1   
1               1               1  2023-04-29  salad           1   
2               1               1  2023-04-29  salad           1   
3               1               1  2023-04-29  salad           1   
4               1               1  2023-04-29  salad           1   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             1              A1     -875.934448       90.174561   
1             1              G1     -881.704285       82.757996   
2             1              D1     -910.192993       89.565781   
3             1              A2     -882.572571       89.329361   
4             1              G2     -857.099609       89.547325   

   lib_mfcc_3_avg  lib_mfcc_4_avg  lib_mfcc_5_avg  lib_mfcc_6_avg  \
0       27.036600       24.335978       17.266857       14.362387   
1       25.871546       23.203876       16.568825       13.680217   
2       26.833704       24.053741       17.038734       14.083481   
3       26.286102       23.565893       16.590597       13.793759   
4       26.392532       23.654797       16.990082       13.819170   

   lib_mfcc_7_avg  lib_mfcc_8_avg  lib_mfcc_9_avg  lib_mfcc_10_avg  \
0       11.513890       10.139982        8.895366         8.150114   
1       10.881258        9.404713        8.086088         7.254086   
2       11.297335        9.914130        8.742417         7.914444   
3       10.865271        9.511434        8.298739         7.412407   
4       10.877643       10.073779        8.636995         7.913766   

   lib_mfcc_11_avg  lib_mfcc_12_avg  lib_mfcc_13_avg  lib_mfcc_1_std  \
0         7.367686         6.810772         6.211969       80.213020   
1         6.448022         5.861232         5.357966      105.766289   
2         7.067588         6.395854         5.967819       28.670700   
3         6.718295         6.080798         5.607462       41.493301   
4         6.902275         6.574956         5.858723       47.930656   

   lib_mfcc_2_std  lib_mfcc_3_std  lib_mfcc_4_std  lib_mfcc_5_std  \
0        0.964405        0.915351        0.899567        0.918060   
1       19.532993        1.066367        0.911629        0.475148   
2        1.105085        0.961518        1.005593        0.891455   
3        0.539670        0.533153        0.578260        0.479409   
4        0.891346        1.438288        1.419913        0.598312   

   lib_mfcc_6_std  lib_mfcc_7_std  lib_mfcc_8_std  lib_mfcc_9_std  \
0        0.936695        0.952802        0.939777        0.936986   
1        0.472212        0.470265        0.211643        0.215753   
2        0.980889        0.943527        0.966510        0.908136   
3        0.545013        0.519312        0.465926        0.469057   
4        0.560690        0.867479        0.715572        1.146438   

   lib_mfcc_10_std  lib_mfcc_11_std  lib_mfcc_12_std  lib_mfcc_13_std  \
0         0.912120         0.908604         0.910060         0.925049   
1         0.384701         0.433127         0.414579         0.361710   
2         0.934234         0.942631         1.036578         0.945394   
3         0.469288         0.504040         0.476202         0.459609   
4         0.558412         0.738493         0.856107         0.679622   

   zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0  0.000111     0.173058             3.270264                0.034481   
1  0.000078     0.125596             3.240312                0.040663   
2  0.000045     0.464907             3.255116                0.031493   
3  0.000178     0.159426             3.140661                0.056633   
4  0.000089     0.214079             3.242801                0.035025   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.083165               0.013287            0.040835   
1              0.091113               0.011048            0.080317   
2   

### RQ2

Is there any difference in the signals when someone is performing eurythmy?

In [8]:
rq2= feat_dataset.return_subset_given_research_question(2)

In [9]:
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

In [11]:
train_feat_dataset.features.head()

id_measurement  id_performance    datetime  plant  generation  \
0             475              82  2023-08-09  basil           2   
1             566              98  2023-09-01  basil           2   
2             263              46  2023-07-11  salad           2   
3             450              78  2023-08-07  basil           1   
4             391              68  2023-08-03  basil           1   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             1              A3     -880.459229       71.563019   
1             1              D2     -896.631653       85.808647   
2             6              G4     -949.650330       67.309189   
3             8              G1     -795.675049       78.880585   
4             7              A3     -810.654114       87.828156   

   lib_mfcc_3_avg  lib_mfcc_4_avg  lib_mfcc_5_avg  lib_mfcc_6_avg  \
0       23.991701       21.145285       16.227755       13.742484   
1       27.747063       24.968508       18.187128       15.217049   
2       22.157995       20.148298       14.703094       12.416656   
3       29.892456       21.406147       16.141926       13.399346   
4       29.006947       25.058216       17.912081       15.055439   

   lib_mfcc_7_avg  lib_mfcc_8_avg  lib_mfcc_9_avg  lib_mfcc_10_avg  \
0       11.644545       10.626822        9.618996         9.039738   
1       12.366268       10.912021        9.647074         8.823382   
2       10.256170        9.128101        8.085982         7.351321   
3       10.171690        9.236697        8.519657         7.919306   
4       12.483369       10.987629        9.768634         9.011834   

   lib_mfcc_11_avg  lib_mfcc_12_avg  lib_mfcc_13_avg  lib_mfcc_1_std  \
0         8.394392         7.919742         7.545269      120.196518   
1         8.013020         7.440699         6.930818       85.467682   
2         6.590561         6.061846         5.665998      115.076538   
3         7.494448         6.658544         6.588222       66.250633   
4         8.225450         7.580260         7.040726      116.543167   

   lib_mfcc_2_std  lib_mfcc_3_std  lib_mfcc_4_std  lib_mfcc_5_std  \
0       34.452957        8.556121        6.925523        4.274146   
1       15.993590        1.049891        0.930527        1.679763   
2       34.340557        7.540725        6.540598        3.952466   
3       10.926257        7.070011        1.700248        3.287801   
4        8.239879        4.738056        1.198588        1.030159   

   lib_mfcc_6_std  lib_mfcc_7_std  lib_mfcc_8_std  lib_mfcc_9_std  \
0        2.901619        1.860963        1.433823        1.078408   
1        1.464717        1.366446        1.109129        1.008294   
2        3.001179        2.220136        1.730425        1.315918   
3        2.637811        2.737643        1.724636        1.666000   
4        1.226576        1.454841        1.375604        1.237955   

   lib_mfcc_10_std  lib_mfcc_11_std  lib_mfcc_12_std  lib_mfcc_13_std  \
0         0.981829         0.966609         1.032355         1.138148   
1         0.947752         0.979315         1.010565         1.050719   
2         0.984161         0.794953         0.710024         0.712893   
3         1.868276         1.464212         1.422490         2.352879   
4         1.261005         1.334958         1.311467         1.240611   

   zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0  0.000058     0.254142             3.283720                0.023365   
1  0.000109     0.180261             3.235023                0.044142   
2  0.000060     0.065282             3.218017                0.035373   
3  0.000100     0.055728             3.270676                0.036323   
4  0.000060     0.094347             3.268370                0.036718   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.061528               0.006047            0.018502   
1              0.094278               0.013050            0.090713   
2   

In [12]:
test_feat_dataset.features.head()

id_measurement  id_performance    datetime   plant  generation  \
0             479              83  2023-08-09   basil           2   
1             416              72  2023-08-03  tomato           1   
2             280              49  2023-07-17   basil           1   
3             275              48  2023-07-17   basil           1   
4              67              12  2023-05-25  tomato           1   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             4              A3     -711.887451       62.689941   
1             1              D3     -790.564514       89.822762   
2             3              A2     -814.757690       90.883659   
3             1              D1     -782.604187       90.869904   
4             2              A2     -789.200562       90.654129   

   lib_mfcc_3_avg  lib_mfcc_4_avg  lib_mfcc_5_avg  lib_mfcc_6_avg  \
0        8.145474       12.558309       11.950567       11.088002   
1       27.215578       24.541288       17.509035       14.597848   
2       27.945698       25.180027       18.065113       15.203221   
3       28.043188       25.277451       18.177601       15.189732   
4       28.305212       25.073265       18.395464       15.227588   

   lib_mfcc_7_avg  lib_mfcc_8_avg  lib_mfcc_9_avg  lib_mfcc_10_avg  \
0        8.972565        8.309328        9.825239         8.900867   
1       12.034195       11.109031       10.156904         9.171906   
2       12.417199       11.039510        9.801959         9.016986   
3       12.357979       11.112367        9.936504         8.988475   
4       12.664186       11.209818       10.022370         9.152474   

   lib_mfcc_11_avg  lib_mfcc_12_avg  lib_mfcc_13_avg  lib_mfcc_1_std  \
0         7.386439         8.338740         8.341283       72.899155   
1         8.420729         8.145185         7.672687      111.397324   
2         8.196719         7.609507         7.090735      100.144882   
3         8.216995         7.752489         7.079271       98.239616   
4         8.314251         7.824982         7.345011      116.887871   

   lib_mfcc_2_std  lib_mfcc_3_std  lib_mfcc_4_std  lib_mfcc_5_std  \
0       15.238992       10.113055        6.304989        4.466549   
1        3.050623        2.689927        2.505968        2.562865   
2        0.866735        0.981298        0.990165        0.969826   
3        0.837952        0.964049        0.973338        0.970217   
4        1.287291        1.738293        1.244434        1.601154   

   lib_mfcc_6_std  lib_mfcc_7_std  lib_mfcc_8_std  lib_mfcc_9_std  \
0        2.563611        5.138049        3.697608        4.867250   
1        2.448047        2.038227        1.834696        2.233138   
2        0.965834        0.961051        0.961254        0.959070   
3        0.985482        0.964651        0.938379        0.997051   
4        1.238707        1.375371        1.202419        1.310441   

   lib_mfcc_10_std  lib_mfcc_11_std  lib_mfcc_12_std  lib_mfcc_13_std  \
0         4.982327         3.554075         3.204032         1.942139   
1         1.534464         1.482080         1.425532         1.482663   
2         0.962719         0.959306         0.947183         0.940923   
3         0.855025         0.902222         1.039731         0.940296   
4         1.375739         1.365407         1.281857         1.247991   

   zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0  0.000276     0.084478             3.171518                0.059066   
1  0.000146     0.071578             3.235263                0.050285   
2  0.000301     0.131348             3.208188                0.060640   
3  0.000219     0.199114             3.169510                0.062500   
4  0.000030     0.229314             3.289115                0.031695   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.142697               0.019192            0.076614   
1              0.127404               0.011976            0.045666  

In [13]:
train_feat_dataset.print_target_distribution()

Counts and Percentages:
Class 1: Count = 1002, Percentage = 33.57%
Class 0: Count = 998, Percentage = 33.43%
Class 2: Count = 985, Percentage = 33.00%


In [14]:
test_feat_dataset.print_target_distribution()

Counts and Percentages:
Class 0: Count = 257, Percentage = 34.40%
Class 2: Count = 249, Percentage = 33.33%
Class 1: Count = 241, Percentage = 32.26%


In [15]:
train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

In [16]:
experiment = Experiment(train_df, test_df, 'target')

In [17]:
classifier_par_dict = {
            "svm": np.array([0.001, 0.01, 0.5, 1.0, 5.0, 10.0, 20.0]),
            "svm_rbf": np.array([0.001, 0.01, 0.5, 1.0, 5.0, 10.0, 20.0]),
            "randomforest": np.array([10, 25, 50, 100, 200, 500]),
            "gradientboosting": np.array([10, 25, 50, 100, 200, 500]),
            "extratrees": np.array([10, 25, 50, 100, 200, 500]),
            "gaussiannb": []  # Naive Bayes does not require parameter tuning for this example
        }

experiment.run_all_models(classifier_par_dict)

Running experiments for svm
F1 Score: 0.16261808367071526
Accuracy: 0.32262382864792505
Precision: 0.10754127621597502
Recall: 0.3333333333333333
[[  0 257   0]
 [  0 241   0]
 [  0 249   0]]
F1 Score: 0.16598976493519604
Accuracy: 0.32396251673360105
Precision: 0.17493261455525608
Recall: 0.3346303501945525
[[  1 256   0]
 [  0 241   0]
 [  4 245   0]]
F1 Score: 0.3430764577950692
Accuracy: 0.36813922356091033
Precision: 0.37713818578369
Recall: 0.37335746373884815
[[ 39 138  80]
 [ 31 154  56]
 [ 28 139  82]]
F1 Score: 0.3290528324723294
Accuracy: 0.3614457831325301
Precision: 0.3582042404956877
Recall: 0.3670752024463948
[[ 27 137  93]
 [ 31 152  58]
 [ 21 137  91]]
F1 Score: 0.30273125769471915
Accuracy: 0.34805890227576974
Precision: 0.326760246501056
Recall: 0.3540495298381421
[[ 13 132 112]
 [ 17 147  77]
 [ 17 132 100]]
F1 Score: 0.294145871930879
Accuracy: 0.35609103078982596
Precision: 0.3485076104298408
Recall: 0.3624122615935323
[[  4 129 124]
 [  6 146  89]
 [  2 131 116]]

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.3682020116141458
Accuracy: 0.3708165997322624
Precision: 0.36777284576904107
Recall: 0.37196264485964803
[[ 93  89  75]
 [ 61 113  67]
 [ 95  83  71]]
F1 Score: 0.35749156376216923
Accuracy: 0.35876840696117807
Precision: 0.35670157630230226
Recall: 0.3595589498583427
[[ 93  79  85]
 [ 71 105  65]
 [102  77  70]]
F1 Score: 0.3374039569063974
Accuracy: 0.3373493975903614
Precision: 0.3369176780838274
Recall: 0.33803169904972535
[[ 86  79  92]
 [ 68  96  77]
 [106  73  70]]
F1 Score: 0.34244047048737847
Accuracy: 0.3427041499330656
Precision: 0.3418750898189078
Recall: 0.343261437719059
[[ 89  82  86]
 [ 66  96  79]
 [105  73  71]]
F1 Score: 0.37556058659954766
Accuracy: 0.37617135207496655
Precision: 0.37513185173344454
Recall: 0.37627855605489696
[[103  75  79]
 [ 65  99  77]
 [ 95  75  79]]
Running experiments for extratrees
F1 Score: 0.3401039682828973
Accuracy: 0.34002677376171353
Precision: 0.3434231083501678
Recall: 0.33992579452900484
[[ 92  91  74]
 [105  84  52]
 [ 

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

In [18]:
experiment.print_best_result(metric='accuracy') # 0.388

Best accuracy result:
Model: gradientboosting, Parameter: 500, F1: 0.37556058659954766, Accuracy: 0.37617135207496655, Precision: 0.37513185173344454, Recall: 0.37627855605489696


### RQ1

In [19]:
rq1= feat_dataset.return_subset_given_research_question(1)
train_feat_dataset, _, test_feat_dataset= rq1.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

In [20]:
train_feat_dataset.features.head()

id_measurement  id_performance    datetime   plant  generation  \
0             250              44  2023-07-11   basil           1   
1             564              97  2023-08-28   salad           3   
2              58              10  2023-05-25   salad           1   
3             368              64  2023-07-31  tomato           2   
4             228              40  2023-07-03   salad           2   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             2              L2     -984.353882       72.062363   
1             0              A2     -818.986450       88.086792   
2             0              G2     -781.015686       87.241440   
3             1              O3     -797.384583       86.573006   
4             0              A2     -791.011230       78.968521   

   lib_mfcc_3_avg  lib_mfcc_4_avg  lib_mfcc_5_avg  lib_mfcc_6_avg  \
0       26.994862       22.293789       16.607067       13.501343   
1       25.406952       22.705082       15.743296       12.937368   
2       24.818596       22.490578       15.520187       12.595559   
3       30.114954       25.166069       18.358955       15.334175   
4       34.369801       24.734499       19.051226       15.849953   

   lib_mfcc_7_avg  lib_mfcc_8_avg  lib_mfcc_9_avg  lib_mfcc_10_avg  \
0       11.190329        9.766424        8.534622         7.925098   
1       10.149009        8.796450        7.501701         6.708362   
2        9.563180        8.139243        7.466263         7.822841   
3       12.573730       11.360179       10.115472         9.191726   
4       13.534989       11.764194       10.824710         9.875539   

   lib_mfcc_11_avg  lib_mfcc_12_avg  lib_mfcc_13_avg  lib_mfcc_1_std  \
0         7.268586         6.775272         6.310095       94.202049   
1         5.912003         5.656219         5.520934       33.756046   
2         8.022415         7.846031         6.958409       90.745903   
3         8.424232         7.844889         7.351725      114.184402   
4         9.051231         8.542490         8.072813      131.980698   

   lib_mfcc_2_std  lib_mfcc_3_std  lib_mfcc_4_std  lib_mfcc_5_std  \
0       28.033316        8.006542        5.193118        3.635555   
1        1.784163        1.335588        1.153985        1.043026   
2        4.476870        3.619431        3.056686        2.758509   
3       10.129804        5.190826        1.622984        1.238399   
4       12.726333        7.234793        2.105844        1.636038   

   lib_mfcc_6_std  lib_mfcc_7_std  lib_mfcc_8_std  lib_mfcc_9_std  \
0        2.393669        1.758913        1.213603        0.780233   
1        1.008179        0.955304        0.938447        1.022977   
2        2.606905        2.596127        2.714929        2.412201   
3        1.231493        1.259656        1.280356        1.394922   
4        1.647500        1.659786        1.598923        1.559331   

   lib_mfcc_10_std  lib_mfcc_11_std  lib_mfcc_12_std  lib_mfcc_13_std  \
0         0.764615         0.825168         0.919949         0.978499   
1         0.905879         0.701620         1.200501         1.798971   
2         1.983029         2.923973         2.873667         1.602103   
3         1.159196         1.180111         1.326008         1.264836   
4         1.563745         1.485044         1.491779         1.568525   

   zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0  0.000156     0.110040             3.275695                0.026890   
1  0.000180     0.091942             3.186005                0.055752   
2  0.000230     0.079721             3.179343                0.059919   
3  0.000100     0.263420             3.257697                0.040870   
4  0.000036     0.167064             3.294891                0.023311   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.044619               0.010462            0.130913   
1              0.137324               0.015816            0.046165  

In [21]:
test_feat_dataset.features.head()

id_measurement  id_performance    datetime   plant  generation  \
0             574              99  2023-09-01   basil           2   
1             140              25  2023-06-16   salad           2   
2             562              97  2023-08-28   salad           3   
3             159              28  2023-06-16  tomato           1   
4             469              81  2023-08-07   salad           3   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             8              A3     -845.898499       89.396019   
1             0              D2     -758.109985       87.538925   
2             6              A3     -846.114929       83.148682   
3             0              D3     -823.656982       90.881584   
4             2              D3     -863.238708       88.718987   

   lib_mfcc_3_avg  lib_mfcc_4_avg  lib_mfcc_5_avg  lib_mfcc_6_avg  \
0       26.602608       23.818747       16.730240       13.784444   
1       24.987276       22.342300       15.437116       12.680230   
2       30.481258       23.970394       18.093857       14.166443   
3       29.940357       25.302891       19.855745       15.725966   
4       26.031414       23.477215       16.613089       13.469542   

   lib_mfcc_7_avg  lib_mfcc_8_avg  lib_mfcc_9_avg  lib_mfcc_10_avg  \
0       10.908296        9.621327        8.488400         7.705795   
1        9.890129        8.636655        7.433048         6.669631   
2       12.131692       10.581286        9.344821         8.494385   
3       13.836607       11.821978       10.949828         9.948787   
4       10.892236        9.319530        8.217675         7.395226   

   lib_mfcc_11_avg  lib_mfcc_12_avg  lib_mfcc_13_avg  lib_mfcc_1_std  \
0         6.800262         6.284706         5.780249       68.879250   
1         5.817098         5.442785         5.347852       90.754463   
2         7.675378         7.219154         6.656241       60.986938   
3         9.288299         8.631245         8.123927      116.995422   
4         6.622736         5.977902         5.422625       11.914670   

   lib_mfcc_2_std  lib_mfcc_3_std  lib_mfcc_4_std  lib_mfcc_5_std  \
0        0.725962        0.637905        0.635416        0.638195   
1        2.736346        2.358171        2.231701        2.039582   
2       13.185537        4.563050        2.156363        1.076388   
3        1.277141        2.071290        1.136799        1.698365   
4        0.960347        1.016402        0.245247        0.519773   

   lib_mfcc_6_std  lib_mfcc_7_std  lib_mfcc_8_std  lib_mfcc_9_std  \
0        0.690607        0.754472        0.680362        0.635988   
1        1.950285        1.852568        1.789594        1.817933   
2        0.819837        0.888876        0.985783        0.906883   
3        1.027114        1.406372        1.124228        1.277441   
4        0.432678        0.490043        0.237372        0.321909   

   lib_mfcc_10_std  lib_mfcc_11_std  lib_mfcc_12_std  lib_mfcc_13_std  \
0         0.651745         0.655890         0.670030         0.683350   
1         1.884811         1.940225         1.673808         1.184727   
2         0.951015         0.824784         0.754877         0.864834   
3         1.200273         1.241871         1.211787         1.215586   
4         0.243016         0.248760         0.190538         0.211969   

   zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0  0.000191     0.272839             3.232645                0.044140   
1  0.000200     0.176442             3.166958                0.064692   
2  0.000015     0.116041             3.296461                0.021390   
3  0.000159     0.077311             3.130099                0.056789   
4  0.000367     0.105294             2.987837                0.081994   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.115910               0.013442            0.023178   
1              0.157924               0.017690            0.066575  

In [22]:
train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

Counts and Percentages:
Class 1: Count = 3395, Percentage = 50.58%
Class 0: Count = 3317, Percentage = 49.42%
Counts and Percentages:
Class 1: Count = 846, Percentage = 50.42%
Class 0: Count = 832, Percentage = 49.58%
Running experiments for svm
F1 Score: 0.33518225039619653
Accuracy: 0.5041716328963052
Precision: 0.2520858164481526
Recall: 0.5
[[  0 832]
 [  0 846]]
F1 Score: 0.44444357833300985
Accuracy: 0.5190703218116806
Precision: 0.5337943558399674
Recall: 0.5160483724313512
[[128 704]
 [103 743]]
F1 Score: 0.447623894547004
Accuracy: 0.5143027413587604
Precision: 0.5216367276196106
Recall: 0.5114395799236224
[[140 692]
 [123 723]]
F1 Score: 0.45381555153707054
Accuracy: 0.5172824791418356
Precision: 0.5264832491109863
Recall: 0.5144742225859247
[[148 684]
 [126 720]]
F1 Score: 0.45304436902487577
Accuracy: 0.5154946364719905
Precision: 0.5229221589409743
Recall: 0.5127111179305328
[[149 683]
 [130 716]]
F1 Score: 0.45495071684587807
Accuracy: 0.5160905840286055
Precision: 0.5237

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.7094808836996336
Accuracy: 0.7115613825983313
Precision: 0.7164953565428411
Recall: 0.7109048236042916
[[526 306]
 [178 668]]
F1 Score: 0.7085106200459801
Accuracy: 0.7103694874851013
Precision: 0.7146564659082979
Recall: 0.7097526254773595
[[529 303]
 [183 663]]
F1 Score: 0.7104989900180565
Accuracy: 0.7121573301549463
Precision: 0.7159789186986328
Recall: 0.7115754000727406
[[534 298]
 [185 661]]
F1 Score: 0.7104057554285192
Accuracy: 0.7115613825983313
Precision: 0.7140494439001902
Recall: 0.711083833424259
[[544 288]
 [196 650]]
F1 Score: 0.7031222911919486
Accuracy: 0.7038140643623361
Precision: 0.7050411986627436
Recall: 0.7034602882342245
[[550 282]
 [215 631]]
Running experiments for extratrees
F1 Score: 0.6702244445747529
Accuracy: 0.6704410011918951
Precision: 0.6712979793875575
Recall: 0.6707014911802145
[[584 248]
 [305 541]]
F1 Score: 0.6921817067232598
Accuracy: 0.6930870083432658
Precision: 0.6946201918592554
Recall: 0.6926827605019095
[[536 296]
 [219 627]]


<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

In [23]:
experiment.print_best_result(metric='accuracy') #0.717

Best accuracy result:
Model: randomforest, Parameter: 500, F1: 0.7159961197412636, Accuracy: 0.7181168057210966, Precision: 0.7234766242697594, Recall: 0.7174457855973813


## No flat Waves

In [24]:
feat_dataset = FeaturesDataset.load(file_path=norm_letters_signal_dataset_path)
feat_dataset.prepare_dataset(drop_constant= True, drop_flatness_columns= True, drop_nan_columns= True)

No columns with NaN values found.


In [26]:
feat_dataset.features.shape

(8245, 181)

### RQ2

In [25]:
rq2= feat_dataset.return_subset_given_research_question(2)
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Counts and Percentages:
Class 0: Count = 990, Percentage = 33.90%
Class 1: Count = 973, Percentage = 33.32%
Class 2: Count = 957, Percentage = 32.77%
Counts and Percentages:
Class 2: Count = 251, Percentage = 34.34%
Class 1: Count = 242, Percentage = 33.11%
Class 0: Count = 238, Percentage = 32.56%
Running experiments for svm
F1 Score: 0.16374269005847952
Accuracy: 0.32558139534883723
Precision: 0.10852713178294575
Recall: 0.3333333333333333
[[238   0   0]
 [242   0   0]
 [251   0   0]]
F1 Score: 0.16374269005847952
Accuracy: 0.32558139534883723
Precision: 0.10852713178294575
Recall: 0.3333333333333333
[[238   0   0]
 [242   0   0]
 [251   0   0]]
F1 Score: 0.29498097020149944
Accuracy: 0.36662106703146374
Precision: 0.24435827569342558
Recall: 0.3720628747366715
[[126 112   0]
 [100 142   0]
 [138 113   0]]
F1 Score: 0.2982533664293573
Accuracy: 0.3707250341997264
Precision: 0.24705553559308502
Recall: 0.3762182558974003
[[127 111   0]
 [ 98 144   0]
 [138 113   0]]
F1 Score: 0.299554

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.38130584971482423
Accuracy: 0.387140902872777
Precision: 0.38930183069069807
Recall: 0.38940725280925975
[[115  77  46]
 [ 83 106  53]
 [121  68  62]]
F1 Score: 0.40974519999383013
Accuracy: 0.4117647058823529
Precision: 0.4114014553923276
Recall: 0.4131264372332186
[[107  73  58]
 [ 68 114  60]
 [ 97  74  80]]
F1 Score: 0.40567349982498585
Accuracy: 0.4076607387140903
Precision: 0.40826094403142843
Recall: 0.40916243353552934
[[110  71  57]
 [ 71 110  61]
 [106  67  78]]
F1 Score: 0.38756261100011097
Accuracy: 0.3898768809849521
Precision: 0.3873792347317944
Recall: 0.3913178455011124
[[102  77  59]
 [ 60 110  72]
 [ 95  83  73]]
F1 Score: 0.3958273677221396
Accuracy: 0.3967168262653899
Precision: 0.3958076360549436
Recall: 0.39764155637560417
[[ 99  69  70]
 [ 69 108  65]
 [ 85  83  83]]
Running experiments for extratrees
F1 Score: 0.3455666169482119
Accuracy: 0.34610123119015046
Precision: 0.3476389710786574
Recall: 0.3470292730045164
[[95 90 53]
 [82 84 76]
 [85 92 74]]

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

### RQ1

In [27]:
rq1= feat_dataset.return_subset_given_research_question(1)
train_feat_dataset, _, test_feat_dataset= rq1.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Counts and Percentages:
Class 1: Count = 3352, Percentage = 50.82%
Class 0: Count = 3244, Percentage = 49.18%
Counts and Percentages:
Class 0: Count = 864, Percentage = 52.40%
Class 1: Count = 785, Percentage = 47.60%
Running experiments for svm
F1 Score: 0.32251437962202134
Accuracy: 0.47604608853850816
Precision: 0.23802304426925408
Recall: 0.5
[[  0 864]
 [  0 785]]
F1 Score: 0.42853668869683104
Accuracy: 0.5039417828987265
Precision: 0.5561888592448864
Recall: 0.5225436423684832
[[116 748]
 [ 70 715]]
F1 Score: 0.4422945154654002
Accuracy: 0.509399636143117
Precision: 0.5603757176298272
Recall: 0.5272278249587167
[[134 730]
 [ 79 706]]
F1 Score: 0.44260670909387606
Accuracy: 0.5075803517283202
Precision: 0.5538283553350127
Recall: 0.5251422800188724
[[137 727]
 [ 85 700]]
F1 Score: 0.44971468959928035
Accuracy: 0.5118253486961795
Precision: 0.5603267207639563
Recall: 0.5291349669733427
[[145 719]
 [ 86 699]]
F1 Score: 0.4511525086934923
Accuracy: 0.5124317768344451
Precision: 0.560

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.6974994032516156
Accuracy: 0.6979987871437234
Precision: 0.7045049950782248
Recall: 0.701555496579382
[[542 322]
 [176 609]]
F1 Score: 0.7049233565247103
Accuracy: 0.7052759248029109
Precision: 0.7109694729808735
Recall: 0.7085581799952819
[[553 311]
 [175 610]]
F1 Score: 0.7214687957807301
Accuracy: 0.7216494845360825
Precision: 0.7262277206837028
Recall: 0.7245326138240151
[[574 290]
 [169 616]]
F1 Score: 0.7234051944841711
Accuracy: 0.7234687689508793
Precision: 0.7267302113551595
Recall: 0.7258610521349376
[[584 280]
 [176 609]]
F1 Score: 0.7155747432699263
Accuracy: 0.7155852031534263
Precision: 0.7178083708570163
Recall: 0.717522558386412
[[585 279]
 [190 595]]
Running experiments for extratrees
F1 Score: 0.6663757406061894
Accuracy: 0.6676773802304427
Precision: 0.6668220454357117
Recall: 0.6662140245340882
[[602 262]
 [286 499]]
F1 Score: 0.6986529902437586
Accuracy: 0.6992116434202547
Precision: 0.7061242678889738
Recall: 0.702887620901156
[[541 323]
 [173 612]]
F1

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

## FR_1K < 50%

In [28]:
feat_dataset = FeaturesDataset.load(file_path=norm_letters_signal_dataset_path)

indexes_to_drop= feat_dataset.features[feat_dataset.features['flatness_ratio_1000'] > 0.5].index.tolist()
feat_dataset.prepare_dataset(drop_constant= False, drop_flatness_columns= True, drop_nan_columns= True)
feat_dataset.drop_rows(indexes_to_drop)

rq2= feat_dataset.return_subset_given_research_question(2)
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

Removing columns with NaN values: ['kurtosis', 'skewness']


In [29]:
feat_dataset.features.shape

(6757, 179)

### RQ 2

In [30]:
# Reduce the features that are correlated in the training data
train_cols, feat_stats= train_feat_dataset.reduce_features_based_on_target(corr_threshold=0.8)
test_feat_dataset.keep_only_specified_variable_columns(train_cols)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Reduced variable features from initial count to 56.
Counts and Percentages:
Class 2: Count = 721, Percentage = 33.40%
Class 0: Count = 720, Percentage = 33.35%
Class 1: Count = 718, Percentage = 33.26%
Counts and Percentages:
Class 0: Count = 188, Percentage = 34.81%
Class 1: Count = 184, Percentage = 34.07%
Class 2: Count = 168, Percentage = 31.11%
Running experiments for svm
F1 Score: 0.15819209039548024
Accuracy: 0.3111111111111111
Precision: 0.1037037037037037
Recall: 0.3333333333333333
[[  0   0 188]
 [  0   0 184]
 [  0   0 168]]
F1 Score: 0.15819209039548024
Accuracy: 0.3111111111111111
Precision: 0.1037037037037037
Recall: 0.3333333333333333
[[  0   0 188]
 [  0   0 184]
 [  0   0 168]]
F1 Score: 0.3226806968620872
Accuracy: 0.3685185185185185
Precision: 0.3596512217828825
Recall: 0.3735408131800361
[[ 11  92  85]
 [ 11 110  63]
 [ 10  80  78]]
F1 Score: 0.32560554263802727
Accuracy: 0.37037037037037035
Precision: 0.3666522982312456
Recall: 0.37514133004419775
[[ 12  93  83]
 [

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.3777491113404426
Accuracy: 0.37962962962962965
Precision: 0.37900368480725627
Recall: 0.3803944025960677
[[57 61 70]
 [44 83 57]
 [51 52 65]]
F1 Score: 0.3879267292676016
Accuracy: 0.3888888888888889
Precision: 0.38818946753729366
Recall: 0.39044902574042256
[[58 57 73]
 [52 81 51]
 [51 46 71]]
F1 Score: 0.36697278770644354
Accuracy: 0.36666666666666664
Precision: 0.36692876460539764
Recall: 0.36727089849199007
[[64 58 66]
 [67 70 47]
 [54 50 64]]
F1 Score: 0.3762468142186452
Accuracy: 0.37592592592592594
Precision: 0.3775168186932893
Recall: 0.3757341820477806
[[66 49 73]
 [60 76 48]
 [61 46 61]]
F1 Score: 0.3649997963506027
Accuracy: 0.3648148148148148
Precision: 0.3660272918280654
Recall: 0.3644810067104239
[[67 54 67]
 [66 71 47]
 [63 46 59]]
Running experiments for extratrees
F1 Score: 0.3050482912365339
Accuracy: 0.31296296296296294
Precision: 0.30413250514605894
Recall: 0.30884652658473194
[[78 58 52]
 [72 58 54]
 [70 65 33]]
F1 Score: 0.3464684758445444
Accuracy: 0.

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

### RQ 1

In [31]:
rq1= feat_dataset.return_subset_given_research_question(1)
train_feat_dataset, _, test_feat_dataset= rq1.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Counts and Percentages:
Class 0: Count = 2937, Percentage = 54.34%
Class 1: Count = 2468, Percentage = 45.66%
Counts and Percentages:
Class 0: Count = 767, Percentage = 56.73%
Class 1: Count = 585, Percentage = 43.27%
Running experiments for svm
F1 Score: 0.3619631901840491
Accuracy: 0.5673076923076923
Precision: 0.28365384615384615
Recall: 0.5
[[767   0]
 [585   0]]
F1 Score: 0.3619631901840491
Accuracy: 0.5673076923076923
Precision: 0.28365384615384615
Recall: 0.5
[[767   0]
 [585   0]]
F1 Score: 0.3619631901840491
Accuracy: 0.5673076923076923
Precision: 0.28365384615384615
Recall: 0.5
[[767   0]
 [585   0]]
F1 Score: 0.3619631901840491
Accuracy: 0.5673076923076923
Precision: 0.28365384615384615
Recall: 0.5
[[767   0]
 [585   0]]
F1 Score: 0.3619631901840491
Accuracy: 0.5673076923076923
Precision: 0.28365384615384615
Recall: 0.5
[[767   0]
 [585   0]]
F1 Score: 0.3619631901840491
Accuracy: 0.5673076923076923
Precision: 0.28365384615384615
Recall: 0.5
[[767   0]
 [585   0]]
F1 Score: 

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.6881750727904574
Accuracy: 0.6930473372781065
Precision: 0.6877811094452774
Recall: 0.6887005649717515
[[553 214]
 [201 384]]
F1 Score: 0.7007427509800995
Accuracy: 0.7048816568047337
Precision: 0.7001361771363894
Recall: 0.7017673475300594
[[556 211]
 [188 397]]
F1 Score: 0.710441745676645
Accuracy: 0.7144970414201184
Precision: 0.7098128102782968
Recall: 0.7114587860350572
[[563 204]
 [182 403]]
F1 Score: 0.7134196589810385
Accuracy: 0.716715976331361
Precision: 0.712696559926001
Recall: 0.7152397508329712
[[557 210]
 [173 412]]
F1 Score: 0.709114319895267
Accuracy: 0.7122781065088757
Precision: 0.708440049639585
Recall: 0.7111255975662756
[[552 215]
 [174 411]]
Running experiments for extratrees
F1 Score: 0.6712448992517395
Accuracy: 0.6819526627218935
Precision: 0.6757202462364524
Recall: 0.6697957409821818
[[583 184]
 [246 339]]
F1 Score: 0.6976353273033098
Accuracy: 0.7019230769230769
Precision: 0.6970664224599403
Recall: 0.6985513544835579
[[555 212]
 [191 394]]
F1 S

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

# Normalize

## All waves

In [32]:
feat_dataset = FeaturesDataset.load(file_path=norm_letters_signal_dataset_path)
feat_dataset.prepare_dataset(drop_constant= True, drop_flatness_columns= True, drop_nan_columns= True)

rq2= feat_dataset.return_subset_given_research_question(2)
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

No columns with NaN values found.


### RQ2

In [33]:
rq2= feat_dataset.return_subset_given_research_question(2)
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

# Normalize features
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Variable features were properly normalized using 'zscore' method.
Applied z-score normalization.
Counts and Percentages:
Class 0: Count = 990, Percentage = 33.90%
Class 1: Count = 973, Percentage = 33.32%
Class 2: Count = 957, Percentage = 32.77%
Counts and Percentages:
Class 2: Count = 251, Percentage = 34.34%
Class 1: Count = 242, Percentage = 33.11%
Class 0: Count = 238, Percentage = 32.56%
Running experiments for svm
F1 Score: 0.16374269005847952
Accuracy: 0.32558139534883723
Precision: 0.10852713178294575
Recall: 0.3333333333333333
[[238   0   0]
 [242   0   0]
 [251   0   0]]
F1 Score: 0.16374269005847952
Accuracy: 0.32558139534883723
Precision: 0.10852713178294575
Recall: 0.3333333333333333
[[238   0   0]
 [242   0   0]
 [251   0   0]]
F1 Score: 0.3370704477569671
Accuracy: 0.35157318741450067
Precision: 0.3620269492844121
Recall: 0.3543771069390517
[[104 108  26]
 [ 94 112  36]
 [103 107  41]]
F1 Score: 0.3422501186431093
Accuracy: 0.34746922024623805
Precision: 0.3526569750436

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.3946992851351718
Accuracy: 0.4049247606019152
Precision: 0.4031888378536725
Recall: 0.40779512226345216
[[123  76  39]
 [ 75 117  50]
 [120  75  56]]
F1 Score: 0.4190629778456887
Accuracy: 0.4213406292749658
Precision: 0.4211542856837862
Recall: 0.4229041193376366
[[115  69  54]
 [ 69 112  61]
 [ 97  73  81]]
F1 Score: 0.40796149640606233
Accuracy: 0.4103967168262654
Precision: 0.4088973215684832
Recall: 0.4120823924709985
[[115  64  59]
 [ 69 108  65]
 [ 99  75  77]]
F1 Score: 0.38913360873266395
Accuracy: 0.3898768809849521
Precision: 0.38888126028816616
Recall: 0.39092273174127573
[[102  75  61]
 [ 62 102  78]
 [ 90  80  81]]
F1 Score: 0.3810830174118857
Accuracy: 0.3816689466484268
Precision: 0.38127878045157454
Recall: 0.3824236816652182
[[ 94  73  71]
 [ 72 103  67]
 [ 90  79  82]]
Running experiments for extratrees
F1 Score: 0.3208865609780244
Accuracy: 0.3228454172366621
Precision: 0.32332492289430936
Recall: 0.3240577980229002
[[ 95  78  65]
 [ 99  76  67]
 [101  8

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

### RQ1

In [34]:
rq1= feat_dataset.return_subset_given_research_question(1)
train_feat_dataset, _, test_feat_dataset= rq1.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

# Normalize features
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Variable features were properly normalized using 'zscore' method.
Applied z-score normalization.
Counts and Percentages:
Class 1: Count = 3352, Percentage = 50.82%
Class 0: Count = 3244, Percentage = 49.18%
Counts and Percentages:
Class 0: Count = 864, Percentage = 52.40%
Class 1: Count = 785, Percentage = 47.60%
Running experiments for svm
F1 Score: 0.32251437962202134
Accuracy: 0.47604608853850816
Precision: 0.23802304426925408
Recall: 0.5
[[  0 864]
 [  0 785]]
F1 Score: 0.6755436969904751
Accuracy: 0.679805942995755
Precision: 0.7019557416649139
Recall: 0.6868733781552253
[[466 398]
 [130 655]]
F1 Score: 0.6964169890291194
Accuracy: 0.698605215281989
Precision: 0.7139612094258625
Recall: 0.7042890422269403
[[506 358]
 [139 646]]
F1 Score: 0.7007237358697425
Accuracy: 0.7028502122498483
Precision: 0.7182662538699691
Recall: 0.7085146850672328
[[510 354]
 [136 649]]
F1 Score: 0.7025307139718828
Accuracy: 0.7034566403881141
Precision: 0.7126872430219711
Recall: 0.7077538924274593
[[53

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.7047589926467337
Accuracy: 0.7052759248029109
Precision: 0.7121011394731958
Recall: 0.7089076138240151
[[547 317]
 [169 616]]
F1 Score: 0.7152568145460436
Accuracy: 0.7155852031534263
Precision: 0.7213290988250731
Recall: 0.7188620547298892
[[562 302]
 [167 618]]
F1 Score: 0.7176853278548194
Accuracy: 0.7180109157064888
Precision: 0.723787797459295
Recall: 0.7212933474876151
[[564 300]
 [165 620]]
F1 Score: 0.7246280536968048
Accuracy: 0.7246816252274105
Precision: 0.7278064311859551
Recall: 0.7270184595423449
[[586 278]
 [176 609]]
F1 Score: 0.733778047301395
Accuracy: 0.7337780473013947
Precision: 0.7354660592120783
Recall: 0.7354660592120783
[[605 259]
 [180 605]]
Running experiments for extratrees
F1 Score: 0.6843349682332733
Accuracy: 0.6858702243784112
Precision: 0.6852299362112446
Recall: 0.6840992863882991
[[623 241]
 [277 508]]
F1 Score: 0.7008883680629014
Accuracy: 0.7010309278350515
Precision: 0.7049428868120458
Recall: 0.7036919084689786
[[560 304]
 [189 596]]
F

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

## No flat

In [35]:
feat_dataset = FeaturesDataset.load(file_path=norm_letters_signal_dataset_path)
feat_dataset.prepare_dataset(drop_constant= True, drop_flatness_columns= True, drop_nan_columns= True)

rq2= feat_dataset.return_subset_given_research_question(2)
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

No columns with NaN values found.


### RQ2

In [36]:
rq2= feat_dataset.return_subset_given_research_question(2)
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

# Normalize features
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Variable features were properly normalized using 'zscore' method.
Applied z-score normalization.
Counts and Percentages:
Class 0: Count = 990, Percentage = 33.90%
Class 1: Count = 973, Percentage = 33.32%
Class 2: Count = 957, Percentage = 32.77%
Counts and Percentages:
Class 2: Count = 251, Percentage = 34.34%
Class 1: Count = 242, Percentage = 33.11%
Class 0: Count = 238, Percentage = 32.56%
Running experiments for svm
F1 Score: 0.16374269005847952
Accuracy: 0.32558139534883723
Precision: 0.10852713178294575
Recall: 0.3333333333333333
[[238   0   0]
 [242   0   0]
 [251   0   0]]
F1 Score: 0.16374269005847952
Accuracy: 0.32558139534883723
Precision: 0.10852713178294575
Recall: 0.3333333333333333
[[238   0   0]
 [242   0   0]
 [251   0   0]]
F1 Score: 0.3370704477569671
Accuracy: 0.35157318741450067
Precision: 0.3620269492844121
Recall: 0.3543771069390517
[[104 108  26]
 [ 94 112  36]
 [103 107  41]]
F1 Score: 0.3422501186431093
Accuracy: 0.34746922024623805
Precision: 0.3526569750436

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.4027610008628128
Accuracy: 0.4062927496580027
Precision: 0.41214412931568584
Recall: 0.40817395741016765
[[114  77  47]
 [ 83 111  48]
 [114  65  72]]
F1 Score: 0.4233707227025712
Accuracy: 0.42544459644322846
Precision: 0.42538846017106885
Recall: 0.4269607220584062
[[116  69  53]
 [ 68 112  62]
 [ 96  72  83]]
F1 Score: 0.4094490367954912
Accuracy: 0.4117647058823529
Precision: 0.41029171795609126
Recall: 0.41341041371933845
[[115  65  58]
 [ 68 108  66]
 [ 98  75  78]]
F1 Score: 0.39187617537632113
Accuracy: 0.39261285909712723
Precision: 0.39209337356403645
Recall: 0.3935556244821856
[[101  75  62]
 [ 67 103  72]
 [ 86  82  83]]
F1 Score: 0.38116424116424125
Accuracy: 0.3816689466484268
Precision: 0.3810874350364295
Recall: 0.3820146872749297
[[ 87  78  73]
 [ 67 105  70]
 [ 89  75  87]]
Running experiments for extratrees
F1 Score: 0.32961389037488426
Accuracy: 0.332421340629275
Precision: 0.33058878723903357
Recall: 0.33396358773992624
[[100  71  67]
 [ 94  81  67]
 [ 

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

### RQ1

In [37]:
rq1= feat_dataset.return_subset_given_research_question(1)
train_feat_dataset, _, test_feat_dataset= rq1.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

# Normalize features
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Variable features were properly normalized using 'zscore' method.
Applied z-score normalization.
Counts and Percentages:
Class 1: Count = 3352, Percentage = 50.82%
Class 0: Count = 3244, Percentage = 49.18%
Counts and Percentages:
Class 0: Count = 864, Percentage = 52.40%
Class 1: Count = 785, Percentage = 47.60%
Running experiments for svm
F1 Score: 0.32251437962202134
Accuracy: 0.47604608853850816
Precision: 0.23802304426925408
Recall: 0.5
[[  0 864]
 [  0 785]]
F1 Score: 0.6755436969904751
Accuracy: 0.679805942995755
Precision: 0.7019557416649139
Recall: 0.6868733781552253
[[466 398]
 [130 655]]
F1 Score: 0.6964169890291194
Accuracy: 0.698605215281989
Precision: 0.7139612094258625
Recall: 0.7042890422269403
[[506 358]
 [139 646]]
F1 Score: 0.7007237358697425
Accuracy: 0.7028502122498483
Precision: 0.7182662538699691
Recall: 0.7085146850672328
[[510 354]
 [136 649]]
F1 Score: 0.7025307139718828
Accuracy: 0.7034566403881141
Precision: 0.7126872430219711
Recall: 0.7077538924274593
[[53

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.7053513961789795
Accuracy: 0.7058823529411765
Precision: 0.7128172683847203
Recall: 0.7095445564991744
[[547 317]
 [168 617]]
F1 Score: 0.7152568145460436
Accuracy: 0.7155852031534263
Precision: 0.7213290988250731
Recall: 0.7188620547298892
[[562 302]
 [167 618]]
F1 Score: 0.7176853278548194
Accuracy: 0.7180109157064888
Precision: 0.723787797459295
Recall: 0.7212933474876151
[[564 300]
 [165 620]]
F1 Score: 0.7246280536968048
Accuracy: 0.7246816252274105
Precision: 0.7278064311859551
Recall: 0.7270184595423449
[[586 278]
 [176 609]]
F1 Score: 0.7325647976222391
Accuracy: 0.7325651910248635
Precision: 0.7343646306177165
Recall: 0.7343086518046709
[[603 261]
 [180 605]]
Running experiments for extratrees
F1 Score: 0.6686014895377704
Accuracy: 0.6701030927835051
Precision: 0.6692989944981977
Recall: 0.668412361405992
[[608 256]
 [288 497]]
F1 Score: 0.6973384872349715
Accuracy: 0.6973923590054578
Precision: 0.700293483309616
Recall: 0.699637296532201
[[564 300]
 [199 586]]
F1 

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

## FR_1K < 50%

In [38]:
feat_dataset = FeaturesDataset.load(file_path=norm_letters_signal_dataset_path)

indexes_to_drop= feat_dataset.features[feat_dataset.features['flatness_ratio_1000'] > 0.5].index.tolist()
feat_dataset.prepare_dataset(drop_constant= False, drop_flatness_columns= True, drop_nan_columns= True)
feat_dataset.drop_rows(indexes_to_drop)

rq2= feat_dataset.return_subset_given_research_question(2)
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

Removing columns with NaN values: ['kurtosis', 'skewness']


### RQ2

In [39]:
rq2= feat_dataset.return_subset_given_research_question(2)
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

# Normalize features
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Variable features were properly normalized using 'zscore' method.
Applied z-score normalization.
Counts and Percentages:
Class 2: Count = 721, Percentage = 33.40%
Class 0: Count = 720, Percentage = 33.35%
Class 1: Count = 718, Percentage = 33.26%
Counts and Percentages:
Class 0: Count = 188, Percentage = 34.81%
Class 1: Count = 184, Percentage = 34.07%
Class 2: Count = 168, Percentage = 31.11%
Running experiments for svm
F1 Score: 0.15819209039548024
Accuracy: 0.3111111111111111
Precision: 0.1037037037037037
Recall: 0.3333333333333333
[[  0   0 188]
 [  0   0 184]
 [  0   0 168]]
F1 Score: 0.15819209039548024
Accuracy: 0.3111111111111111
Precision: 0.1037037037037037
Recall: 0.3333333333333333
[[  0   0 188]
 [  0   0 184]
 [  0   0 168]]
F1 Score: 0.3287556497343697
Accuracy: 0.3314814814814815
Precision: 0.32937902909223343
Recall: 0.3322981366459627
[[47 74 67]
 [57 75 52]
 [45 66 57]]
F1 Score: 0.33879847796780177
Accuracy: 0.34074074074074073
Precision: 0.3386968085106383
Recall: 

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.3735799259283124
Accuracy: 0.37592592592592594
Precision: 0.37625415229396747
Recall: 0.377020836086516
[[55 65 68]
 [42 82 60]
 [46 56 66]]
F1 Score: 0.363209394715123
Accuracy: 0.3648148148148148
Precision: 0.3655408249158249
Recall: 0.36528860696298254
[[55 54 79]
 [45 81 58]
 [50 57 61]]
F1 Score: 0.38868993664558515
Accuracy: 0.3888888888888889
Precision: 0.39025221186544545
Recall: 0.3902177583953717
[[64 54 70]
 [51 75 58]
 [49 48 71]]
F1 Score: 0.36293823675052056
Accuracy: 0.362962962962963
Precision: 0.3639095027943294
Recall: 0.36466455222236904
[[60 52 76]
 [63 67 54]
 [48 51 69]]
F1 Score: 0.3628264937304772
Accuracy: 0.362962962962963
Precision: 0.3635797700114587
Recall: 0.3644534748836321
[[61 58 69]
 [58 67 59]
 [48 52 68]]
Running experiments for extratrees
F1 Score: 0.30932996610569913
Accuracy: 0.31666666666666665
Precision: 0.3077361201856763
Recall: 0.3130625669941119
[[85 55 48]
 [75 48 61]
 [56 74 38]]
F1 Score: 0.3533215269578906
Accuracy: 0.3555555

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

### RQ1

In [40]:
rq1= feat_dataset.return_subset_given_research_question(1)
train_feat_dataset, _, test_feat_dataset= rq1.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

# Normalize features
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Variable features were properly normalized using 'zscore' method.
Applied z-score normalization.
Counts and Percentages:
Class 0: Count = 2937, Percentage = 54.34%
Class 1: Count = 2468, Percentage = 45.66%
Counts and Percentages:
Class 0: Count = 767, Percentage = 56.73%
Class 1: Count = 585, Percentage = 43.27%
Running experiments for svm
F1 Score: 0.3619631901840491
Accuracy: 0.5673076923076923
Precision: 0.28365384615384615
Recall: 0.5
[[767   0]
 [585   0]]
F1 Score: 0.6689461124764042
Accuracy: 0.6745562130177515
Precision: 0.6687611589523981
Recall: 0.6691583369549472
[[544 223]
 [217 368]]
F1 Score: 0.687078626799557
Accuracy: 0.6908284023668639
Precision: 0.6864788738602727
Recall: 0.6885701868752716
[[541 226]
 [192 393]]
F1 Score: 0.7031240344976739
Accuracy: 0.7056213017751479
Precision: 0.7028189002976615
Recall: 0.7060698247138926
[[539 228]
 [170 415]]
F1 Score: 0.7010532032507709
Accuracy: 0.7048816568047337
Precision: 0.7003941456352674
Recall: 0.7023757786469651
[[553

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.6931422964039279
Accuracy: 0.6982248520710059
Precision: 0.6928682676904687
Recall: 0.693466608720846
[[559 208]
 [200 385]]
F1 Score: 0.6989180192582909
Accuracy: 0.7034023668639053
Precision: 0.6984119601328904
Recall: 0.6996523250760538
[[558 209]
 [192 393]]
F1 Score: 0.705548643803391
Accuracy: 0.709319526627219
Precision: 0.7048696627031417
Recall: 0.7068955526582645
[[556 211]
 [182 403]]
F1 Score: 0.7167390538014885
Accuracy: 0.7204142011834319
Precision: 0.7160176332816048
Recall: 0.7180935825003621
[[564 203]
 [175 410]]
F1 Score: 0.7022435102879201
Accuracy: 0.7056213017751479
Precision: 0.7015833382874581
Recall: 0.7040417209908736
[[549 218]
 [180 405]]
Running experiments for extratrees
F1 Score: 0.6550863286410642
Accuracy: 0.6686390532544378
Precision: 0.6621308267179141
Recall: 0.6538026944806605
[[586 181]
 [267 318]]
F1 Score: 0.6795132498952166
Accuracy: 0.6841715976331361
Precision: 0.6790337146297412
Recall: 0.6802694480660583
[[544 223]
 [204 381]]
F1

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>