# Experiment Eurythmy Letter

In [1]:
from PlantReactivityAnalysis.features.features_dataset import FeaturesDataset
from PlantReactivityAnalysis.models.experiment import Experiment
from PlantReactivityAnalysis.config import PROCESSED_DATA_DIR

In [2]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# No normalize

## All waves

In [3]:
norm_letters_signal_dataset_path= r"..\data\processed\feat_norm_letters_1_1_dataset.pkl"
feat_dataset = FeaturesDataset.load(file_path=norm_letters_signal_dataset_path)
feat_dataset.features.shape

(8390, 187)

In [4]:
feat_dataset.features.head()

id_measurement  id_performance    datetime  plant  generation  \
0               1               1  2023-04-29  salad           1   
1               1               1  2023-04-29  salad           1   
2               1               1  2023-04-29  salad           1   
3               1               1  2023-04-29  salad           1   
4               1               1  2023-04-29  salad           1   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             1              A1      -85.835655       90.291260   
1             1              G1      -96.628212       83.604851   
2             1              D1     -109.998672       89.973495   
3             1              A2      -83.306580       89.631935   
4             1              G2      -65.591743       89.487083   

   lib_mfcc_3_avg  lib_mfcc_4_avg  lib_mfcc_5_avg  lib_mfcc_6_avg  \
0       27.150677       24.450397       17.381523       14.476572   
1       26.647131       23.880787       17.142712       14.166664   
2       27.083378       24.341211       17.288652       14.374680   
3       26.564987       23.834097       16.861643       14.067777   
4       26.376032       23.637720       16.882397       13.740993   

   lib_mfcc_7_avg  lib_mfcc_8_avg  lib_mfcc_9_avg  lib_mfcc_10_avg  \
0       11.628652       10.253779        9.009523         8.263220   
1       11.311499        9.815317        8.509996         7.710995   
2       11.574939       10.197500        8.994436         8.182779   
3       11.136328        9.779285        8.568973         7.687598   
4       10.826669        9.959647        8.586371         7.815620   

   lib_mfcc_11_avg  lib_mfcc_12_avg  lib_mfcc_13_avg  lib_mfcc_1_std  \
0         7.481691         6.924080         6.325689       87.071404   
1         6.942698         6.384663         5.894090      107.289284   
2         7.339973         6.694422         6.222746       45.244011   
3         6.993852         6.350812         5.871837       39.551929   
4         6.835242         6.490175         5.785554       57.464516   

   lib_mfcc_2_std  lib_mfcc_3_std  lib_mfcc_4_std  lib_mfcc_5_std  \
0        0.980359        0.953386        0.947235        0.955398   
1       17.435492        0.894234        0.777028        1.745475   
2        0.859658        0.939066        0.948810        0.866550   
3        0.491159        0.504996        0.560510        0.462185   
4        0.788460        1.222857        1.200740        0.515309   

   lib_mfcc_6_std  lib_mfcc_7_std  lib_mfcc_8_std  lib_mfcc_9_std  \
0        0.965027        0.979433        0.972912        0.969672   
1        1.486925        1.322912        0.952002        0.781681   
2        0.917197        0.897436        0.912217        0.878173   
3        0.536993        0.503689        0.455105        0.462463   
4        0.505040        0.743336        0.627253        1.033373   

   lib_mfcc_10_std  lib_mfcc_11_std  lib_mfcc_12_std  lib_mfcc_13_std  \
0         0.946374         0.945209         0.952646         0.956299   
1         0.693320         0.757019         0.842326         0.944447   
2         0.894446         0.902890         0.967887         0.915868   
3         0.449083         0.490654         0.456090         0.447698   
4         0.488459         0.632174         0.794163         0.601958   

   zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0  0.000111     0.175157             3.270264                0.034481   
1  0.000078     0.127419             3.240312                0.040663   
2  0.000045     0.477437             3.255116                0.031493   
3  0.000178     0.162887             3.140661                0.056633   
4  0.000089     0.216644             3.242801                0.035025   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.083165               0.013287            0.040835   
1              0.091113               0.011048            0.080317   
2   

In [5]:
feat_dataset.prepare_dataset(drop_constant= False, drop_flatness_columns= True, drop_nan_columns= True)

Removing columns with NaN values: ['kurtosis', 'skewness']


In [6]:
feat_dataset.features.shape

(8390, 179)

In [7]:
feat_dataset.features.head()

id_measurement  id_performance    datetime  plant  generation  \
0               1               1  2023-04-29  salad           1   
1               1               1  2023-04-29  salad           1   
2               1               1  2023-04-29  salad           1   
3               1               1  2023-04-29  salad           1   
4               1               1  2023-04-29  salad           1   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             1              A1      -85.835655       90.291260   
1             1              G1      -96.628212       83.604851   
2             1              D1     -109.998672       89.973495   
3             1              A2      -83.306580       89.631935   
4             1              G2      -65.591743       89.487083   

   lib_mfcc_3_avg  lib_mfcc_4_avg  lib_mfcc_5_avg  lib_mfcc_6_avg  \
0       27.150677       24.450397       17.381523       14.476572   
1       26.647131       23.880787       17.142712       14.166664   
2       27.083378       24.341211       17.288652       14.374680   
3       26.564987       23.834097       16.861643       14.067777   
4       26.376032       23.637720       16.882397       13.740993   

   lib_mfcc_7_avg  lib_mfcc_8_avg  lib_mfcc_9_avg  lib_mfcc_10_avg  \
0       11.628652       10.253779        9.009523         8.263220   
1       11.311499        9.815317        8.509996         7.710995   
2       11.574939       10.197500        8.994436         8.182779   
3       11.136328        9.779285        8.568973         7.687598   
4       10.826669        9.959647        8.586371         7.815620   

   lib_mfcc_11_avg  lib_mfcc_12_avg  lib_mfcc_13_avg  lib_mfcc_1_std  \
0         7.481691         6.924080         6.325689       87.071404   
1         6.942698         6.384663         5.894090      107.289284   
2         7.339973         6.694422         6.222746       45.244011   
3         6.993852         6.350812         5.871837       39.551929   
4         6.835242         6.490175         5.785554       57.464516   

   lib_mfcc_2_std  lib_mfcc_3_std  lib_mfcc_4_std  lib_mfcc_5_std  \
0        0.980359        0.953386        0.947235        0.955398   
1       17.435492        0.894234        0.777028        1.745475   
2        0.859658        0.939066        0.948810        0.866550   
3        0.491159        0.504996        0.560510        0.462185   
4        0.788460        1.222857        1.200740        0.515309   

   lib_mfcc_6_std  lib_mfcc_7_std  lib_mfcc_8_std  lib_mfcc_9_std  \
0        0.965027        0.979433        0.972912        0.969672   
1        1.486925        1.322912        0.952002        0.781681   
2        0.917197        0.897436        0.912217        0.878173   
3        0.536993        0.503689        0.455105        0.462463   
4        0.505040        0.743336        0.627253        1.033373   

   lib_mfcc_10_std  lib_mfcc_11_std  lib_mfcc_12_std  lib_mfcc_13_std  \
0         0.946374         0.945209         0.952646         0.956299   
1         0.693320         0.757019         0.842326         0.944447   
2         0.894446         0.902890         0.967887         0.915868   
3         0.449083         0.490654         0.456090         0.447698   
4         0.488459         0.632174         0.794163         0.601958   

   zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0  0.000111     0.175157             3.270264                0.034481   
1  0.000078     0.127419             3.240312                0.040663   
2  0.000045     0.477437             3.255116                0.031493   
3  0.000178     0.162887             3.140661                0.056633   
4  0.000089     0.216644             3.242801                0.035025   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.083165               0.013287            0.040835   
1              0.091113               0.011048            0.080317   
2   

In [16]:
classifier_par_dict = {
            "svm": np.array([0.001, 0.01, 0.5, 1.0, 5.0, 10.0, 20.0]),
            "svm_rbf": np.array([0.001, 0.01, 0.5, 1.0, 5.0, 10.0, 20.0]),
            "randomforest": np.array([10, 25, 50, 100, 200, 500]),
            "gradientboosting": np.array([10, 25, 50, 100, 200, 500]),
            "extratrees": np.array([10, 25, 50, 100, 200, 500]),
            "gaussiannb": []  # Naive Bayes does not require parameter tuning for this example
        }

Running experiments for svm
F1 Score: 0.16261808367071526
Accuracy: 0.32262382864792505
Precision: 0.10754127621597502
Recall: 0.3333333333333333
[[  0 257   0]
 [  0 241   0]
 [  0 249   0]]
F1 Score: 0.16261808367071526
Accuracy: 0.32262382864792505
Precision: 0.10754127621597502
Recall: 0.3333333333333333
[[  0 257   0]
 [  0 241   0]
 [  0 249   0]]
F1 Score: 0.30303191895571474
Accuracy: 0.34404283801874164
Precision: 0.340379347835785
Recall: 0.350427699571826
[[ 27 162  68]
 [ 22 169  50]
 [ 32 156  61]]
F1 Score: 0.30100897567041773
Accuracy: 0.3413654618473896
Precision: 0.3378577214146381
Recall: 0.3476559147342771
[[ 25 159  73]
 [ 20 165  56]
 [ 30 154  65]]
F1 Score: 0.3070782055133591
Accuracy: 0.3427041499330656
Precision: 0.34618167767573543
Recall: 0.34860019591959607
[[ 27 149  81]
 [ 18 158  65]
 [ 29 149  71]]
F1 Score: 0.3097713742809279
Accuracy: 0.3427041499330656
Precision: 0.34944684944684945
Recall: 0.3483835401343495
[[ 29 147  81]
 [ 19 155  67]
 [ 29 148  7

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.38151218534302495
Accuracy: 0.3815261044176707
Precision: 0.38141492374901986
Recall: 0.38166944651341644
[[100  71  86]
 [ 71  97  73]
 [ 82  79  88]]
F1 Score: 0.3722905442027749
Accuracy: 0.37215528781793844
Precision: 0.37264715669230525
Recall: 0.37319032495320253
[[ 85  72 100]
 [ 63 103  75]
 [ 80  79  90]]
F1 Score: 0.36960137108693986
Accuracy: 0.36947791164658633
Precision: 0.3697195333829734
Recall: 0.3701268415444557
[[90 76 91]
 [65 99 77]
 [82 80 87]]
F1 Score: 0.3560594492797882
Accuracy: 0.35609103078982596
Precision: 0.35785063557081825
Recall: 0.3569400171470172
[[82 81 94]
 [58 96 87]
 [75 86 88]]
F1 Score: 0.36614663825729127
Accuracy: 0.3668005354752343
Precision: 0.36755932309270634
Recall: 0.36808836651156024
[[ 80  82  95]
 [ 56 104  81]
 [ 75  84  90]]
Running experiments for extratrees
F1 Score: 0.32665753614765314
Accuracy: 0.3279785809906292
Precision: 0.3274469047932868
Recall: 0.3274442901874273
[[96 84 77]
 [95 78 68]
 [90 88 71]]
F1 Score: 0.

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

### RQ5

In [18]:
rq5= feat_dataset.return_subset_given_research_question(5)

In [19]:
train_feat_dataset, _, test_feat_dataset= rq5.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

In [20]:
train_feat_dataset.features.head()

id_measurement  id_performance    datetime   plant  generation  \
0             250              44  2023-07-11   basil           1   
1             564              97  2023-08-28   salad           3   
2              58              10  2023-05-25   salad           1   
3             368              64  2023-07-31  tomato           2   
4             228              40  2023-07-03   salad           2   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             2              L2     -159.394821       80.605270   
1             0              A2      -45.417221       88.046646   
2             0              G2     -102.984222       86.444092   
3             1              O3     -273.353607       82.576019   
4             0              A2     -135.637573       89.396629   

   lib_mfcc_3_avg  lib_mfcc_4_avg  lib_mfcc_5_avg  lib_mfcc_6_avg  \
0       23.797482       21.366404       15.020288       12.391527   
1       25.370852       22.669716       15.704741       12.898817   
2       24.081972       21.745403       14.775640       11.830242   
3       31.416300       25.208084       19.517088       15.599072   
4       26.643229       23.738396       16.424765       13.581029   

   lib_mfcc_7_avg  lib_mfcc_8_avg  lib_mfcc_9_avg  lib_mfcc_10_avg  \
0        9.819618        8.569760        7.490523         6.826966   
1       10.109165        8.766016        7.472760         6.663585   
2        8.812757        7.386414        6.726233         7.059811   
3       13.369842       11.664322       10.593497         9.600644   
4       11.367213       10.171313        8.440859         7.795256   

   lib_mfcc_11_avg  lib_mfcc_12_avg  lib_mfcc_13_avg  lib_mfcc_1_std  \
0         6.106288         5.562629         5.082755      136.227310   
1         5.819554         5.529524         5.418949       32.366005   
2         7.256543         7.080164         6.233261       54.146996   
3         9.031762         8.364903         7.863293      128.279877   
4         7.395786         6.322886         6.158155       60.444069   

   lib_mfcc_2_std  lib_mfcc_3_std  lib_mfcc_4_std  lib_mfcc_5_std  \
0       25.450811        6.518581        5.710754        3.597976   
1        1.859235        1.420116        1.253378        1.137155   
2        4.387800        3.541636        2.952601        2.671344   
3       15.740682        4.922906        2.004647        2.042346   
4        1.529504        1.210761        1.389220        2.170035   

   lib_mfcc_6_std  lib_mfcc_7_std  lib_mfcc_8_std  lib_mfcc_9_std  \
0        2.724567        1.874393        1.462501        1.109392   
1        1.098843        1.048671        1.039079        1.121951   
2        2.528495        2.571850        2.686394        2.317439   
3        1.556377        1.505978        1.358285        1.325060   
4        2.238100        1.002697        1.113283        1.465561   

   lib_mfcc_10_std  lib_mfcc_11_std  lib_mfcc_12_std  lib_mfcc_13_std  \
0         0.902392         0.677852         0.508814         0.374747   
1         1.005242         0.914551         1.451110         1.907380   
2         1.854790         2.933653         2.892549         1.386477   
3         1.271371         1.428745         1.493774         1.418100   
4         1.128291         1.173021         1.449605         0.977775   

   zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0  0.000156     0.119290             3.275695                0.026890   
1  0.000180     0.092360             3.186005                0.055752   
2  0.000230     0.080060             3.179343                0.059919   
3  0.000100     0.265341             3.257697                0.040869   
4  0.000036     0.167643             3.294891                0.023311   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.044619               0.010462            0.130913   
1              0.137324               0.015816            0.046165  

In [21]:
test_feat_dataset.features.head()

id_measurement  id_performance    datetime   plant  generation  \
0             574              99  2023-09-01   basil           2   
1             140              25  2023-06-16   salad           2   
2             562              97  2023-08-28   salad           3   
3             159              28  2023-06-16  tomato           1   
4             469              81  2023-08-07   salad           3   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             8              A3     -138.135971       89.766869   
1             0              D2     -191.967468       86.557663   
2             6              A3     -131.836197       83.116798   
3             0              D3     -120.983902       90.114517   
4             2              D3      -30.391010       88.988785   

   lib_mfcc_3_avg  lib_mfcc_4_avg  lib_mfcc_5_avg  lib_mfcc_6_avg  \
0       26.925928       24.124680       17.045929       14.111732   
1       24.033018       21.384439       14.472772       11.690976   
2       30.546103       23.995512       18.149092       14.204644   
3       27.058664       24.336161       17.283802       14.411300   
4       26.234344       23.689363       16.834785       13.689631   

   lib_mfcc_7_avg  lib_mfcc_8_avg  lib_mfcc_9_avg  lib_mfcc_10_avg  \
0       11.235825        9.942743        8.804521         8.023866   
1        8.883643        7.651146        6.494347         5.723831   
2       12.163241       10.622729        9.383395         8.538942   
3       11.602880       10.217814        8.952750         8.183155   
4       11.111129        9.543944        8.445748         7.616190   

   lib_mfcc_11_avg  lib_mfcc_12_avg  lib_mfcc_13_avg  lib_mfcc_1_std  \
0         7.117317         6.599966         6.095604       59.956814   
1         4.838871         4.490690         4.412056       28.996401   
2         7.711967         7.256431         6.692817       62.142448   
3         7.402377         6.824203         6.271512       39.675385   
4         6.840416         6.195661         5.642431       13.645220   

   lib_mfcc_2_std  lib_mfcc_3_std  lib_mfcc_4_std  lib_mfcc_5_std  \
0        0.879334        0.983698        0.922968        0.950484   
1        2.644965        2.258401        2.125343        1.925849   
2       13.238531        4.563087        2.169713        1.105187   
3        0.598314        0.579735        0.561640        0.578725   
4        0.920068        1.012910        0.274386        0.558537   

   lib_mfcc_6_std  lib_mfcc_7_std  lib_mfcc_8_std  lib_mfcc_9_std  \
0        1.038553        1.128241        1.046984        0.905019   
1        1.811670        1.715320        1.653571        1.706542   
2        0.802572        0.887123        0.973621        0.911481   
3        0.577053        0.564246        0.563509        0.574670   
4        0.426849        0.526363        0.251560        0.360515   

   lib_mfcc_10_std  lib_mfcc_11_std  lib_mfcc_12_std  lib_mfcc_13_std  \
0         0.942915         0.980540         0.947255         0.887942   
1         1.754618         1.790794         1.553343         1.140959   
2         0.948832         0.817504         0.746482         0.858330   
3         0.593068         0.590984         0.574768         0.555889   
4         0.282781         0.297333         0.242358         0.268318   

   zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0  0.000191     0.275431             3.232645                0.044140   
1  0.000200     0.177767             3.166958                0.064692   
2  0.000015     0.116271             3.296461                0.021390   
3  0.000159     0.078348             3.130099                0.056789   
4  0.000367     0.108143             2.987837                0.081994   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.115910               0.013442            0.023178   
1              0.157924               0.017690            0.066575  

In [22]:
train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

Counts and Percentages:
Class 0: Count = 2561, Percentage = 38.16%
Class 2: Count = 2152, Percentage = 32.06%
Class 1: Count = 1999, Percentage = 29.78%
Counts and Percentages:
Class 0: Count = 631, Percentage = 37.60%
Class 1: Count = 541, Percentage = 32.24%
Class 2: Count = 506, Percentage = 30.15%
Running experiments for svm
F1 Score: 0.18218565035368847
Accuracy: 0.37604290822407627
Precision: 0.1253476360746921
Recall: 0.3333333333333333
[[631   0   0]
 [541   0   0]
 [506   0   0]]
F1 Score: 0.18218565035368847
Accuracy: 0.37604290822407627
Precision: 0.1253476360746921
Recall: 0.3333333333333333
[[631   0   0]
 [541   0   0]
 [506   0   0]]
F1 Score: 0.19969208049052467
Accuracy: 0.3766388557806913
Precision: 0.24476074048201188
Recall: 0.3358190880067818
[[617   0  14]
 [528   0  13]
 [491   0  15]]
F1 Score: 0.19969208049052467
Accuracy: 0.3766388557806913
Precision: 0.24476074048201188
Recall: 0.3358190880067818
[[617   0  14]
 [528   0  13]
 [491   0  15]]
F1 Score: 0.20246

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.368409891084295
Accuracy: 0.41775923718712754
Precision: 0.4353298900500709
Recall: 0.39549744327289044
[[476  57  98]
 [363  98  80]
 [331  48 127]]
F1 Score: 0.40089294733971975
Accuracy: 0.43563766388557806
Precision: 0.44867258534711146
Recall: 0.4176277866354059
[[451  68 112]
 [322 119 100]
 [289  56 161]]
F1 Score: 0.4143897760787543
Accuracy: 0.43921334922526817
Precision: 0.44223535615989557
Recall: 0.42455773228674526
[[421  82 128]
 [282 141 118]
 [255  76 175]]
F1 Score: 0.43554010242461905
Accuracy: 0.4511323003575685
Precision: 0.45283013450863013
Recall: 0.4399778921382537
[[394  88 149]
 [237 171 133]
 [227  87 192]]
F1 Score: 0.4258572985448823
Accuracy: 0.43802145411203813
Precision: 0.43345082782953287
Recall: 0.4285398208801447
[[367 105 159]
 [217 182 142]
 [206 114 186]]
Running experiments for extratrees
F1 Score: 0.3854408799249441
Accuracy: 0.4028605482717521
Precision: 0.39525978087688546
Recall: 0.3906157870602139
[[365 114 152]
 [249 166 126]
 [2

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

In [23]:
experiment.print_best_result(metric='accuracy') #0.717

Best accuracy result:
Model: gradientboosting, Parameter: 200, F1: 0.43554010242461905, Accuracy: 0.4511323003575685, Precision: 0.45283013450863013, Recall: 0.4399778921382537


## No flat Waves

In [24]:
feat_dataset = FeaturesDataset.load(file_path=norm_letters_signal_dataset_path)
feat_dataset.prepare_dataset(drop_constant= True, drop_flatness_columns= True, drop_nan_columns= True)

No columns with NaN values found.


In [25]:
feat_dataset.features.shape

(8245, 181)

In [26]:
rq2= feat_dataset.return_subset_given_research_question(2)
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Counts and Percentages:
Class 0: Count = 990, Percentage = 33.90%
Class 1: Count = 973, Percentage = 33.32%
Class 2: Count = 957, Percentage = 32.77%
Counts and Percentages:
Class 2: Count = 251, Percentage = 34.34%
Class 1: Count = 242, Percentage = 33.11%
Class 0: Count = 238, Percentage = 32.56%
Running experiments for svm
F1 Score: 0.16374269005847952
Accuracy: 0.32558139534883723
Precision: 0.10852713178294575
Recall: 0.3333333333333333
[[238   0   0]
 [242   0   0]
 [251   0   0]]
F1 Score: 0.16374269005847952
Accuracy: 0.32558139534883723
Precision: 0.10852713178294575
Recall: 0.3333333333333333
[[238   0   0]
 [242   0   0]
 [251   0   0]]
F1 Score: 0.2652155736267886
Accuracy: 0.3447332421340629
Precision: 0.22714731849347233
Recall: 0.3488205199435146
[[ 74 164   0]
 [ 64 178   0]
 [ 86 165   0]]
F1 Score: 0.26479054449789247
Accuracy: 0.3433652530779754
Precision: 0.22628265494750796
Recall: 0.34746625923096514
[[ 75 163   0]
 [ 66 176   0]
 [ 87 164   0]]
F1 Score: 0.264630

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.41072372304676574
Accuracy: 0.4131326949384405
Precision: 0.41544429132853566
Recall: 0.41474922588969076
[[124  52  62]
 [ 82  95  65]
 [105  63  83]]
F1 Score: 0.42603254879988545
Accuracy: 0.426812585499316
Precision: 0.4285447778094837
Recall: 0.4278411506184905
[[118  58  62]
 [ 76 100  66]
 [ 94  63  94]]
F1 Score: 0.39829515410769173
Accuracy: 0.39808481532147744
Precision: 0.4009067484127485
Recall: 0.3990359371828149
[[104  60  74]
 [ 76 102  64]
 [104  62  85]]
F1 Score: 0.40355041122753343
Accuracy: 0.40355677154582764
Precision: 0.4045883661907923
Recall: 0.4041010760762769
[[104  64  70]
 [ 75  97  70]
 [ 90  67  94]]
F1 Score: 0.4032539840747755
Accuracy: 0.40355677154582764
Precision: 0.40390772994547525
Recall: 0.40436808222350545
[[107  62  69]
 [ 74  98  70]
 [ 89  72  90]]
Running experiments for extratrees
F1 Score: 0.34375061029196363
Accuracy: 0.3447332421340629
Precision: 0.34852363884621945
Recall: 0.3458062096130145
[[ 91  82  65]
 [ 95  92  55]
 [1

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

### RQ5

In [27]:
rq5= feat_dataset.return_subset_given_research_question(5)
train_feat_dataset, _, test_feat_dataset= rq5.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Counts and Percentages:
Class 0: Count = 2547, Percentage = 38.61%
Class 2: Count = 2086, Percentage = 31.63%
Class 1: Count = 1963, Percentage = 29.76%
Counts and Percentages:
Class 0: Count = 627, Percentage = 38.02%
Class 1: Count = 529, Percentage = 32.08%
Class 2: Count = 493, Percentage = 29.90%
Running experiments for svm
F1 Score: 0.1836555360281195
Accuracy: 0.3802304426925409
Precision: 0.12674348089751364
Recall: 0.3333333333333333
[[627   0   0]
 [529   0   0]
 [493   0   0]]
F1 Score: 0.1836555360281195
Accuracy: 0.3802304426925409
Precision: 0.12674348089751364
Recall: 0.3333333333333333
[[627   0   0]
 [529   0   0]
 [493   0   0]]
F1 Score: 0.19756896698073168
Accuracy: 0.38144329896907214
Precision: 0.24197974644403217
Recall: 0.3359861020798354
[[618   0   9]
 [517   0  12]
 [482   0  11]]
F1 Score: 0.19880730672104852
Accuracy: 0.38144329896907214
Precision: 0.23569288891869536
Recall: 0.3361306024912302
[[617   0  10]
 [514   0  15]
 [481   0  12]]
F1 Score: 0.19889

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.34947060108868194
Accuracy: 0.41297756215888415
Precision: 0.41658868133072247
Recall: 0.3870837151654678
[[487  43  97]
 [373  65  91]
 [321  43 129]]
F1 Score: 0.36686550524942385
Accuracy: 0.41540327471194666
Precision: 0.4110900751975801
Recall: 0.3929204628015944
[[458  58 111]
 [324  88 117]
 [295  59 139]]
F1 Score: 0.3977191705681076
Accuracy: 0.4275318374772589
Precision: 0.42338463467947113
Recall: 0.4106586945231561
[[418  78 131]
 [273 122 134]
 [253  75 165]]
F1 Score: 0.428074072506738
Accuracy: 0.4475439660400243
Precision: 0.4476838704830592
Recall: 0.43495374401909287
[[396  79 152]
 [234 148 147]
 [220  79 194]]
F1 Score: 0.4290893523331906
Accuracy: 0.4414796846573681
Precision: 0.43711326020116603
Recall: 0.43152807358562867
[[364 105 158]
 [207 176 146]
 [202 103 188]]
Running experiments for extratrees
F1 Score: 0.3864933631604999
Accuracy: 0.40388114008489995
Precision: 0.3945162786673526
Recall: 0.39079694928617953
[[358 132 137]
 [232 169 128]
 [242

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

## FR_1K < 50%

In [28]:
feat_dataset = FeaturesDataset.load(file_path=norm_letters_signal_dataset_path)

indexes_to_drop= feat_dataset.features[feat_dataset.features['flatness_ratio_1000'] > 0.5].index.tolist()
feat_dataset.prepare_dataset(drop_constant= False, drop_flatness_columns= True, drop_nan_columns= True)
feat_dataset.drop_rows(indexes_to_drop)

rq2= feat_dataset.return_subset_given_research_question(2)
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

Removing columns with NaN values: ['kurtosis', 'skewness']


In [29]:
feat_dataset.features.shape

(6757, 179)

### RQ 5

rq5= feat_dataset.return_subset_given_research_question(5)
train_feat_dataset, _, test_feat_dataset= rq5.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

# Normalize

## All waves

In [32]:
feat_dataset = FeaturesDataset.load(file_path=norm_letters_signal_dataset_path)
feat_dataset.prepare_dataset(drop_constant= True, drop_flatness_columns= True, drop_nan_columns= True)

rq2= feat_dataset.return_subset_given_research_question(2)
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

No columns with NaN values found.


In [33]:
rq2= feat_dataset.return_subset_given_research_question(2)
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

# Normalize features
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Variable features were properly normalized using 'zscore' method.
Applied z-score normalization.
Counts and Percentages:
Class 0: Count = 990, Percentage = 33.90%
Class 1: Count = 973, Percentage = 33.32%
Class 2: Count = 957, Percentage = 32.77%
Counts and Percentages:
Class 2: Count = 251, Percentage = 34.34%
Class 1: Count = 242, Percentage = 33.11%
Class 0: Count = 238, Percentage = 32.56%
Running experiments for svm
F1 Score: 0.16374269005847952
Accuracy: 0.32558139534883723
Precision: 0.10852713178294575
Recall: 0.3333333333333333
[[238   0   0]
 [242   0   0]
 [251   0   0]]
F1 Score: 0.16374269005847952
Accuracy: 0.32558139534883723
Precision: 0.10852713178294575
Recall: 0.3333333333333333
[[238   0   0]
 [242   0   0]
 [251   0   0]]
F1 Score: 0.3408791336797805
Accuracy: 0.3447332421340629
Precision: 0.3485867413243627
Recall: 0.34601303561825114
[[ 85 104  49]
 [ 82 105  55]
 [ 87 102  62]]
F1 Score: 0.34582612935427176
Accuracy: 0.34610123119015046
Precision: 0.346604658471

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.4238211774535457
Accuracy: 0.4240766073871409
Precision: 0.430032250133773
Recall: 0.4249381620219126
[[118  49  71]
 [ 81  95  66]
 [101  53  97]]
F1 Score: 0.4232947953284229
Accuracy: 0.4240766073871409
Precision: 0.4258722806516924
Recall: 0.4250137907061016
[[117  61  60]
 [ 77  98  67]
 [ 94  62  95]]
F1 Score: 0.39389566612347265
Accuracy: 0.39398084815321477
Precision: 0.3951893845533958
Recall: 0.39466293909483713
[[100  70  68]
 [ 76 100  66]
 [ 95  68  88]]
F1 Score: 0.3993847588834114
Accuracy: 0.399452804377565
Precision: 0.3996320301263377
Recall: 0.399975024088197
[[100  66  72]
 [ 75 100  67]
 [ 82  77  92]]
F1 Score: 0.3913869724456747
Accuracy: 0.3912448700410397
Precision: 0.39167249944675214
Recall: 0.3917630402066987
[[98 68 72]
 [68 98 76]
 [92 69 90]]
Running experiments for extratrees
F1 Score: 0.3295352301614947
Accuracy: 0.33105335157318744
Precision: 0.3336630476440443
Recall: 0.33217409317287877
[[ 95  81  62]
 [102  79  61]
 [100  83  68]]
F1 Sc

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

### RQ5

In [34]:
rq5= feat_dataset.return_subset_given_research_question(5)
train_feat_dataset, _, test_feat_dataset= rq5.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

# Normalize features
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Variable features were properly normalized using 'zscore' method.
Applied z-score normalization.
Counts and Percentages:
Class 0: Count = 2547, Percentage = 38.61%
Class 2: Count = 2086, Percentage = 31.63%
Class 1: Count = 1963, Percentage = 29.76%
Counts and Percentages:
Class 0: Count = 627, Percentage = 38.02%
Class 1: Count = 529, Percentage = 32.08%
Class 2: Count = 493, Percentage = 29.90%
Running experiments for svm
F1 Score: 0.1836555360281195
Accuracy: 0.3802304426925409
Precision: 0.12674348089751364
Recall: 0.3333333333333333
[[627   0   0]
 [529   0   0]
 [493   0   0]]
F1 Score: 0.1836555360281195
Accuracy: 0.3802304426925409
Precision: 0.12674348089751364
Recall: 0.3333333333333333
[[627   0   0]
 [529   0   0]
 [493   0   0]]
F1 Score: 0.3647859925193337
Accuracy: 0.41600970285021227
Precision: 0.41263938970871705
Recall: 0.39267711804225885
[[465  43 119]
 [335  86 108]
 [291  67 135]]
F1 Score: 0.38020773697892624
Accuracy: 0.41904184354154034
Precision: 0.42063851181

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.3451776728643314
Accuracy: 0.4105518496058217
Precision: 0.4114352771677879
Recall: 0.3843267102646297
[[488  42  97]
 [365  63 101]
 [326  41 126]]
F1 Score: 0.3720244183810806
Accuracy: 0.4178289872650091
Precision: 0.41235644101361507
Recall: 0.3961634437495578
[[453  59 115]
 [314  92 123]
 [286  63 144]]
F1 Score: 0.3927209864527945
Accuracy: 0.42389326864766524
Precision: 0.4192251631989355
Recall: 0.40711450219652107
[[417  75 135]
 [276 114 139]
 [253  72 168]]
F1 Score: 0.4252479202295149
Accuracy: 0.4426925409338993
Precision: 0.445538292315445
Recall: 0.4303325847406412
[[388  75 164]
 [223 156 150]
 [227  80 186]]
F1 Score: 0.4396580928522853
Accuracy: 0.4523953911461492
Precision: 0.44916837887998184
Recall: 0.44202339087108306
[[374  97 156]
 [205 181 143]
 [202 100 191]]
Running experiments for extratrees
F1 Score: 0.389577921507259
Accuracy: 0.40448756822316556
Precision: 0.3958651747601645
Recall: 0.3928656111091613
[[349 137 141]
 [231 167 131]
 [226 116 1

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

## No flat

In [35]:
feat_dataset = FeaturesDataset.load(file_path=norm_letters_signal_dataset_path)
feat_dataset.prepare_dataset(drop_constant= True, drop_flatness_columns= True, drop_nan_columns= True)

rq2= feat_dataset.return_subset_given_research_question(2)
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

No columns with NaN values found.


### RQ5

In [37]:
rq5= feat_dataset.return_subset_given_research_question(5)
train_feat_dataset, _, test_feat_dataset= rq5.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

# Normalize features
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Variable features were properly normalized using 'zscore' method.
Applied z-score normalization.
Counts and Percentages:
Class 0: Count = 2547, Percentage = 38.61%
Class 2: Count = 2086, Percentage = 31.63%
Class 1: Count = 1963, Percentage = 29.76%
Counts and Percentages:
Class 0: Count = 627, Percentage = 38.02%
Class 1: Count = 529, Percentage = 32.08%
Class 2: Count = 493, Percentage = 29.90%
Running experiments for svm
F1 Score: 0.1836555360281195
Accuracy: 0.3802304426925409
Precision: 0.12674348089751364
Recall: 0.3333333333333333
[[627   0   0]
 [529   0   0]
 [493   0   0]]
F1 Score: 0.1836555360281195
Accuracy: 0.3802304426925409
Precision: 0.12674348089751364
Recall: 0.3333333333333333
[[627   0   0]
 [529   0   0]
 [493   0   0]]
F1 Score: 0.3647859925193337
Accuracy: 0.41600970285021227
Precision: 0.41263938970871705
Recall: 0.39267711804225885
[[465  43 119]
 [335  86 108]
 [291  67 135]]
F1 Score: 0.38020773697892624
Accuracy: 0.41904184354154034
Precision: 0.42063851181

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.34439463368485784
Accuracy: 0.4099454214675561
Precision: 0.4098261419652009
Recall: 0.3836505777426555
[[488  42  97]
 [365  63 101]
 [326  42 125]]
F1 Score: 0.3708441458006018
Accuracy: 0.4166161309884779
Precision: 0.41044724206443317
Recall: 0.39495567911700397
[[452  59 116]
 [313  92 124]
 [286  64 143]]
F1 Score: 0.3938578175361496
Accuracy: 0.42510612492419647
Precision: 0.42033167182938397
Recall: 0.40832226682907474
[[418  75 134]
 [276 114 139]
 [252  72 169]]
F1 Score: 0.42663872261015107
Accuracy: 0.44390539721043054
Precision: 0.4475197246210989
Recall: 0.43168484978458976
[[388  74 165]
 [225 156 148]
 [226  79 188]]
F1 Score: 0.44194278717103225
Accuracy: 0.454214675560946
Precision: 0.4511125875157173
Recall: 0.44410426324994684
[[373 101 153]
 [207 183 139]
 [201  99 193]]
Running experiments for extratrees
F1 Score: 0.3814061989610326
Accuracy: 0.39781685870224376
Precision: 0.3876158351735784
Recall: 0.38542169135373006
[[350 136 141]
 [231 164 134]
 [2

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

## FR_1K < 50%

In [38]:
feat_dataset = FeaturesDataset.load(file_path=norm_letters_signal_dataset_path)

indexes_to_drop= feat_dataset.features[feat_dataset.features['flatness_ratio_1000'] > 0.5].index.tolist()
feat_dataset.prepare_dataset(drop_constant= False, drop_flatness_columns= True, drop_nan_columns= True)
feat_dataset.drop_rows(indexes_to_drop)

rq2= feat_dataset.return_subset_given_research_question(2)
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

Removing columns with NaN values: ['kurtosis', 'skewness']


### RQ5

In [40]:
rq5= feat_dataset.return_subset_given_research_question(5)
train_feat_dataset, _, test_feat_dataset= rq5.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

# Normalize features
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Variable features were properly normalized using 'zscore' method.
Applied z-score normalization.
Counts and Percentages:
Class 0: Count = 2125, Percentage = 39.32%
Class 2: Count = 1642, Percentage = 30.38%
Class 1: Count = 1638, Percentage = 30.31%
Counts and Percentages:
Class 0: Count = 499, Percentage = 36.91%
Class 2: Count = 432, Percentage = 31.95%
Class 1: Count = 421, Percentage = 31.14%
Running experiments for svm
F1 Score: 0.1797226724293175
Accuracy: 0.3690828402366864
Precision: 0.1230276134122288
Recall: 0.3333333333333333
[[499   0   0]
 [421   0   0]
 [432   0   0]]
F1 Score: 0.1797226724293175
Accuracy: 0.3690828402366864
Precision: 0.1230276134122288
Recall: 0.3333333333333333
[[499   0   0]
 [421   0   0]
 [432   0   0]]
F1 Score: 0.33883039167213774
Accuracy: 0.4119822485207101
Precision: 0.41971108141919977
Recall: 0.3886639551352786
[[415  53  31]
 [295  93  33]
 [306  77  49]]
F1 Score: 0.36339680890630355
Accuracy: 0.4156804733727811
Precision: 0.414808385688319

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.33475079335472363
Accuracy: 0.41420118343195267
Precision: 0.43666090722694495
Recall: 0.389021521974185
[[430  38  31]
 [319  73  29]
 [311  64  57]]
F1 Score: 0.3654224805112354
Accuracy: 0.4193786982248521
Precision: 0.42056052368724023
Recall: 0.3983971652874383
[[393  56  50]
 [283  80  58]
 [262  76  94]]
F1 Score: 0.4100180081839653
Accuracy: 0.4386094674556213
Precision: 0.44253292697078767
Recall: 0.4234984514056117
[[350  72  77]
 [236 109  76]
 [225  73 134]]
F1 Score: 0.4251530375029056
Accuracy: 0.4423076923076923
Precision: 0.4430887838960305
Recall: 0.4311152839975132
[[318  86  95]
 [207 131  83]
 [198  85 149]]
F1 Score: 0.4287408806530333
Accuracy: 0.4378698224852071
Precision: 0.43799716680424394
Recall: 0.4303307026063505
[[284 101 114]
 [188 147  86]
 [178  93 161]]
Running experiments for extratrees
F1 Score: 0.3949988154782915
Accuracy: 0.4119822485207101
Precision: 0.40404256049230053
Recall: 0.4015313661544961
[[298 110  91]
 [192 130  99]
 [193 110

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>