# Experiment Eurythmy Letter

In [1]:
from PlantReactivityAnalysis.features.features_dataset import FeaturesDataset
from PlantReactivityAnalysis.models.experiment import Experiment
from PlantReactivityAnalysis.config import PROCESSED_DATA_DIR

In [2]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# No normalize

## All waves

In [3]:
norm_letters_signal_dataset_path= r"..\data\processed\feat_raw_letters_1_1_dataset.pkl"
feat_dataset = FeaturesDataset.load(file_path=norm_letters_signal_dataset_path)
feat_dataset.features.shape

(8390, 187)

In [4]:
feat_dataset.features.head()

id_measurement  id_performance    datetime  plant  generation  \
0               1               1  2023-04-29  salad           1   
1               1               1  2023-04-29  salad           1   
2               1               1  2023-04-29  salad           1   
3               1               1  2023-04-29  salad           1   
4               1               1  2023-04-29  salad           1   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             1              A1     -875.934448       90.174561   
1             1              G1     -881.704285       82.757996   
2             1              D1     -910.192993       89.565781   
3             1              A2     -882.572571       89.329361   
4             1              G2     -857.099609       89.547325   

   lib_mfcc_3_avg  lib_mfcc_4_avg  lib_mfcc_5_avg  lib_mfcc_6_avg  \
0       27.036600       24.335978       17.266857       14.362387   
1       25.871546       23.203876       16.568825       13.680217   
2       26.833704       24.053741       17.038734       14.083481   
3       26.286102       23.565893       16.590597       13.793759   
4       26.392532       23.654797       16.990082       13.819170   

   lib_mfcc_7_avg  lib_mfcc_8_avg  lib_mfcc_9_avg  lib_mfcc_10_avg  \
0       11.513890       10.139982        8.895366         8.150114   
1       10.881258        9.404713        8.086088         7.254086   
2       11.297335        9.914130        8.742417         7.914444   
3       10.865271        9.511434        8.298739         7.412407   
4       10.877643       10.073779        8.636995         7.913766   

   lib_mfcc_11_avg  lib_mfcc_12_avg  lib_mfcc_13_avg  lib_mfcc_1_std  \
0         7.367686         6.810772         6.211969       80.213020   
1         6.448022         5.861232         5.357966      105.766289   
2         7.067588         6.395854         5.967819       28.670700   
3         6.718295         6.080798         5.607462       41.493301   
4         6.902275         6.574956         5.858723       47.930656   

   lib_mfcc_2_std  lib_mfcc_3_std  lib_mfcc_4_std  lib_mfcc_5_std  \
0        0.964405        0.915351        0.899567        0.918060   
1       19.532993        1.066367        0.911629        0.475148   
2        1.105085        0.961518        1.005593        0.891455   
3        0.539670        0.533153        0.578260        0.479409   
4        0.891346        1.438288        1.419913        0.598312   

   lib_mfcc_6_std  lib_mfcc_7_std  lib_mfcc_8_std  lib_mfcc_9_std  \
0        0.936695        0.952802        0.939777        0.936986   
1        0.472212        0.470265        0.211643        0.215753   
2        0.980889        0.943527        0.966510        0.908136   
3        0.545013        0.519312        0.465926        0.469057   
4        0.560690        0.867479        0.715572        1.146438   

   lib_mfcc_10_std  lib_mfcc_11_std  lib_mfcc_12_std  lib_mfcc_13_std  \
0         0.912120         0.908604         0.910060         0.925049   
1         0.384701         0.433127         0.414579         0.361710   
2         0.934234         0.942631         1.036578         0.945394   
3         0.469288         0.504040         0.476202         0.459609   
4         0.558412         0.738493         0.856107         0.679622   

   zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0  0.000111     0.173058             3.270264                0.034481   
1  0.000078     0.125596             3.240312                0.040663   
2  0.000045     0.464907             3.255116                0.031493   
3  0.000178     0.159426             3.140661                0.056633   
4  0.000089     0.214079             3.242801                0.035025   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.083165               0.013287            0.040835   
1              0.091113               0.011048            0.080317   
2   

In [5]:
feat_dataset.prepare_dataset(drop_constant= False, drop_flatness_columns= True, drop_nan_columns= True)

Removing columns with NaN values: ['skewness', 'kurtosis']


In [6]:
feat_dataset.features.shape

(8390, 179)

In [7]:
feat_dataset.features.head()

id_measurement  id_performance    datetime  plant  generation  \
0               1               1  2023-04-29  salad           1   
1               1               1  2023-04-29  salad           1   
2               1               1  2023-04-29  salad           1   
3               1               1  2023-04-29  salad           1   
4               1               1  2023-04-29  salad           1   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             1              A1     -875.934448       90.174561   
1             1              G1     -881.704285       82.757996   
2             1              D1     -910.192993       89.565781   
3             1              A2     -882.572571       89.329361   
4             1              G2     -857.099609       89.547325   

   lib_mfcc_3_avg  lib_mfcc_4_avg  lib_mfcc_5_avg  lib_mfcc_6_avg  \
0       27.036600       24.335978       17.266857       14.362387   
1       25.871546       23.203876       16.568825       13.680217   
2       26.833704       24.053741       17.038734       14.083481   
3       26.286102       23.565893       16.590597       13.793759   
4       26.392532       23.654797       16.990082       13.819170   

   lib_mfcc_7_avg  lib_mfcc_8_avg  lib_mfcc_9_avg  lib_mfcc_10_avg  \
0       11.513890       10.139982        8.895366         8.150114   
1       10.881258        9.404713        8.086088         7.254086   
2       11.297335        9.914130        8.742417         7.914444   
3       10.865271        9.511434        8.298739         7.412407   
4       10.877643       10.073779        8.636995         7.913766   

   lib_mfcc_11_avg  lib_mfcc_12_avg  lib_mfcc_13_avg  lib_mfcc_1_std  \
0         7.367686         6.810772         6.211969       80.213020   
1         6.448022         5.861232         5.357966      105.766289   
2         7.067588         6.395854         5.967819       28.670700   
3         6.718295         6.080798         5.607462       41.493301   
4         6.902275         6.574956         5.858723       47.930656   

   lib_mfcc_2_std  lib_mfcc_3_std  lib_mfcc_4_std  lib_mfcc_5_std  \
0        0.964405        0.915351        0.899567        0.918060   
1       19.532993        1.066367        0.911629        0.475148   
2        1.105085        0.961518        1.005593        0.891455   
3        0.539670        0.533153        0.578260        0.479409   
4        0.891346        1.438288        1.419913        0.598312   

   lib_mfcc_6_std  lib_mfcc_7_std  lib_mfcc_8_std  lib_mfcc_9_std  \
0        0.936695        0.952802        0.939777        0.936986   
1        0.472212        0.470265        0.211643        0.215753   
2        0.980889        0.943527        0.966510        0.908136   
3        0.545013        0.519312        0.465926        0.469057   
4        0.560690        0.867479        0.715572        1.146438   

   lib_mfcc_10_std  lib_mfcc_11_std  lib_mfcc_12_std  lib_mfcc_13_std  \
0         0.912120         0.908604         0.910060         0.925049   
1         0.384701         0.433127         0.414579         0.361710   
2         0.934234         0.942631         1.036578         0.945394   
3         0.469288         0.504040         0.476202         0.459609   
4         0.558412         0.738493         0.856107         0.679622   

   zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0  0.000111     0.173058             3.270264                0.034481   
1  0.000078     0.125596             3.240312                0.040663   
2  0.000045     0.464907             3.255116                0.031493   
3  0.000178     0.159426             3.140661                0.056633   
4  0.000089     0.214079             3.242801                0.035025   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.083165               0.013287            0.040835   
1              0.091113               0.011048            0.080317   
2   

In [8]:
classifier_par_dict = {
            "svm": np.array([0.001, 0.01, 0.5, 1.0, 5.0, 10.0, 20.0]),
            "svm_rbf": np.array([0.001, 0.01, 0.5, 1.0, 5.0, 10.0, 20.0]),
            "randomforest": np.array([10, 25, 50, 100, 200, 500]),
            "gradientboosting": np.array([10, 25, 50, 100, 200, 500]),
            "extratrees": np.array([10, 25, 50, 100, 200, 500]),
            "gaussiannb": []  # Naive Bayes does not require parameter tuning for this example
        }

### RQ5

In [9]:
rq5= feat_dataset.return_subset_given_research_question(5)

In [10]:
train_feat_dataset, _, test_feat_dataset= rq5.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

In [11]:
train_feat_dataset.features.head()

id_measurement  id_performance    datetime   plant  generation  \
0             250              44  2023-07-11   basil           1   
1             564              97  2023-08-28   salad           3   
2              58              10  2023-05-25   salad           1   
3             368              64  2023-07-31  tomato           2   
4             228              40  2023-07-03   salad           2   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             2              L2     -984.353882       72.062363   
1             0              A2     -818.986450       88.086792   
2             0              G2     -781.015686       87.241440   
3             1              O3     -797.384583       86.573006   
4             0              A2     -791.011230       78.968521   

   lib_mfcc_3_avg  lib_mfcc_4_avg  lib_mfcc_5_avg  lib_mfcc_6_avg  \
0       26.994862       22.293789       16.607067       13.501343   
1       25.406952       22.705082       15.743296       12.937368   
2       24.818596       22.490578       15.520187       12.595559   
3       30.114954       25.166069       18.358955       15.334175   
4       34.369801       24.734499       19.051226       15.849953   

   lib_mfcc_7_avg  lib_mfcc_8_avg  lib_mfcc_9_avg  lib_mfcc_10_avg  \
0       11.190329        9.766424        8.534622         7.925098   
1       10.149009        8.796450        7.501701         6.708362   
2        9.563180        8.139243        7.466263         7.822841   
3       12.573730       11.360179       10.115472         9.191726   
4       13.534989       11.764194       10.824710         9.875539   

   lib_mfcc_11_avg  lib_mfcc_12_avg  lib_mfcc_13_avg  lib_mfcc_1_std  \
0         7.268586         6.775272         6.310095       94.202049   
1         5.912003         5.656219         5.520934       33.756046   
2         8.022415         7.846031         6.958409       90.745903   
3         8.424232         7.844889         7.351725      114.184402   
4         9.051231         8.542490         8.072813      131.980698   

   lib_mfcc_2_std  lib_mfcc_3_std  lib_mfcc_4_std  lib_mfcc_5_std  \
0       28.033316        8.006542        5.193118        3.635555   
1        1.784163        1.335588        1.153985        1.043026   
2        4.476870        3.619431        3.056686        2.758509   
3       10.129804        5.190826        1.622984        1.238399   
4       12.726333        7.234793        2.105844        1.636038   

   lib_mfcc_6_std  lib_mfcc_7_std  lib_mfcc_8_std  lib_mfcc_9_std  \
0        2.393669        1.758913        1.213603        0.780233   
1        1.008179        0.955304        0.938447        1.022977   
2        2.606905        2.596127        2.714929        2.412201   
3        1.231493        1.259656        1.280356        1.394922   
4        1.647500        1.659786        1.598923        1.559331   

   lib_mfcc_10_std  lib_mfcc_11_std  lib_mfcc_12_std  lib_mfcc_13_std  \
0         0.764615         0.825168         0.919949         0.978499   
1         0.905879         0.701620         1.200501         1.798971   
2         1.983029         2.923973         2.873667         1.602103   
3         1.159196         1.180111         1.326008         1.264836   
4         1.563745         1.485044         1.491779         1.568525   

   zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0  0.000156     0.110040             3.275695                0.026890   
1  0.000180     0.091942             3.186005                0.055752   
2  0.000230     0.079721             3.179343                0.059919   
3  0.000100     0.263420             3.257697                0.040870   
4  0.000036     0.167064             3.294891                0.023311   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.044619               0.010462            0.130913   
1              0.137324               0.015816            0.046165  

In [12]:
test_feat_dataset.features.head()

id_measurement  id_performance    datetime   plant  generation  \
0             574              99  2023-09-01   basil           2   
1             140              25  2023-06-16   salad           2   
2             562              97  2023-08-28   salad           3   
3             159              28  2023-06-16  tomato           1   
4             469              81  2023-08-07   salad           3   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             8              A3     -845.898499       89.396019   
1             0              D2     -758.109985       87.538925   
2             6              A3     -846.114929       83.148682   
3             0              D3     -823.656982       90.881584   
4             2              D3     -863.238708       88.718987   

   lib_mfcc_3_avg  lib_mfcc_4_avg  lib_mfcc_5_avg  lib_mfcc_6_avg  \
0       26.602608       23.818747       16.730240       13.784444   
1       24.987276       22.342300       15.437116       12.680230   
2       30.481258       23.970394       18.093857       14.166443   
3       29.940357       25.302891       19.855745       15.725966   
4       26.031414       23.477215       16.613089       13.469542   

   lib_mfcc_7_avg  lib_mfcc_8_avg  lib_mfcc_9_avg  lib_mfcc_10_avg  \
0       10.908296        9.621327        8.488400         7.705795   
1        9.890129        8.636655        7.433048         6.669631   
2       12.131692       10.581286        9.344821         8.494385   
3       13.836607       11.821978       10.949828         9.948787   
4       10.892236        9.319530        8.217675         7.395226   

   lib_mfcc_11_avg  lib_mfcc_12_avg  lib_mfcc_13_avg  lib_mfcc_1_std  \
0         6.800262         6.284706         5.780249       68.879250   
1         5.817098         5.442785         5.347852       90.754463   
2         7.675378         7.219154         6.656241       60.986938   
3         9.288299         8.631245         8.123927      116.995422   
4         6.622736         5.977902         5.422625       11.914670   

   lib_mfcc_2_std  lib_mfcc_3_std  lib_mfcc_4_std  lib_mfcc_5_std  \
0        0.725962        0.637905        0.635416        0.638195   
1        2.736346        2.358171        2.231701        2.039582   
2       13.185537        4.563050        2.156363        1.076388   
3        1.277141        2.071290        1.136799        1.698365   
4        0.960347        1.016402        0.245247        0.519773   

   lib_mfcc_6_std  lib_mfcc_7_std  lib_mfcc_8_std  lib_mfcc_9_std  \
0        0.690607        0.754472        0.680362        0.635988   
1        1.950285        1.852568        1.789594        1.817933   
2        0.819837        0.888876        0.985783        0.906883   
3        1.027114        1.406372        1.124228        1.277441   
4        0.432678        0.490043        0.237372        0.321909   

   lib_mfcc_10_std  lib_mfcc_11_std  lib_mfcc_12_std  lib_mfcc_13_std  \
0         0.651745         0.655890         0.670030         0.683350   
1         1.884811         1.940225         1.673808         1.184727   
2         0.951015         0.824784         0.754877         0.864834   
3         1.200273         1.241871         1.211787         1.215586   
4         0.243016         0.248760         0.190538         0.211969   

   zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0  0.000191     0.272839             3.232645                0.044140   
1  0.000200     0.176442             3.166958                0.064692   
2  0.000015     0.116041             3.296461                0.021390   
3  0.000159     0.077311             3.130099                0.056789   
4  0.000367     0.105294             2.987837                0.081994   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.115910               0.013442            0.023178   
1              0.157924               0.017690            0.066575  

In [13]:
train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

Counts and Percentages:
Class 0: Count = 2561, Percentage = 38.16%
Class 2: Count = 2152, Percentage = 32.06%
Class 1: Count = 1999, Percentage = 29.78%
Counts and Percentages:
Class 0: Count = 631, Percentage = 37.60%
Class 1: Count = 541, Percentage = 32.24%
Class 2: Count = 506, Percentage = 30.15%
Running experiments for svm
F1 Score: 0.18218565035368847
Accuracy: 0.37604290822407627
Precision: 0.1253476360746921
Recall: 0.3333333333333333
[[631   0   0]
 [541   0   0]
 [506   0   0]]
F1 Score: 0.18218565035368847
Accuracy: 0.37604290822407627
Precision: 0.1253476360746921
Recall: 0.3333333333333333
[[631   0   0]
 [541   0   0]
 [506   0   0]]
F1 Score: 0.18825484609798337
Accuracy: 0.37604290822407627
Precision: 0.24444826007326007
Recall: 0.3339858308851625
[[626   0   5]
 [537   0   4]
 [501   0   5]]
F1 Score: 0.20765356971531604
Accuracy: 0.37604290822407627
Precision: 0.235560293769249
Recall: 0.33633482207174764
[[608   0  23]
 [517   0  24]
 [483   0  23]]
F1 Score: 0.2083

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.38620253250667363
Accuracy: 0.43504171632896305
Precision: 0.4588346463657163
Recall: 0.41217258676320495
[[492  63  76]
 [363 106  72]
 [326  48 132]]
F1 Score: 0.4044587252230168
Accuracy: 0.43861740166865315
Precision: 0.44751388040582957
Recall: 0.41941936882281655
[[455  80  96]
 [314 142  85]
 [293  74 139]]
F1 Score: 0.43495091458186336
Accuracy: 0.45232419547079855
Precision: 0.4559409365372417
Recall: 0.43926061665571897
[[406 102 123]
 [258 182 101]
 [247  88 171]]
F1 Score: 0.45200242344433184
Accuracy: 0.464839094159714
Precision: 0.4637536014503336
Recall: 0.45432494173141386
[[392 109 130]
 [236 196 109]
 [208 106 192]]
F1 Score: 0.44978346635472016
Accuracy: 0.4576877234803337
Precision: 0.4556175350674761
Recall: 0.4501748894133158
[[358 115 158]
 [206 212 123]
 [195 113 198]]
Running experiments for extratrees
F1 Score: 0.40327295160022386
Accuracy: 0.4165673420738975
Precision: 0.40929202717623575
Recall: 0.4062599004744061
[[356 129 146]
 [231 182 128]
 [

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

In [14]:
experiment.print_best_result(metric='accuracy') #0.717

Best accuracy result:
Model: randomforest, Parameter: 200, F1: 0.4607353480340027, Accuracy: 0.47497020262216927, Precision: 0.480749012632068, Recall: 0.4634732266085277


## No flat Waves

In [15]:
feat_dataset = FeaturesDataset.load(file_path=norm_letters_signal_dataset_path)
feat_dataset.prepare_dataset(drop_constant= True, drop_flatness_columns= True, drop_nan_columns= True)

No columns with NaN values found.


In [16]:
feat_dataset.features.shape

(8245, 181)

### RQ5

In [17]:
rq5= feat_dataset.return_subset_given_research_question(5)
train_feat_dataset, _, test_feat_dataset= rq5.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Counts and Percentages:
Class 0: Count = 2547, Percentage = 38.61%
Class 2: Count = 2086, Percentage = 31.63%
Class 1: Count = 1963, Percentage = 29.76%
Counts and Percentages:
Class 0: Count = 627, Percentage = 38.02%
Class 1: Count = 529, Percentage = 32.08%
Class 2: Count = 493, Percentage = 29.90%
Running experiments for svm
F1 Score: 0.1836555360281195
Accuracy: 0.3802304426925409
Precision: 0.12674348089751364
Recall: 0.3333333333333333
[[627   0   0]
 [529   0   0]
 [493   0   0]]
F1 Score: 0.1836555360281195
Accuracy: 0.3802304426925409
Precision: 0.12674348089751364
Recall: 0.3333333333333333
[[627   0   0]
 [529   0   0]
 [493   0   0]]
F1 Score: 0.19084813436289927
Accuracy: 0.3802304426925409
Precision: 0.28037427120556707
Recall: 0.3342003358017023
[[621   0   6]
 [528   0   1]
 [487   0   6]]
F1 Score: 0.18946285087872747
Accuracy: 0.3796240145542753
Precision: 0.26533971356818026
Recall: 0.3335242032797279
[[621   0   6]
 [528   0   1]
 [488   0   5]]
F1 Score: 0.1880724

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.3762671903587447
Accuracy: 0.4342025469981807
Precision: 0.4570903907416379
Recall: 0.40714798847389577
[[503  50  74]
 [375  93  61]
 [323  50 120]]
F1 Score: 0.40594111220615314
Accuracy: 0.4414796846573681
Precision: 0.4515515108661244
Recall: 0.4204095613284006
[[454  74  99]
 [312 135  82]
 [287  67 139]]
F1 Score: 0.43255310444655276
Accuracy: 0.45542753183747725
Precision: 0.4620004258629156
Recall: 0.438869224899618
[[424  79 124]
 [270 166  93]
 [253  79 161]]
F1 Score: 0.45412876661177554
Accuracy: 0.4675560946027896
Precision: 0.47203868004641986
Recall: 0.45534650370413937
[[394  98 135]
 [233 196 100]
 [230  82 181]]
F1 Score: 0.4672201880305989
Accuracy: 0.47786537295330506
Precision: 0.47557394418960514
Recall: 0.46779254392758185
[[382 109 136]
 [201 213 115]
 [199 101 193]]
Running experiments for extratrees
F1 Score: 0.42356541965534733
Accuracy: 0.44026682838083686
Precision: 0.43424847026560737
Recall: 0.4269370839611093
[[381 111 135]
 [234 193 102]
 [2

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

## FR_1K < 50%

In [18]:
feat_dataset = FeaturesDataset.load(file_path=norm_letters_signal_dataset_path)

indexes_to_drop= feat_dataset.features[feat_dataset.features['flatness_ratio_1000'] > 0.5].index.tolist()
feat_dataset.prepare_dataset(drop_constant= False, drop_flatness_columns= True, drop_nan_columns= True)
feat_dataset.drop_rows(indexes_to_drop)

Removing columns with NaN values: ['skewness', 'kurtosis']


In [19]:
feat_dataset.features.shape

(6757, 179)

### RQ 5

In [20]:
rq5= feat_dataset.return_subset_given_research_question(5)
train_feat_dataset, _, test_feat_dataset= rq5.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Counts and Percentages:
Class 0: Count = 2125, Percentage = 39.32%
Class 2: Count = 1642, Percentage = 30.38%
Class 1: Count = 1638, Percentage = 30.31%
Counts and Percentages:
Class 0: Count = 499, Percentage = 36.91%
Class 2: Count = 432, Percentage = 31.95%
Class 1: Count = 421, Percentage = 31.14%
Running experiments for svm
F1 Score: 0.1797226724293175
Accuracy: 0.3690828402366864
Precision: 0.1230276134122288
Recall: 0.3333333333333333
[[499   0   0]
 [421   0   0]
 [432   0   0]]
F1 Score: 0.1797226724293175
Accuracy: 0.3690828402366864
Precision: 0.1230276134122288
Recall: 0.3333333333333333
[[499   0   0]
 [421   0   0]
 [432   0   0]]
F1 Score: 0.18835074084635475
Accuracy: 0.3690828402366864
Precision: 0.22337337337337337
Recall: 0.33395494693089883
[[493   0   6]
 [413   0   8]
 [426   0   6]]
F1 Score: 0.18835074084635475
Accuracy: 0.3690828402366864
Precision: 0.22337337337337337
Recall: 0.33395494693089883
[[493   0   6]
 [413   0   8]
 [426   0   6]]
F1 Score: 0.1883507

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.38337817302732113
Accuracy: 0.4386094674556213
Precision: 0.47968267146349336
Recall: 0.41720167263355784
[[410  56  33]
 [284 105  32]
 [296  58  78]]
F1 Score: 0.42365144182294817
Accuracy: 0.45857988165680474
Precision: 0.4780097961110619
Recall: 0.44156364986505076
[[381  66  52]
 [242 131  48]
 [246  78 108]]
F1 Score: 0.431897619984952
Accuracy: 0.4526627218934911
Precision: 0.4622712665657451
Recall: 0.4401481182945934
[[338  88  73]
 [220 146  55]
 [212  92 128]]
F1 Score: 0.4578503334507795
Accuracy: 0.4681952662721893
Precision: 0.4751187070708139
Recall: 0.45967606013469714
[[310 102  87]
 [192 167  62]
 [183  93 156]]
F1 Score: 0.45652838178485466
Accuracy: 0.46597633136094674
Precision: 0.4662652203369529
Recall: 0.45859887497348883
[[300 106  93]
 [163 177  81]
 [182  97 153]]
Running experiments for extratrees
F1 Score: 0.3984389793634823
Accuracy: 0.41272189349112426
Precision: 0.40743123575769785
Recall: 0.4031749093918167
[[289 105 105]
 [202 127  92]
 [18

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

# Normalize

## All waves

In [21]:
feat_dataset = FeaturesDataset.load(file_path=norm_letters_signal_dataset_path)
feat_dataset.prepare_dataset(drop_constant= True, drop_flatness_columns= True, drop_nan_columns= True)

No columns with NaN values found.


### RQ5

In [22]:
rq5= feat_dataset.return_subset_given_research_question(5)
train_feat_dataset, _, test_feat_dataset= rq5.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

# Normalize features
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Variable features were properly normalized using 'zscore' method.
Applied z-score normalization.
Counts and Percentages:
Class 0: Count = 2547, Percentage = 38.61%
Class 2: Count = 2086, Percentage = 31.63%
Class 1: Count = 1963, Percentage = 29.76%
Counts and Percentages:
Class 0: Count = 627, Percentage = 38.02%
Class 1: Count = 529, Percentage = 32.08%
Class 2: Count = 493, Percentage = 29.90%
Running experiments for svm
F1 Score: 0.1836555360281195
Accuracy: 0.3802304426925409
Precision: 0.12674348089751364
Recall: 0.3333333333333333
[[627   0   0]
 [529   0   0]
 [493   0   0]]
F1 Score: 0.1836555360281195
Accuracy: 0.3802304426925409
Precision: 0.12674348089751364
Recall: 0.3333333333333333
[[627   0   0]
 [529   0   0]
 [493   0   0]]
F1 Score: 0.3597690054769111
Accuracy: 0.41540327471194666
Precision: 0.41724764834331896
Recall: 0.38872917216791447
[[480  52  95]
 [357 110  62]
 [321  77  95]]
F1 Score: 0.39855741207888645
Accuracy: 0.43541540327471195
Precision: 0.44372895165

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.37429825100217146
Accuracy: 0.4317768344451183
Precision: 0.45459134684158853
Recall: 0.40520551122848575
[[499  51  77]
 [375  89  65]
 [324  45 124]]
F1 Score: 0.41387566743424115
Accuracy: 0.4493632504548211
Precision: 0.4615266842551094
Recall: 0.4284243072441516
[[460  66 101]
 [311 133  85]
 [280  65 148]]
F1 Score: 0.4287440381558029
Accuracy: 0.45057610673135234
Precision: 0.45628385389028975
Recall: 0.4347542064126631
[[416  86 125]
 [260 163 106]
 [257  72 164]]
F1 Score: 0.4626200874823562
Accuracy: 0.47847180109157067
Precision: 0.4808561587944946
Recall: 0.46538247170055375
[[411  87 129]
 [229 189 111]
 [219  85 189]]
F1 Score: 0.46497440507331556
Accuracy: 0.47786537295330506
Precision: 0.4755376069774062
Recall: 0.4665186669831137
[[394  92 141]
 [200 203 126]
 [203  99 191]]
Running experiments for extratrees
F1 Score: 0.4279079007641764
Accuracy: 0.44026682838083686
Precision: 0.4344562836262306
Recall: 0.4296301169646702
[[363 134 130]
 [225 191 113]
 [20

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

## No flat

In [23]:
feat_dataset = FeaturesDataset.load(file_path=norm_letters_signal_dataset_path)
feat_dataset.prepare_dataset(drop_constant= True, drop_flatness_columns= True, drop_nan_columns= True)

rq2= feat_dataset.return_subset_given_research_question(2)
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

No columns with NaN values found.


### RQ5

In [24]:
rq5= feat_dataset.return_subset_given_research_question(5)
train_feat_dataset, _, test_feat_dataset= rq5.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

# Normalize features
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Variable features were properly normalized using 'zscore' method.
Applied z-score normalization.
Counts and Percentages:
Class 0: Count = 2547, Percentage = 38.61%
Class 2: Count = 2086, Percentage = 31.63%
Class 1: Count = 1963, Percentage = 29.76%
Counts and Percentages:
Class 0: Count = 627, Percentage = 38.02%
Class 1: Count = 529, Percentage = 32.08%
Class 2: Count = 493, Percentage = 29.90%
Running experiments for svm
F1 Score: 0.1836555360281195
Accuracy: 0.3802304426925409
Precision: 0.12674348089751364
Recall: 0.3333333333333333
[[627   0   0]
 [529   0   0]
 [493   0   0]]
F1 Score: 0.1836555360281195
Accuracy: 0.3802304426925409
Precision: 0.12674348089751364
Recall: 0.3333333333333333
[[627   0   0]
 [529   0   0]
 [493   0   0]]
F1 Score: 0.3597690054769111
Accuracy: 0.41540327471194666
Precision: 0.41724764834331896
Recall: 0.38872917216791447
[[480  52  95]
 [357 110  62]
 [321  77  95]]
F1 Score: 0.39855741207888645
Accuracy: 0.43541540327471195
Precision: 0.44372895165

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.373889380313529
Accuracy: 0.43117040630685266
Precision: 0.45384688566237946
Recall: 0.40467387911790625
[[498  51  78]
 [375  89  65]
 [324  45 124]]
F1 Score: 0.41471891637593195
Accuracy: 0.44996967859308673
Precision: 0.46259440777509825
Recall: 0.42905442696689894
[[460  66 101]
 [311 134  84]
 [280  65 148]]
F1 Score: 0.42889914797918766
Accuracy: 0.45118253486961796
Precision: 0.4567113318544616
Recall: 0.4351873509110747
[[418  86 123]
 [261 162 106]
 [257  72 164]]
F1 Score: 0.4590666237979382
Accuracy: 0.47543966040024255
Precision: 0.4774384652028962
Recall: 0.46204782188990917
[[411  86 130]
 [231 188 110]
 [221  87 185]]
F1 Score: 0.46801925594210186
Accuracy: 0.4808975136446331
Precision: 0.4785117148589743
Recall: 0.4694722903725146
[[396  92 139]
 [198 206 125]
 [203  99 191]]
Running experiments for extratrees
F1 Score: 0.38950010303553895
Accuracy: 0.406913280776228
Precision: 0.3978958990932863
Recall: 0.3937570346892943
[[359 134 134]
 [241 175 113]
 [23

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

## FR_1K < 50%

In [25]:
feat_dataset = FeaturesDataset.load(file_path=norm_letters_signal_dataset_path)

indexes_to_drop= feat_dataset.features[feat_dataset.features['flatness_ratio_1000'] > 0.5].index.tolist()
feat_dataset.prepare_dataset(drop_constant= False, drop_flatness_columns= True, drop_nan_columns= True)
feat_dataset.drop_rows(indexes_to_drop)

Removing columns with NaN values: ['skewness', 'kurtosis']


### RQ5

In [26]:
rq5= feat_dataset.return_subset_given_research_question(5)
train_feat_dataset, _, test_feat_dataset= rq5.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

# Normalize features
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Variable features were properly normalized using 'zscore' method.
Applied z-score normalization.
Counts and Percentages:
Class 0: Count = 2125, Percentage = 39.32%
Class 2: Count = 1642, Percentage = 30.38%
Class 1: Count = 1638, Percentage = 30.31%
Counts and Percentages:
Class 0: Count = 499, Percentage = 36.91%
Class 2: Count = 432, Percentage = 31.95%
Class 1: Count = 421, Percentage = 31.14%
Running experiments for svm
F1 Score: 0.1797226724293175
Accuracy: 0.3690828402366864
Precision: 0.1230276134122288
Recall: 0.3333333333333333
[[499   0   0]
 [421   0   0]
 [432   0   0]]
F1 Score: 0.1797226724293175
Accuracy: 0.3690828402366864
Precision: 0.1230276134122288
Recall: 0.3333333333333333
[[499   0   0]
 [421   0   0]
 [432   0   0]]
F1 Score: 0.35324938938020084
Accuracy: 0.4275147928994083
Precision: 0.4563829253537544
Recall: 0.40394980160020927
[[426  50  23]
 [293 104  24]
 [306  78  48]]
F1 Score: 0.38525846421421855
Accuracy: 0.4341715976331361
Precision: 0.454352210427907

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.3889759185909112
Accuracy: 0.4415680473372781
Precision: 0.4781108589885368
Recall: 0.4206392205836264
[[407  60  32]
 [280 107  34]
 [282  67  83]]
F1 Score: 0.43104338301895256
Accuracy: 0.46079881656804733
Precision: 0.4872280497280497
Recall: 0.4450757729352726
[[371  69  59]
 [246 139  36]
 [241  78 113]]
F1 Score: 0.43649773347526616
Accuracy: 0.45636094674556216
Precision: 0.4690798043374071
Recall: 0.4442911915441099
[[337  94  68]
 [212 155  54]
 [222  85 125]]
F1 Score: 0.4514794685990338
Accuracy: 0.46523668639053256
Precision: 0.46869563004293013
Recall: 0.4554931356217023
[[320  90  89]
 [187 164  70]
 [194  93 145]]
F1 Score: 0.44662935656996655
Accuracy: 0.4556213017751479
Precision: 0.4550436533540232
Recall: 0.4486885048358351
[[291 109  99]
 [169 175  77]
 [173 109 150]]
Running experiments for extratrees
F1 Score: 0.43597379477950016
Accuracy: 0.4467455621301775
Precision: 0.4492211409275857
Recall: 0.43918171964585456
[[293 125  81]
 [176 173  72]
 [186 

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>