# Experiment Eurythmy Letter

In [1]:
from PlantReactivityAnalysis.features.features_dataset import FeaturesDataset
from PlantReactivityAnalysis.models.experiment import Experiment
from PlantReactivityAnalysis.config import PROCESSED_DATA_DIR

In [2]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# No normalize

## All waves

In [3]:
norm_letters_signal_dataset_path= r"..\data\processed\feat_norm_letters_1_1_dataset.pkl"
feat_dataset = FeaturesDataset.load(file_path=norm_letters_signal_dataset_path)
feat_dataset.features.shape

(8390, 187)

In [4]:
feat_dataset.features.head()

id_measurement  id_performance    datetime  plant  generation  \
0               1               1  2023-04-29  salad           1   
1               1               1  2023-04-29  salad           1   
2               1               1  2023-04-29  salad           1   
3               1               1  2023-04-29  salad           1   
4               1               1  2023-04-29  salad           1   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             1              A1      -85.835655       90.291260   
1             1              G1      -96.628212       83.604851   
2             1              D1     -109.998672       89.973495   
3             1              A2      -83.306580       89.631935   
4             1              G2      -65.591743       89.487083   

   lib_mfcc_3_avg  lib_mfcc_4_avg  lib_mfcc_5_avg  lib_mfcc_6_avg  \
0       27.150677       24.450397       17.381523       14.476572   
1       26.647131       23.880787       17.142712       14.166664   
2       27.083378       24.341211       17.288652       14.374680   
3       26.564987       23.834097       16.861643       14.067777   
4       26.376032       23.637720       16.882397       13.740993   

   lib_mfcc_7_avg  lib_mfcc_8_avg  lib_mfcc_9_avg  lib_mfcc_10_avg  \
0       11.628652       10.253779        9.009523         8.263220   
1       11.311499        9.815317        8.509996         7.710995   
2       11.574939       10.197500        8.994436         8.182779   
3       11.136328        9.779285        8.568973         7.687598   
4       10.826669        9.959647        8.586371         7.815620   

   lib_mfcc_11_avg  lib_mfcc_12_avg  lib_mfcc_13_avg  lib_mfcc_1_std  \
0         7.481691         6.924080         6.325689       87.071404   
1         6.942698         6.384663         5.894090      107.289284   
2         7.339973         6.694422         6.222746       45.244011   
3         6.993852         6.350812         5.871837       39.551929   
4         6.835242         6.490175         5.785554       57.464516   

   lib_mfcc_2_std  lib_mfcc_3_std  lib_mfcc_4_std  lib_mfcc_5_std  \
0        0.980359        0.953386        0.947235        0.955398   
1       17.435492        0.894234        0.777028        1.745475   
2        0.859658        0.939066        0.948810        0.866550   
3        0.491159        0.504996        0.560510        0.462185   
4        0.788460        1.222857        1.200740        0.515309   

   lib_mfcc_6_std  lib_mfcc_7_std  lib_mfcc_8_std  lib_mfcc_9_std  \
0        0.965027        0.979433        0.972912        0.969672   
1        1.486925        1.322912        0.952002        0.781681   
2        0.917197        0.897436        0.912217        0.878173   
3        0.536993        0.503689        0.455105        0.462463   
4        0.505040        0.743336        0.627253        1.033373   

   lib_mfcc_10_std  lib_mfcc_11_std  lib_mfcc_12_std  lib_mfcc_13_std  \
0         0.946374         0.945209         0.952646         0.956299   
1         0.693320         0.757019         0.842326         0.944447   
2         0.894446         0.902890         0.967887         0.915868   
3         0.449083         0.490654         0.456090         0.447698   
4         0.488459         0.632174         0.794163         0.601958   

   zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0  0.000111     0.175157             3.270264                0.034481   
1  0.000078     0.127419             3.240312                0.040663   
2  0.000045     0.477437             3.255116                0.031493   
3  0.000178     0.162887             3.140661                0.056633   
4  0.000089     0.216644             3.242801                0.035025   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.083165               0.013287            0.040835   
1              0.091113               0.011048            0.080317   
2   

In [5]:
feat_dataset.prepare_dataset(drop_constant= False, drop_flatness_columns= True, drop_nan_columns= True)

Removing columns with NaN values: ['skewness', 'kurtosis']


In [6]:
feat_dataset.features.shape

(8390, 179)

In [7]:
feat_dataset.features.head()

id_measurement  id_performance    datetime  plant  generation  \
0               1               1  2023-04-29  salad           1   
1               1               1  2023-04-29  salad           1   
2               1               1  2023-04-29  salad           1   
3               1               1  2023-04-29  salad           1   
4               1               1  2023-04-29  salad           1   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             1              A1      -85.835655       90.291260   
1             1              G1      -96.628212       83.604851   
2             1              D1     -109.998672       89.973495   
3             1              A2      -83.306580       89.631935   
4             1              G2      -65.591743       89.487083   

   lib_mfcc_3_avg  lib_mfcc_4_avg  lib_mfcc_5_avg  lib_mfcc_6_avg  \
0       27.150677       24.450397       17.381523       14.476572   
1       26.647131       23.880787       17.142712       14.166664   
2       27.083378       24.341211       17.288652       14.374680   
3       26.564987       23.834097       16.861643       14.067777   
4       26.376032       23.637720       16.882397       13.740993   

   lib_mfcc_7_avg  lib_mfcc_8_avg  lib_mfcc_9_avg  lib_mfcc_10_avg  \
0       11.628652       10.253779        9.009523         8.263220   
1       11.311499        9.815317        8.509996         7.710995   
2       11.574939       10.197500        8.994436         8.182779   
3       11.136328        9.779285        8.568973         7.687598   
4       10.826669        9.959647        8.586371         7.815620   

   lib_mfcc_11_avg  lib_mfcc_12_avg  lib_mfcc_13_avg  lib_mfcc_1_std  \
0         7.481691         6.924080         6.325689       87.071404   
1         6.942698         6.384663         5.894090      107.289284   
2         7.339973         6.694422         6.222746       45.244011   
3         6.993852         6.350812         5.871837       39.551929   
4         6.835242         6.490175         5.785554       57.464516   

   lib_mfcc_2_std  lib_mfcc_3_std  lib_mfcc_4_std  lib_mfcc_5_std  \
0        0.980359        0.953386        0.947235        0.955398   
1       17.435492        0.894234        0.777028        1.745475   
2        0.859658        0.939066        0.948810        0.866550   
3        0.491159        0.504996        0.560510        0.462185   
4        0.788460        1.222857        1.200740        0.515309   

   lib_mfcc_6_std  lib_mfcc_7_std  lib_mfcc_8_std  lib_mfcc_9_std  \
0        0.965027        0.979433        0.972912        0.969672   
1        1.486925        1.322912        0.952002        0.781681   
2        0.917197        0.897436        0.912217        0.878173   
3        0.536993        0.503689        0.455105        0.462463   
4        0.505040        0.743336        0.627253        1.033373   

   lib_mfcc_10_std  lib_mfcc_11_std  lib_mfcc_12_std  lib_mfcc_13_std  \
0         0.946374         0.945209         0.952646         0.956299   
1         0.693320         0.757019         0.842326         0.944447   
2         0.894446         0.902890         0.967887         0.915868   
3         0.449083         0.490654         0.456090         0.447698   
4         0.488459         0.632174         0.794163         0.601958   

   zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0  0.000111     0.175157             3.270264                0.034481   
1  0.000078     0.127419             3.240312                0.040663   
2  0.000045     0.477437             3.255116                0.031493   
3  0.000178     0.162887             3.140661                0.056633   
4  0.000089     0.216644             3.242801                0.035025   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.083165               0.013287            0.040835   
1              0.091113               0.011048            0.080317   
2   

### RQ2

Is there any difference in the signals when someone is performing eurythmy?

In [8]:
rq2= feat_dataset.return_subset_given_research_question(2)

In [9]:
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

In [10]:
train_feat_dataset.features.head()

id_measurement  id_performance    datetime  plant  generation  \
0             475              82  2023-08-09  basil           2   
1             566              98  2023-09-01  basil           2   
2             263              46  2023-07-11  salad           2   
3             450              78  2023-08-07  basil           1   
4             391              68  2023-08-03  basil           1   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             1              A3     -241.534332       71.499710   
1             1              D2     -121.180412       87.309631   
2             6              G4     -257.515533       72.210571   
3             8              G1     -222.466095       78.123756   
4             7              A3     -117.614250       89.077873   

   lib_mfcc_3_avg  lib_mfcc_4_avg  lib_mfcc_5_avg  lib_mfcc_6_avg  \
0       22.971710       20.871870       15.459749       13.231969   
1       27.871500       23.998308       16.888828       14.064090   
2       25.452717       22.024702       15.987997       13.701541   
3       29.807997       21.045176       15.855097       13.064397   
4       26.299629       23.607006       16.852348       13.548154   

   lib_mfcc_7_avg  lib_mfcc_8_avg  lib_mfcc_9_avg  lib_mfcc_10_avg  \
0       11.058607       10.012943        9.066941         8.443850   
1       11.363098        9.931684        8.674533         7.891739   
2       11.598704       10.414721        9.350342         8.696244   
3        9.891227        8.934801        8.197018         7.639285   
4       11.151986        9.485555        8.497714         7.614470   

   lib_mfcc_11_avg  lib_mfcc_12_avg  lib_mfcc_13_avg  lib_mfcc_1_std  \
0         7.807832         7.355748         6.949651      116.802071   
1         7.099161         6.500525         5.964089       92.125183   
2         8.025736         7.513809         7.101633      151.220490   
3         7.172208         6.365016         6.294454       81.128128   
4         6.843027         6.187740         5.688671       62.859627   

   lib_mfcc_2_std  lib_mfcc_3_std  lib_mfcc_4_std  lib_mfcc_5_std  \
0       34.791168        8.252175        7.113840        4.190128   
1        7.665179        4.639249        0.969789        0.817408   
2       30.288269        8.796588        5.821466        2.974078   
3       11.067699        6.871985        1.869696        3.049192   
4        0.824726        1.335465        0.633882        0.691183   

   lib_mfcc_6_std  lib_mfcc_7_std  lib_mfcc_8_std  lib_mfcc_9_std  \
0        3.011310        1.915595        1.446046        1.097441   
1        1.015959        1.352540        1.143791        1.052579   
2        2.076678        1.691348        1.259993        1.125350   
3        2.516328        2.579436        1.585729        1.562310   
4        0.843855        0.586178        0.613265        0.521808   

   lib_mfcc_10_std  lib_mfcc_11_std  lib_mfcc_12_std  lib_mfcc_13_std  \
0         0.947429         0.906035         0.959707         1.050826   
1         1.105335         1.197472         1.150115         1.105809   
2         1.300509         1.561634         1.655808         1.733073   
3         1.815358         1.402265         1.205801         2.351165   
4         0.580774         0.518985         0.528686         0.519496   

   zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0  0.000058     0.255758             3.283720                0.023365   
1  0.000109     0.185609             3.235023                0.044142   
2  0.000060     0.066301             3.218017                0.035373   
3  0.000100     0.055785             3.270676                0.036323   
4  0.000060     0.094810             3.268370                0.036718   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.061528               0.006047            0.018502   
1              0.094278               0.013050            0.090713   
2   

In [11]:
test_feat_dataset.features.head()

id_measurement  id_performance    datetime   plant  generation  \
0             479              83  2023-08-09   basil           2   
1             416              72  2023-08-03  tomato           1   
2             280              49  2023-07-17   basil           1   
3             275              48  2023-07-17   basil           1   
4              67              12  2023-05-25  tomato           1   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             4              A3     -165.313751       62.968102   
1             1              D3     -135.430099       88.907127   
2             3              A2     -169.517624       90.885880   
3             1              D1      -68.599022       90.695312   
4             2              A2     -119.265846       89.402924   

   lib_mfcc_3_avg  lib_mfcc_4_avg  lib_mfcc_5_avg  lib_mfcc_6_avg  \
0        7.772108       12.757183       11.760372       11.115572   
1       26.253700       23.626081       16.549700       13.681617   
2       27.947918       25.182241       18.067324       15.205434   
3       27.869108       25.103455       18.003595       15.015872   
4       26.535301       23.774841       16.699919       13.842563   

   lib_mfcc_7_avg  lib_mfcc_8_avg  lib_mfcc_9_avg  lib_mfcc_10_avg  \
0        8.923944        8.256383        9.792509         8.838442   
1       11.078298       10.191878        9.206149         8.254006   
2       12.419406       11.041718        9.804159         9.019186   
3       12.184223       10.938834        9.763119         8.815355   
4       11.065558        9.747198        8.494120         7.649414   

   lib_mfcc_11_avg  lib_mfcc_12_avg  lib_mfcc_13_avg  lib_mfcc_1_std  \
0         7.353340         8.274459         8.163120       65.005646   
1         7.475065         7.225413         6.732573       71.540581   
2         8.198918         7.611704         7.092930      100.236877   
3         8.044098         7.579880         6.906889       89.739082   
4         6.817606         6.315367         5.846348       36.585495   

   lib_mfcc_2_std  lib_mfcc_3_std  lib_mfcc_4_std  lib_mfcc_5_std  \
0       15.613978        9.819160        6.532093        4.488976   
1        2.907115        2.464453        2.310158        2.328703   
2        0.867608        0.982271        0.991130        0.970741   
3        0.775316        0.891773        0.903364        0.906312   
4        0.494625        0.395191        0.435135        0.497314   

   lib_mfcc_6_std  lib_mfcc_7_std  lib_mfcc_8_std  lib_mfcc_9_std  \
0        2.336261        5.086741        3.727010        4.978024   
1        2.248374        1.781474        1.679332        2.126338   
2        0.966747        0.962001        0.962229        0.960038   
3        0.930273        0.906779        0.867684        0.927375   
4        0.486691        0.420445        0.405927        0.442699   

   lib_mfcc_10_std  lib_mfcc_11_std  lib_mfcc_12_std  lib_mfcc_13_std  \
0         4.999482         3.395570         3.014999         1.833031   
1         1.357065         1.180256         1.113901         1.147260   
2         0.963669         0.960249         0.948147         0.941905   
3         0.786054         0.834404         0.971521         0.873462   
4         0.617727         0.604384         0.447625         0.405815   

   zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0  0.000276     0.084528             3.171518                0.059066   
1  0.000146     0.071786             3.235263                0.050285   
2  0.000301     0.133625             3.208188                0.060640   
3  0.000219     0.200967             3.169509                0.062500   
4  0.000030     0.230771             3.289115                0.031695   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.142697               0.019192            0.076614   
1              0.127404               0.011976            0.045666  

In [12]:
train_feat_dataset.print_target_distribution()

Counts and Percentages:
Class 1: Count = 1002, Percentage = 33.57%
Class 0: Count = 998, Percentage = 33.43%
Class 2: Count = 985, Percentage = 33.00%


In [13]:
test_feat_dataset.print_target_distribution()

Counts and Percentages:
Class 0: Count = 257, Percentage = 34.40%
Class 2: Count = 249, Percentage = 33.33%
Class 1: Count = 241, Percentage = 32.26%


In [14]:
train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

In [15]:
experiment = Experiment(train_df, test_df, 'target')

In [16]:
classifier_par_dict = {
            "svm": np.array([0.001, 0.01, 0.5, 1.0, 5.0, 10.0, 20.0]),
            "svm_rbf": np.array([0.001, 0.01, 0.5, 1.0, 5.0, 10.0, 20.0]),
            "randomforest": np.array([10, 25, 50, 100, 200, 500]),
            "gradientboosting": np.array([10, 25, 50, 100, 200, 500]),
            "extratrees": np.array([10, 25, 50, 100, 200, 500]),
            "gaussiannb": []  # Naive Bayes does not require parameter tuning for this example
        }

experiment.run_all_models(classifier_par_dict)

Running experiments for svm
F1 Score: 0.16261808367071526
Accuracy: 0.32262382864792505
Precision: 0.10754127621597502
Recall: 0.3333333333333333
[[  0 257   0]
 [  0 241   0]
 [  0 249   0]]
F1 Score: 0.16261808367071526
Accuracy: 0.32262382864792505
Precision: 0.10754127621597502
Recall: 0.3333333333333333
[[  0 257   0]
 [  0 241   0]
 [  0 249   0]]
F1 Score: 0.30303191895571474
Accuracy: 0.34404283801874164
Precision: 0.340379347835785
Recall: 0.350427699571826
[[ 27 162  68]
 [ 22 169  50]
 [ 32 156  61]]
F1 Score: 0.30100897567041773
Accuracy: 0.3413654618473896
Precision: 0.3378577214146381
Recall: 0.3476559147342771
[[ 25 159  73]
 [ 20 165  56]
 [ 30 154  65]]
F1 Score: 0.3070782055133591
Accuracy: 0.3427041499330656
Precision: 0.34618167767573543
Recall: 0.34860019591959607
[[ 27 149  81]
 [ 18 158  65]
 [ 29 149  71]]
F1 Score: 0.3097713742809279
Accuracy: 0.3427041499330656
Precision: 0.34944684944684945
Recall: 0.3483835401343495
[[ 29 147  81]
 [ 19 155  67]
 [ 29 148  7

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.3829567631996018
Accuracy: 0.3828647925033467
Precision: 0.3829326335342016
Recall: 0.3830081345990925
[[100  69  88]
 [ 71  97  73]
 [ 82  78  89]]
F1 Score: 0.3867586434101781
Accuracy: 0.3868808567603748
Precision: 0.3868810630037541
Recall: 0.38805474034061344
[[ 87  71  99]
 [ 64 108  69]
 [ 76  79  94]]
F1 Score: 0.3683221529146827
Accuracy: 0.36813922356091033
Precision: 0.3684532728974082
Recall: 0.3687020444555453
[[91 75 91]
 [65 98 78]
 [83 80 86]]
F1 Score: 0.3602134735870122
Accuracy: 0.36010709504685406
Precision: 0.3609002597989382
Recall: 0.36092270984255087
[[86 78 93]
 [59 99 83]
 [82 83 84]]
F1 Score: 0.36619323064115133
Accuracy: 0.3668005354752343
Precision: 0.3675036062708154
Recall: 0.36804392873278263
[[ 80  82  95]
 [ 57 103  81]
 [ 75  83  91]]
Running experiments for extratrees
F1 Score: 0.3421780298206974
Accuracy: 0.3453815261044177
Precision: 0.34498617624013345
Recall: 0.34439438494083213
[[109  83  65]
 [ 99  80  62]
 [ 99  81  69]]
F1 Score:

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

In [17]:
experiment.print_best_result(metric='accuracy') # 0.388

Best accuracy result:
Model: gradientboosting, Parameter: 10, F1: 0.38806102047509455, Accuracy: 0.3895582329317269, Precision: 0.39276192015563477, Recall: 0.3884016403159933


### RQ1

In [18]:
rq1= feat_dataset.return_subset_given_research_question(1)
train_feat_dataset, _, test_feat_dataset= rq1.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

In [19]:
train_feat_dataset.features.head()

id_measurement  id_performance    datetime   plant  generation  \
0             250              44  2023-07-11   basil           1   
1             564              97  2023-08-28   salad           3   
2              58              10  2023-05-25   salad           1   
3             368              64  2023-07-31  tomato           2   
4             228              40  2023-07-03   salad           2   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             2              L2     -159.394821       80.605270   
1             0              A2      -45.417221       88.046646   
2             0              G2     -102.984222       86.444092   
3             1              O3     -273.353607       82.576019   
4             0              A2     -135.637573       89.396629   

   lib_mfcc_3_avg  lib_mfcc_4_avg  lib_mfcc_5_avg  lib_mfcc_6_avg  \
0       23.797482       21.366404       15.020288       12.391527   
1       25.370852       22.669716       15.704741       12.898817   
2       24.081972       21.745403       14.775640       11.830242   
3       31.416300       25.208084       19.517088       15.599072   
4       26.643229       23.738396       16.424765       13.581029   

   lib_mfcc_7_avg  lib_mfcc_8_avg  lib_mfcc_9_avg  lib_mfcc_10_avg  \
0        9.819618        8.569760        7.490523         6.826966   
1       10.109165        8.766016        7.472760         6.663585   
2        8.812757        7.386414        6.726233         7.059811   
3       13.369842       11.664322       10.593497         9.600644   
4       11.367213       10.171313        8.440859         7.795256   

   lib_mfcc_11_avg  lib_mfcc_12_avg  lib_mfcc_13_avg  lib_mfcc_1_std  \
0         6.106288         5.562629         5.082755      136.227310   
1         5.819554         5.529524         5.418949       32.366005   
2         7.256543         7.080164         6.233261       54.146996   
3         9.031762         8.364903         7.863293      128.279877   
4         7.395786         6.322886         6.158155       60.444069   

   lib_mfcc_2_std  lib_mfcc_3_std  lib_mfcc_4_std  lib_mfcc_5_std  \
0       25.450811        6.518581        5.710754        3.597976   
1        1.859235        1.420116        1.253378        1.137155   
2        4.387800        3.541636        2.952601        2.671344   
3       15.740682        4.922906        2.004647        2.042346   
4        1.529504        1.210761        1.389220        2.170035   

   lib_mfcc_6_std  lib_mfcc_7_std  lib_mfcc_8_std  lib_mfcc_9_std  \
0        2.724567        1.874393        1.462501        1.109392   
1        1.098843        1.048671        1.039079        1.121951   
2        2.528495        2.571850        2.686394        2.317439   
3        1.556377        1.505978        1.358285        1.325060   
4        2.238100        1.002697        1.113283        1.465561   

   lib_mfcc_10_std  lib_mfcc_11_std  lib_mfcc_12_std  lib_mfcc_13_std  \
0         0.902392         0.677852         0.508814         0.374747   
1         1.005242         0.914551         1.451110         1.907380   
2         1.854790         2.933653         2.892549         1.386477   
3         1.271371         1.428745         1.493774         1.418100   
4         1.128291         1.173021         1.449605         0.977775   

   zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0  0.000156     0.119290             3.275695                0.026890   
1  0.000180     0.092360             3.186005                0.055752   
2  0.000230     0.080060             3.179343                0.059919   
3  0.000100     0.265341             3.257697                0.040869   
4  0.000036     0.167643             3.294891                0.023311   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.044619               0.010462            0.130913   
1              0.137324               0.015816            0.046165  

In [20]:
test_feat_dataset.features.head()

id_measurement  id_performance    datetime   plant  generation  \
0             574              99  2023-09-01   basil           2   
1             140              25  2023-06-16   salad           2   
2             562              97  2023-08-28   salad           3   
3             159              28  2023-06-16  tomato           1   
4             469              81  2023-08-07   salad           3   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             8              A3     -138.135971       89.766869   
1             0              D2     -191.967468       86.557663   
2             6              A3     -131.836197       83.116798   
3             0              D3     -120.983902       90.114517   
4             2              D3      -30.391010       88.988785   

   lib_mfcc_3_avg  lib_mfcc_4_avg  lib_mfcc_5_avg  lib_mfcc_6_avg  \
0       26.925928       24.124680       17.045929       14.111732   
1       24.033018       21.384439       14.472772       11.690976   
2       30.546103       23.995512       18.149092       14.204644   
3       27.058664       24.336161       17.283802       14.411300   
4       26.234344       23.689363       16.834785       13.689631   

   lib_mfcc_7_avg  lib_mfcc_8_avg  lib_mfcc_9_avg  lib_mfcc_10_avg  \
0       11.235825        9.942743        8.804521         8.023866   
1        8.883643        7.651146        6.494347         5.723831   
2       12.163241       10.622729        9.383395         8.538942   
3       11.602880       10.217814        8.952750         8.183155   
4       11.111129        9.543944        8.445748         7.616190   

   lib_mfcc_11_avg  lib_mfcc_12_avg  lib_mfcc_13_avg  lib_mfcc_1_std  \
0         7.117317         6.599966         6.095604       59.956814   
1         4.838871         4.490690         4.412056       28.996401   
2         7.711967         7.256431         6.692817       62.142448   
3         7.402377         6.824203         6.271512       39.675385   
4         6.840416         6.195661         5.642431       13.645220   

   lib_mfcc_2_std  lib_mfcc_3_std  lib_mfcc_4_std  lib_mfcc_5_std  \
0        0.879334        0.983698        0.922968        0.950484   
1        2.644965        2.258401        2.125343        1.925849   
2       13.238531        4.563087        2.169713        1.105187   
3        0.598314        0.579735        0.561640        0.578725   
4        0.920068        1.012910        0.274386        0.558537   

   lib_mfcc_6_std  lib_mfcc_7_std  lib_mfcc_8_std  lib_mfcc_9_std  \
0        1.038553        1.128241        1.046984        0.905019   
1        1.811670        1.715320        1.653571        1.706542   
2        0.802572        0.887123        0.973621        0.911481   
3        0.577053        0.564246        0.563509        0.574670   
4        0.426849        0.526363        0.251560        0.360515   

   lib_mfcc_10_std  lib_mfcc_11_std  lib_mfcc_12_std  lib_mfcc_13_std  \
0         0.942915         0.980540         0.947255         0.887942   
1         1.754618         1.790794         1.553343         1.140959   
2         0.948832         0.817504         0.746482         0.858330   
3         0.593068         0.590984         0.574768         0.555889   
4         0.282781         0.297333         0.242358         0.268318   

   zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0  0.000191     0.275431             3.232645                0.044140   
1  0.000200     0.177767             3.166958                0.064692   
2  0.000015     0.116271             3.296461                0.021390   
3  0.000159     0.078348             3.130099                0.056789   
4  0.000367     0.108143             2.987837                0.081994   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.115910               0.013442            0.023178   
1              0.157924               0.017690            0.066575  

In [21]:
train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

Counts and Percentages:
Class 1: Count = 3395, Percentage = 50.58%
Class 0: Count = 3317, Percentage = 49.42%
Counts and Percentages:
Class 1: Count = 846, Percentage = 50.42%
Class 0: Count = 832, Percentage = 49.58%
Running experiments for svm
F1 Score: 0.33518225039619653
Accuracy: 0.5041716328963052
Precision: 0.2520858164481526
Recall: 0.5
[[  0 832]
 [  0 846]]
F1 Score: 0.3651153991676126
Accuracy: 0.5083432657926102
Precision: 0.53893712181005
Recall: 0.5044155755591926
[[ 28 804]
 [ 21 825]]
F1 Score: 0.41506283827171814
Accuracy: 0.5131108462455304
Precision: 0.5283577825530699
Recall: 0.5097304623567921
[[ 87 745]
 [ 72 774]]
F1 Score: 0.415372846733236
Accuracy: 0.5125148986889154
Precision: 0.526222352519626
Recall: 0.509149390798327
[[ 88 744]
 [ 74 772]]
F1 Score: 0.512342091129145
Accuracy: 0.5292014302741359
Precision: 0.5319006835860769
Recall: 0.5276868521549373
[[288 544]
 [246 600]]
F1 Score: 0.5072800063024157
Accuracy: 0.5113230035756854
Precision: 0.512564835553

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.6948608475648324
Accuracy: 0.698450536352801
Precision: 0.7065673938356978
Recall: 0.6975941648481543
[[495 337]
 [169 677]]
F1 Score: 0.69731166927683
Accuracy: 0.700238379022646
Precision: 0.7067862913262548
Recall: 0.6994666643935261
[[505 327]
 [176 670]]
F1 Score: 0.7050008897615833
Accuracy: 0.7073897497020262
Precision: 0.7129467128230274
Recall: 0.7066881478450627
[[518 314]
 [177 669]]
F1 Score: 0.7038242322380005
Accuracy: 0.7056019070321812
Precision: 0.7094928512526277
Recall: 0.7050046031096563
[[527 305]
 [189 657]]
F1 Score: 0.6969004213781966
Accuracy: 0.698450536352801
Precision: 0.7015446674537584
Recall: 0.6979024595380978
[[526 306]
 [200 646]]
Running experiments for extratrees
F1 Score: 0.6643669732332453
Accuracy: 0.6644815256257449
Precision: 0.6650089611474824
Recall: 0.6646819308056011
[[573 259]
 [304 542]]
F1 Score: 0.690015049821328
Accuracy: 0.6912991656734208
Precision: 0.6936026062388283
Recall: 0.6908102609565375
[[526 306]
 [212 634]]
F1 Sc

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

In [22]:
experiment.print_best_result(metric='accuracy') #0.717

Best accuracy result:
Model: gradientboosting, Parameter: 100, F1: 0.7050008897615833, Accuracy: 0.7073897497020262, Precision: 0.7129467128230274, Recall: 0.7066881478450627


## No flat Waves

In [23]:
feat_dataset = FeaturesDataset.load(file_path=norm_letters_signal_dataset_path)
feat_dataset.prepare_dataset(drop_constant= True, drop_flatness_columns= True, drop_nan_columns= True)

No columns with NaN values found.


In [24]:
feat_dataset.features.shape

(8245, 181)

### RQ2

In [25]:
rq2= feat_dataset.return_subset_given_research_question(2)
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Counts and Percentages:
Class 0: Count = 990, Percentage = 33.90%
Class 1: Count = 973, Percentage = 33.32%
Class 2: Count = 957, Percentage = 32.77%
Counts and Percentages:
Class 2: Count = 251, Percentage = 34.34%
Class 1: Count = 242, Percentage = 33.11%
Class 0: Count = 238, Percentage = 32.56%
Running experiments for svm
F1 Score: 0.16374269005847952
Accuracy: 0.32558139534883723
Precision: 0.10852713178294575
Recall: 0.3333333333333333
[[238   0   0]
 [242   0   0]
 [251   0   0]]
F1 Score: 0.16374269005847952
Accuracy: 0.32558139534883723
Precision: 0.10852713178294575
Recall: 0.3333333333333333
[[238   0   0]
 [242   0   0]
 [251   0   0]]
F1 Score: 0.2652155736267886
Accuracy: 0.3447332421340629
Precision: 0.22714731849347233
Recall: 0.3488205199435146
[[ 74 164   0]
 [ 64 178   0]
 [ 86 165   0]]
F1 Score: 0.26479054449789247
Accuracy: 0.3433652530779754
Precision: 0.22628265494750796
Recall: 0.34746625923096514
[[ 75 163   0]
 [ 66 176   0]
 [ 87 164   0]]
F1 Score: 0.264630

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.41072372304676574
Accuracy: 0.4131326949384405
Precision: 0.41544429132853566
Recall: 0.41474922588969076
[[124  52  62]
 [ 82  95  65]
 [105  63  83]]
F1 Score: 0.42606042394224736
Accuracy: 0.426812585499316
Precision: 0.42875779207959136
Recall: 0.4278411506184905
[[118  58  62]
 [ 76 100  66]
 [ 95  62  94]]
F1 Score: 0.3942906328028295
Accuracy: 0.39398084815321477
Precision: 0.39692534120959433
Recall: 0.39483116680210656
[[103  60  75]
 [ 77  99  66]
 [103  62  86]]
F1 Score: 0.4077748365871426
Accuracy: 0.4076607387140903
Precision: 0.4088167753031209
Recall: 0.4082333074812355
[[104  62  72]
 [ 74 100  68]
 [ 90  67  94]]
F1 Score: 0.4032539840747755
Accuracy: 0.40355677154582764
Precision: 0.40390772994547525
Recall: 0.40436808222350545
[[107  61  70]
 [ 75  98  69]
 [ 88  73  90]]
Running experiments for extratrees
F1 Score: 0.30792814013537334
Accuracy: 0.31053351573187415
Precision: 0.31000627201235104
Recall: 0.3118586606879425
[[ 95  75  68]
 [104  71  67]
 [

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

### RQ1

In [26]:
rq1= feat_dataset.return_subset_given_research_question(1)
train_feat_dataset, _, test_feat_dataset= rq1.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Counts and Percentages:
Class 1: Count = 3352, Percentage = 50.82%
Class 0: Count = 3244, Percentage = 49.18%
Counts and Percentages:
Class 0: Count = 864, Percentage = 52.40%
Class 1: Count = 785, Percentage = 47.60%
Running experiments for svm
F1 Score: 0.32251437962202134
Accuracy: 0.47604608853850816
Precision: 0.23802304426925408
Recall: 0.5
[[  0 864]
 [  0 785]]
F1 Score: 0.34229076039348566
Accuracy: 0.4808975136446331
Precision: 0.5604785405834142
Recall: 0.5040472399150743
[[ 18 846]
 [ 10 775]]
F1 Score: 0.3948523272084215
Accuracy: 0.49120679199514855
Precision: 0.5403426904094282
Recall: 0.5114974050483605
[[ 76 788]
 [ 51 734]]
F1 Score: 0.39517312206572774
Accuracy: 0.49060036385688294
Precision: 0.537101838253912
Recall: 0.5108022234017457
[[ 77 787]
 [ 53 732]]
F1 Score: 0.40407163507870225
Accuracy: 0.48696179502728926
Precision: 0.516159567275186
Recall: 0.5059905048360462
[[ 94 770]
 [ 76 709]]
F1 Score: 0.40737237869871695
Accuracy: 0.48635536688902364
Precision: 0

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.6994392563445518
Accuracy: 0.7010309278350515
Precision: 0.7136606760804449
Recall: 0.7061379452701109
[[518 346]
 [147 638]]
F1 Score: 0.7126447984783237
Accuracy: 0.7137659187386295
Precision: 0.7246153869481754
Recall: 0.7184072009907998
[[537 327]
 [145 640]]
F1 Score: 0.7149797764817527
Accuracy: 0.7155852031534263
Precision: 0.7233232302013624
Recall: 0.7194444444444444
[[552 312]
 [157 628]]
F1 Score: 0.7087164268743982
Accuracy: 0.7089144936325046
Precision: 0.7134484111299655
Recall: 0.7117974463316821
[[563 301]
 [179 606]]
F1 Score: 0.7124971309521708
Accuracy: 0.7125530624620983
Precision: 0.7156077728164476
Recall: 0.7148619957537155
[[576 288]
 [186 599]]
Running experiments for extratrees
F1 Score: 0.6635579513230767
Accuracy: 0.6652516676773802
Precision: 0.6644530820992767
Recall: 0.6633750589761735
[[607 257]
 [295 490]]
F1 Score: 0.7116374018190286
Accuracy: 0.7119466343238327
Precision: 0.7174595936565841
Recall: 0.7151568766218448
[[560 304]
 [171 614]]

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

## FR_1K < 50%

In [27]:
feat_dataset = FeaturesDataset.load(file_path=norm_letters_signal_dataset_path)

indexes_to_drop= feat_dataset.features[feat_dataset.features['flatness_ratio_1000'] > 0.5].index.tolist()
feat_dataset.prepare_dataset(drop_constant= False, drop_flatness_columns= True, drop_nan_columns= True)
feat_dataset.drop_rows(indexes_to_drop)

rq2= feat_dataset.return_subset_given_research_question(2)
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

Removing columns with NaN values: ['skewness', 'kurtosis']


In [28]:
feat_dataset.features.shape

(6757, 179)

### RQ 2

In [29]:
# Reduce the features that are correlated in the training data
train_cols, feat_stats= train_feat_dataset.reduce_features_based_on_target(corr_threshold=0.8)
test_feat_dataset.keep_only_specified_variable_columns(train_cols)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Reduced variable features from initial count to 57.
Counts and Percentages:
Class 2: Count = 721, Percentage = 33.40%
Class 0: Count = 720, Percentage = 33.35%
Class 1: Count = 718, Percentage = 33.26%
Counts and Percentages:
Class 0: Count = 188, Percentage = 34.81%
Class 1: Count = 184, Percentage = 34.07%
Class 2: Count = 168, Percentage = 31.11%
Running experiments for svm
F1 Score: 0.15819209039548024
Accuracy: 0.3111111111111111
Precision: 0.1037037037037037
Recall: 0.3333333333333333
[[  0   0 188]
 [  0   0 184]
 [  0   0 168]]
F1 Score: 0.15819209039548024
Accuracy: 0.3111111111111111
Precision: 0.1037037037037037
Recall: 0.3333333333333333
[[  0   0 188]
 [  0   0 184]
 [  0   0 168]]
F1 Score: 0.33025673238554354
Accuracy: 0.3685185185185185
Precision: 0.37051577535580815
Recall: 0.3691871136366973
[[ 21 106  61]
 [ 12 123  49]
 [ 20  93  55]]
F1 Score: 0.32562035534782136
Accuracy: 0.3611111111111111
Precision: 0.3634221541938918
Recall: 0.36211326960633156
[[ 21 104  63]
 

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.35853699604910366
Accuracy: 0.3592592592592593
Precision: 0.3657914546579026
Recall: 0.36230782784899346
[[54 43 91]
 [52 65 67]
 [48 45 75]]
F1 Score: 0.3350178876462436
Accuracy: 0.3351851851851852
Precision: 0.33777762651188886
Recall: 0.33716576362274786
[[55 54 79]
 [57 60 67]
 [55 47 66]]
F1 Score: 0.33155957202199976
Accuracy: 0.3314814814814815
Precision: 0.3330703440714442
Recall: 0.33315896509698545
[[56 55 77]
 [64 59 61]
 [56 48 64]]
F1 Score: 0.33973381946244013
Accuracy: 0.34074074074074073
Precision: 0.3399286515953183
Recall: 0.33991527539168614
[[62 57 69]
 [60 70 54]
 [54 62 52]]
F1 Score: 0.3561561822195542
Accuracy: 0.3574074074074074
Precision: 0.35619975277801985
Recall: 0.35690975434268674
[[62 66 60]
 [57 75 52]
 [54 58 56]]
Running experiments for extratrees
F1 Score: 0.34247043061632726
Accuracy: 0.34444444444444444
Precision: 0.3440223311546841
Recall: 0.3426739644362216
[[71 63 54]
 [77 66 41]
 [56 63 49]]
F1 Score: 0.3463229824271949
Accuracy: 0

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

### RQ 1

In [30]:
rq1= feat_dataset.return_subset_given_research_question(1)
train_feat_dataset, _, test_feat_dataset= rq1.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Counts and Percentages:
Class 0: Count = 2937, Percentage = 54.34%
Class 1: Count = 2468, Percentage = 45.66%
Counts and Percentages:
Class 0: Count = 767, Percentage = 56.73%
Class 1: Count = 585, Percentage = 43.27%
Running experiments for svm
F1 Score: 0.3619631901840491
Accuracy: 0.5673076923076923
Precision: 0.28365384615384615
Recall: 0.5
[[767   0]
 [585   0]]
F1 Score: 0.3619631901840491
Accuracy: 0.5673076923076923
Precision: 0.28365384615384615
Recall: 0.5
[[767   0]
 [585   0]]
F1 Score: 0.3619631901840491
Accuracy: 0.5673076923076923
Precision: 0.28365384615384615
Recall: 0.5
[[767   0]
 [585   0]]
F1 Score: 0.3619631901840491
Accuracy: 0.5673076923076923
Precision: 0.28365384615384615
Recall: 0.5
[[767   0]
 [585   0]]
F1 Score: 0.3619631901840491
Accuracy: 0.5673076923076923
Precision: 0.28365384615384615
Recall: 0.5
[[767   0]
 [585   0]]
F1 Score: 0.3619631901840491
Accuracy: 0.5673076923076923
Precision: 0.28365384615384615
Recall: 0.5
[[767   0]
 [585   0]]
F1 Score: 

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.7039103032643322
Accuracy: 0.7063609467455622
Precision: 0.7036310839737516
Recall: 0.7069245255685934
[[539 228]
 [169 416]]
F1 Score: 0.7123797430403076
Accuracy: 0.7144970414201184
Precision: 0.7122982090539958
Recall: 0.715920614225699
[[541 226]
 [160 425]]
F1 Score: 0.7067317961667425
Accuracy: 0.709319526627219
Precision: 0.7063202247191012
Recall: 0.7095320874981892
[[543 224]
 [169 416]]
F1 Score: 0.7161465412265988
Accuracy: 0.7189349112426036
Precision: 0.7155255566028823
Recall: 0.7186150948862813
[[553 214]
 [166 419]]
F1 Score: 0.7112210928923044
Accuracy: 0.7144970414201184
Precision: 0.710513973934698
Recall: 0.7130812690134724
[[555 212]
 [174 411]]
Running experiments for extratrees
F1 Score: 0.6264442881543253
Accuracy: 0.6420118343195266
Precision: 0.6335975550619632
Recall: 0.6258728089236564
[[572 195]
 [289 296]]
F1 Score: 0.6874601899573087
Accuracy: 0.6915680473372781
Precision: 0.6868706942236353
Recall: 0.6886136462407648
[[545 222]
 [195 390]]
F1

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

# Normalize

## All waves

In [31]:
feat_dataset = FeaturesDataset.load(file_path=norm_letters_signal_dataset_path)
feat_dataset.prepare_dataset(drop_constant= True, drop_flatness_columns= True, drop_nan_columns= True)

rq2= feat_dataset.return_subset_given_research_question(2)
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

No columns with NaN values found.


### RQ2

In [32]:
rq2= feat_dataset.return_subset_given_research_question(2)
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

# Normalize features
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Variable features were properly normalized using 'zscore' method.
Applied z-score normalization.
Counts and Percentages:
Class 0: Count = 990, Percentage = 33.90%
Class 1: Count = 973, Percentage = 33.32%
Class 2: Count = 957, Percentage = 32.77%
Counts and Percentages:
Class 2: Count = 251, Percentage = 34.34%
Class 1: Count = 242, Percentage = 33.11%
Class 0: Count = 238, Percentage = 32.56%
Running experiments for svm
F1 Score: 0.16374269005847952
Accuracy: 0.32558139534883723
Precision: 0.10852713178294575
Recall: 0.3333333333333333
[[238   0   0]
 [242   0   0]
 [251   0   0]]
F1 Score: 0.16374269005847952
Accuracy: 0.32558139534883723
Precision: 0.10852713178294575
Recall: 0.3333333333333333
[[238   0   0]
 [242   0   0]
 [251   0   0]]
F1 Score: 0.3408791336797805
Accuracy: 0.3447332421340629
Precision: 0.3485867413243627
Recall: 0.34601303561825114
[[ 85 104  49]
 [ 82 105  55]
 [ 87 102  62]]
F1 Score: 0.34582612935427176
Accuracy: 0.34610123119015046
Precision: 0.346604658471

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.42524794848167763
Accuracy: 0.42544459644322846
Precision: 0.43168282916003275
Recall: 0.42626618327025256
[[118  49  71]
 [ 81  95  66]
 [101  52  98]]
F1 Score: 0.41910545366907215
Accuracy: 0.41997264021887826
Precision: 0.42215117986174183
Recall: 0.42098033774110216
[[117  59  62]
 [ 79  97  66]
 [ 96  62  93]]
F1 Score: 0.39112757509782775
Accuracy: 0.3912448700410397
Precision: 0.3924201565675877
Recall: 0.39195750737817764
[[100  69  69]
 [ 77  99  66]
 [ 95  69  87]]
F1 Score: 0.3979427196622691
Accuracy: 0.39808481532147744
Precision: 0.39833058429549656
Recall: 0.39867015259562716
[[101  67  70]
 [ 76  99  67]
 [ 83  77  91]]
F1 Score: 0.39552950212342997
Accuracy: 0.3953488372093023
Precision: 0.39585033046159834
Recall: 0.3958690321474479
[[99 67 72]
 [67 99 76]
 [92 68 91]]
Running experiments for extratrees
F1 Score: 0.3397341839447103
Accuracy: 0.3392612859097127
Precision: 0.34357660594921113
Recall: 0.3396375375411104
[[ 86  77  75]
 [104  82  56]
 [ 97  7

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

### RQ1

In [33]:
rq1= feat_dataset.return_subset_given_research_question(1)
train_feat_dataset, _, test_feat_dataset= rq1.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

# Normalize features
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Variable features were properly normalized using 'zscore' method.
Applied z-score normalization.
Counts and Percentages:
Class 1: Count = 3352, Percentage = 50.82%
Class 0: Count = 3244, Percentage = 49.18%
Counts and Percentages:
Class 0: Count = 864, Percentage = 52.40%
Class 1: Count = 785, Percentage = 47.60%
Running experiments for svm
F1 Score: 0.32251437962202134
Accuracy: 0.47604608853850816
Precision: 0.23802304426925408
Recall: 0.5
[[  0 864]
 [  0 785]]
F1 Score: 0.6755436969904751
Accuracy: 0.679805942995755
Precision: 0.7019557416649139
Recall: 0.6868733781552253
[[466 398]
 [130 655]]
F1 Score: 0.6960807389972021
Accuracy: 0.6979987871437234
Precision: 0.712018809644553
Recall: 0.7034191436659589
[[510 354]
 [144 641]]
F1 Score: 0.6971820556717276
Accuracy: 0.6992116434202547
Precision: 0.7138607838607839
Recall: 0.704751267987733
[[509 355]
 [141 644]]
F1 Score: 0.7138267741137951
Accuracy: 0.7143723468768951
Precision: 0.7216655578331594
Recall: 0.7181123201226705
[[553

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.6988027627414442
Accuracy: 0.7004244996967859
Precision: 0.7131650969359673
Recall: 0.7055592415664071
[[517 347]
 [147 638]]
F1 Score: 0.7097084917055931
Accuracy: 0.7107337780473014
Precision: 0.7208712743647241
Recall: 0.7152224876150035
[[537 327]
 [150 635]]
F1 Score: 0.7084331597605934
Accuracy: 0.7089144936325046
Precision: 0.7156059169012863
Recall: 0.7124963139891485
[[551 313]
 [167 618]]
F1 Score: 0.7092745878846347
Accuracy: 0.7095209217707702
Precision: 0.7144785938727416
Recall: 0.7125508669497523
[[561 303]
 [176 609]]
F1 Score: 0.7137481280102626
Accuracy: 0.7137659187386295
Precision: 0.7161676345998192
Recall: 0.7157864472753008
[[582 282]
 [190 595]]
Running experiments for extratrees
F1 Score: 0.6742652909390652
Accuracy: 0.6755609460278957
Precision: 0.6747565271446332
Recall: 0.6740866065109696
[[609 255]
 [280 505]]
F1 Score: 0.7159198998748435
Accuracy: 0.7161916312916919
Precision: 0.7214894060541088
Recall: 0.7193242804906819
[[565 299]
 [169 616]]

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

## No flat

In [34]:
feat_dataset = FeaturesDataset.load(file_path=norm_letters_signal_dataset_path)
feat_dataset.prepare_dataset(drop_constant= True, drop_flatness_columns= True, drop_nan_columns= True)

rq2= feat_dataset.return_subset_given_research_question(2)
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

No columns with NaN values found.


### RQ2

In [35]:
rq2= feat_dataset.return_subset_given_research_question(2)
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

# Normalize features
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Variable features were properly normalized using 'zscore' method.
Applied z-score normalization.
Counts and Percentages:
Class 0: Count = 990, Percentage = 33.90%
Class 1: Count = 973, Percentage = 33.32%
Class 2: Count = 957, Percentage = 32.77%
Counts and Percentages:
Class 2: Count = 251, Percentage = 34.34%
Class 1: Count = 242, Percentage = 33.11%
Class 0: Count = 238, Percentage = 32.56%
Running experiments for svm
F1 Score: 0.16374269005847952
Accuracy: 0.32558139534883723
Precision: 0.10852713178294575
Recall: 0.3333333333333333
[[238   0   0]
 [242   0   0]
 [251   0   0]]
F1 Score: 0.16374269005847952
Accuracy: 0.32558139534883723
Precision: 0.10852713178294575
Recall: 0.3333333333333333
[[238   0   0]
 [242   0   0]
 [251   0   0]]
F1 Score: 0.3408791336797805
Accuracy: 0.3447332421340629
Precision: 0.3485867413243627
Recall: 0.34601303561825114
[[ 85 104  49]
 [ 82 105  55]
 [ 87 102  62]]
F1 Score: 0.34582612935427176
Accuracy: 0.34610123119015046
Precision: 0.346604658471

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.42649070241218245
Accuracy: 0.426812585499316
Precision: 0.43294871118791384
Recall: 0.4276667434943422
[[119  49  70]
 [ 81  95  66]
 [101  52  98]]
F1 Score: 0.42190977572333505
Accuracy: 0.42270861833105333
Precision: 0.4247473959441505
Recall: 0.42368576945776165
[[117  60  61]
 [ 78  98  66]
 [ 95  62  94]]
F1 Score: 0.39379598054839066
Accuracy: 0.39398084815321477
Precision: 0.3949178953520174
Recall: 0.3947354780705868
[[101  69  68]
 [ 75 100  67]
 [ 95  69  87]]
F1 Score: 0.39938274573357796
Accuracy: 0.399452804377565
Precision: 0.39970264397141864
Recall: 0.4000244133081767
[[100  65  73]
 [ 75 101  66]
 [ 84  76  91]]
F1 Score: 0.3942383462386934
Accuracy: 0.39398084815321477
Precision: 0.3945058109174042
Recall: 0.39444532216758815
[[ 97  67  74]
 [ 66 100  76]
 [ 92  68  91]]
Running experiments for extratrees
F1 Score: 0.3286619129493034
Accuracy: 0.33105335157318744
Precision: 0.33005155034303013
Recall: 0.3325861772716067
[[100  69  69]
 [ 85  80  77]
 [11

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

### RQ1

In [36]:
rq1= feat_dataset.return_subset_given_research_question(1)
train_feat_dataset, _, test_feat_dataset= rq1.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

# Normalize features
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Variable features were properly normalized using 'zscore' method.
Applied z-score normalization.
Counts and Percentages:
Class 1: Count = 3352, Percentage = 50.82%
Class 0: Count = 3244, Percentage = 49.18%
Counts and Percentages:
Class 0: Count = 864, Percentage = 52.40%
Class 1: Count = 785, Percentage = 47.60%
Running experiments for svm
F1 Score: 0.32251437962202134
Accuracy: 0.47604608853850816
Precision: 0.23802304426925408
Recall: 0.5
[[  0 864]
 [  0 785]]
F1 Score: 0.6755436969904751
Accuracy: 0.679805942995755
Precision: 0.7019557416649139
Recall: 0.6868733781552253
[[466 398]
 [130 655]]
F1 Score: 0.6960807389972021
Accuracy: 0.6979987871437234
Precision: 0.712018809644553
Recall: 0.7034191436659589
[[510 354]
 [144 641]]
F1 Score: 0.6971820556717276
Accuracy: 0.6992116434202547
Precision: 0.7138607838607839
Recall: 0.704751267987733
[[509 355]
 [141 644]]
F1 Score: 0.7138267741137951
Accuracy: 0.7143723468768951
Precision: 0.7216655578331594
Recall: 0.7181123201226705
[[553

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.6988027627414442
Accuracy: 0.7004244996967859
Precision: 0.7131650969359673
Recall: 0.7055592415664071
[[517 347]
 [147 638]]
F1 Score: 0.7097084917055931
Accuracy: 0.7107337780473014
Precision: 0.7208712743647241
Recall: 0.7152224876150035
[[537 327]
 [150 635]]
F1 Score: 0.7078400424333617
Accuracy: 0.708308065494239
Precision: 0.7148915010393766
Recall: 0.7118593713139891
[[551 313]
 [168 617]]
F1 Score: 0.7080607030741319
Accuracy: 0.708308065494239
Precision: 0.7132519222071461
Recall: 0.7113352205708894
[[560 304]
 [177 608]]
F1 Score: 0.7131388136469039
Accuracy: 0.7131594906003639
Precision: 0.7156216669768871
Recall: 0.7152077435715971
[[581 283]
 [190 595]]
Running experiments for extratrees
F1 Score: 0.6767467293962279
Accuracy: 0.6773802304426926
Precision: 0.6766986700615019
Recall: 0.6768127801368247
[[595 269]
 [263 522]]
F1 Score: 0.7010832080643734
Accuracy: 0.7016373559733171
Precision: 0.708594346829641
Recall: 0.7053189136588818
[[543 321]
 [171 614]]
F1

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

## FR_1K < 50%

In [37]:
feat_dataset = FeaturesDataset.load(file_path=norm_letters_signal_dataset_path)

indexes_to_drop= feat_dataset.features[feat_dataset.features['flatness_ratio_1000'] > 0.5].index.tolist()
feat_dataset.prepare_dataset(drop_constant= False, drop_flatness_columns= True, drop_nan_columns= True)
feat_dataset.drop_rows(indexes_to_drop)

rq2= feat_dataset.return_subset_given_research_question(2)
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

Removing columns with NaN values: ['skewness', 'kurtosis']


### RQ2

In [38]:
rq2= feat_dataset.return_subset_given_research_question(2)
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

# Normalize features
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Variable features were properly normalized using 'zscore' method.
Applied z-score normalization.
Counts and Percentages:
Class 2: Count = 721, Percentage = 33.40%
Class 0: Count = 720, Percentage = 33.35%
Class 1: Count = 718, Percentage = 33.26%
Counts and Percentages:
Class 0: Count = 188, Percentage = 34.81%
Class 1: Count = 184, Percentage = 34.07%
Class 2: Count = 168, Percentage = 31.11%
Running experiments for svm
F1 Score: 0.15819209039548024
Accuracy: 0.3111111111111111
Precision: 0.1037037037037037
Recall: 0.3333333333333333
[[  0   0 188]
 [  0   0 184]
 [  0   0 168]]
F1 Score: 0.15819209039548024
Accuracy: 0.3111111111111111
Precision: 0.1037037037037037
Recall: 0.3333333333333333
[[  0   0 188]
 [  0   0 184]
 [  0   0 168]]
F1 Score: 0.3213996581292727
Accuracy: 0.32407407407407407
Precision: 0.32408729108173157
Recall: 0.3254739145118423
[[45 72 71]
 [50 71 63]
 [42 67 59]]
F1 Score: 0.3352339588563448
Accuracy: 0.3351851851851852
Precision: 0.33596453433797163
Recall: 

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.3676250862080428
Accuracy: 0.37037037037037035
Precision: 0.37397721054653227
Recall: 0.37442366709249225
[[53 51 84]
 [49 65 70]
 [40 46 82]]
F1 Score: 0.3744988221215428
Accuracy: 0.37592592592592594
Precision: 0.37638657902378503
Recall: 0.378228565555115
[[55 59 74]
 [49 75 60]
 [46 49 73]]
F1 Score: 0.37502875920165485
Accuracy: 0.37592592592592594
Precision: 0.3778624933119315
Recall: 0.37797894365886964
[[57 51 80]
 [52 74 58]
 [43 53 72]]
F1 Score: 0.3773057814324303
Accuracy: 0.37777777777777777
Precision: 0.3781062106896456
Recall: 0.3792912940692774
[[61 57 70]
 [58 73 53]
 [41 57 70]]
F1 Score: 0.34230456111933655
Accuracy: 0.3425925925925926
Precision: 0.34292882810079917
Recall: 0.34305023273570906
[[59 60 69]
 [59 67 58]
 [49 60 59]]
Running experiments for extratrees
F1 Score: 0.3391230261647218
Accuracy: 0.34074074074074073
Precision: 0.34057423978964335
Recall: 0.3391847642541445
[[72 63 53]
 [79 62 43]
 [53 65 50]]
F1 Score: 0.3374258665709697
Accuracy: 0

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

### RQ1

In [39]:
rq1= feat_dataset.return_subset_given_research_question(1)
train_feat_dataset, _, test_feat_dataset= rq1.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

# Normalize features
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

Variable features were properly normalized using 'zscore' method.
Applied z-score normalization.
Counts and Percentages:
Class 0: Count = 2937, Percentage = 54.34%
Class 1: Count = 2468, Percentage = 45.66%
Counts and Percentages:
Class 0: Count = 767, Percentage = 56.73%
Class 1: Count = 585, Percentage = 43.27%
Running experiments for svm
F1 Score: 0.3619631901840491
Accuracy: 0.5673076923076923
Precision: 0.28365384615384615
Recall: 0.5
[[767   0]
 [585   0]]
F1 Score: 0.6690054875966991
Accuracy: 0.6738165680473372
Precision: 0.6685598682579594
Recall: 0.6697233087063595
[[537 230]
 [211 374]]
F1 Score: 0.6999735029146794
Accuracy: 0.7026627218934911
Precision: 0.6995766087878368
Recall: 0.702651021295089
[[539 228]
 [174 411]]
F1 Score: 0.7096162361135894
Accuracy: 0.7115384615384616
Precision: 0.7098124240333761
Recall: 0.713515862668405
[[536 231]
 [159 426]]
F1 Score: 0.7039258885674089
Accuracy: 0.7071005917159763
Precision: 0.7032898861573997
Recall: 0.7059539330725771
[[548 

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.7068133548973421
Accuracy: 0.709319526627219
Precision: 0.7064564959852573
Recall: 0.7097348978704912
[[542 225]
 [168 417]]
F1 Score: 0.7082242552193292
Accuracy: 0.7107988165680473
Precision: 0.7078037219101123
Recall: 0.711038678835289
[[544 223]
 [168 417]]
F1 Score: 0.7117493703327294
Accuracy: 0.7144970414201184
Precision: 0.7111916449774323
Recall: 0.7142981312472838
[[549 218]
 [168 417]]
F1 Score: 0.7063921281066974
Accuracy: 0.709319526627219
Precision: 0.7058104781997188
Recall: 0.7087208460089816
[[547 220]
 [173 412]]
F1 Score: 0.7076187636993556
Accuracy: 0.7107988165680473
Precision: 0.7069526223606967
Recall: 0.7096190062291756
[[551 216]
 [175 410]]
Running experiments for extratrees
F1 Score: 0.658116938281595
Accuracy: 0.6708579881656804
Precision: 0.6643236247769088
Recall: 0.656772417789367
[[584 183]
 [262 323]]
F1 Score: 0.6940463908948717
Accuracy: 0.6982248520710059
Precision: 0.6934541765840787
Recall: 0.6950890916992611
[[551 216]
 [192 393]]
F1 S

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>