# Experiment Eurythmy Letter

In [6]:
from PlantReactivityAnalysis.features.features_dataset import FeaturesDataset
from PlantReactivityAnalysis.models.experiment import Experiment
from PlantReactivityAnalysis.config import PROCESSED_DATA_DIR

In [7]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [8]:
classifier_par_dict = {
            "svm": np.array([0.001, 0.01, 0.5, 1.0, 5.0, 10.0, 20.0]),
            "svm_rbf": np.array([0.001, 0.01, 0.5, 1.0, 5.0, 10.0, 20.0]),
            "randomforest": np.array([10, 25, 50, 100, 200, 500]),
            "gradientboosting": np.array([10, 25, 50, 100, 200, 500]),
            "extratrees": np.array([10, 25, 50, 100, 200, 500]),
            "gaussiannb": []  # Naive Bayes does not require parameter tuning for this example
        }

# Preparation

In [9]:
norm_letters_signal_dataset_path= r"..\data\processed\feat_norm_letters_1_1_dataset.pkl"
feat_dataset = FeaturesDataset.load(file_path=norm_letters_signal_dataset_path)

In [10]:
feat_dataset.features.shape

(8390, 187)

In [11]:
feat_dataset.features.head()

id_measurement  id_performance    datetime  plant  generation  \
0               1               1  2023-04-29  salad           1   
1               1               1  2023-04-29  salad           1   
2               1               1  2023-04-29  salad           1   
3               1               1  2023-04-29  salad           1   
4               1               1  2023-04-29  salad           1   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             1              A1      -85.835655       90.291260   
1             1              G1      -96.628212       83.604851   
2             1              D1     -109.998672       89.973495   
3             1              A2      -83.306580       89.631935   
4             1              G2      -65.591743       89.487083   

   lib_mfcc_3_avg  lib_mfcc_4_avg  lib_mfcc_5_avg  lib_mfcc_6_avg  \
0       27.150677       24.450397       17.381523       14.476572   
1       26.647131       23.880787       17.142712       14.166664   
2       27.083378       24.341211       17.288652       14.374680   
3       26.564987       23.834097       16.861643       14.067777   
4       26.376032       23.637720       16.882397       13.740993   

   lib_mfcc_7_avg  lib_mfcc_8_avg  lib_mfcc_9_avg  lib_mfcc_10_avg  \
0       11.628652       10.253779        9.009523         8.263220   
1       11.311499        9.815317        8.509996         7.710995   
2       11.574939       10.197500        8.994436         8.182779   
3       11.136328        9.779285        8.568973         7.687598   
4       10.826669        9.959647        8.586371         7.815620   

   lib_mfcc_11_avg  lib_mfcc_12_avg  lib_mfcc_13_avg  lib_mfcc_1_std  \
0         7.481691         6.924080         6.325689       87.071404   
1         6.942698         6.384663         5.894090      107.289284   
2         7.339973         6.694422         6.222746       45.244011   
3         6.993852         6.350812         5.871837       39.551929   
4         6.835242         6.490175         5.785554       57.464516   

   lib_mfcc_2_std  lib_mfcc_3_std  lib_mfcc_4_std  lib_mfcc_5_std  \
0        0.980359        0.953386        0.947235        0.955398   
1       17.435492        0.894234        0.777028        1.745475   
2        0.859658        0.939066        0.948810        0.866550   
3        0.491159        0.504996        0.560510        0.462185   
4        0.788460        1.222857        1.200740        0.515309   

   lib_mfcc_6_std  lib_mfcc_7_std  lib_mfcc_8_std  lib_mfcc_9_std  \
0        0.965027        0.979433        0.972912        0.969672   
1        1.486925        1.322912        0.952002        0.781681   
2        0.917197        0.897436        0.912217        0.878173   
3        0.536993        0.503689        0.455105        0.462463   
4        0.505040        0.743336        0.627253        1.033373   

   lib_mfcc_10_std  lib_mfcc_11_std  lib_mfcc_12_std  lib_mfcc_13_std  \
0         0.946374         0.945209         0.952646         0.956299   
1         0.693320         0.757019         0.842326         0.944447   
2         0.894446         0.902890         0.967887         0.915868   
3         0.449083         0.490654         0.456090         0.447698   
4         0.488459         0.632174         0.794163         0.601958   

   zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0  0.000111     0.175157             3.270264                0.034481   
1  0.000078     0.127419             3.240312                0.040663   
2  0.000045     0.477437             3.255116                0.031493   
3  0.000178     0.162887             3.140661                0.056633   
4  0.000089     0.216644             3.242801                0.035025   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.083165               0.013287            0.040835   
1              0.091113               0.011048            0.080317   
2   

In [12]:
feat_dataset.prepare_dataset(drop_constant= True, drop_flatness_columns= True, drop_nan_columns= True)

No columns with NaN values found.


In [13]:
feat_dataset.features.shape

(8362, 181)

In [14]:
feat_dataset.features.head()

id_measurement  id_performance    datetime  plant  generation  \
0               1               1  2023-04-29  salad           1   
1               1               1  2023-04-29  salad           1   
2               1               1  2023-04-29  salad           1   
3               1               1  2023-04-29  salad           1   
4               1               1  2023-04-29  salad           1   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             1              A1      -85.835655       90.291260   
1             1              G1      -96.628212       83.604851   
2             1              D1     -109.998672       89.973495   
3             1              A2      -83.306580       89.631935   
4             1              G2      -65.591743       89.487083   

   lib_mfcc_3_avg  lib_mfcc_4_avg  lib_mfcc_5_avg  lib_mfcc_6_avg  \
0       27.150677       24.450397       17.381523       14.476572   
1       26.647131       23.880787       17.142712       14.166664   
2       27.083378       24.341211       17.288652       14.374680   
3       26.564987       23.834097       16.861643       14.067777   
4       26.376032       23.637720       16.882397       13.740993   

   lib_mfcc_7_avg  lib_mfcc_8_avg  lib_mfcc_9_avg  lib_mfcc_10_avg  \
0       11.628652       10.253779        9.009523         8.263220   
1       11.311499        9.815317        8.509996         7.710995   
2       11.574939       10.197500        8.994436         8.182779   
3       11.136328        9.779285        8.568973         7.687598   
4       10.826669        9.959647        8.586371         7.815620   

   lib_mfcc_11_avg  lib_mfcc_12_avg  lib_mfcc_13_avg  lib_mfcc_1_std  \
0         7.481691         6.924080         6.325689       87.071404   
1         6.942698         6.384663         5.894090      107.289284   
2         7.339973         6.694422         6.222746       45.244011   
3         6.993852         6.350812         5.871837       39.551929   
4         6.835242         6.490175         5.785554       57.464516   

   lib_mfcc_2_std  lib_mfcc_3_std  lib_mfcc_4_std  lib_mfcc_5_std  \
0        0.980359        0.953386        0.947235        0.955398   
1       17.435492        0.894234        0.777028        1.745475   
2        0.859658        0.939066        0.948810        0.866550   
3        0.491159        0.504996        0.560510        0.462185   
4        0.788460        1.222857        1.200740        0.515309   

   lib_mfcc_6_std  lib_mfcc_7_std  lib_mfcc_8_std  lib_mfcc_9_std  \
0        0.965027        0.979433        0.972912        0.969672   
1        1.486925        1.322912        0.952002        0.781681   
2        0.917197        0.897436        0.912217        0.878173   
3        0.536993        0.503689        0.455105        0.462463   
4        0.505040        0.743336        0.627253        1.033373   

   lib_mfcc_10_std  lib_mfcc_11_std  lib_mfcc_12_std  lib_mfcc_13_std  \
0         0.946374         0.945209         0.952646         0.956299   
1         0.693320         0.757019         0.842326         0.944447   
2         0.894446         0.902890         0.967887         0.915868   
3         0.449083         0.490654         0.456090         0.447698   
4         0.488459         0.632174         0.794163         0.601958   

   zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0  0.000111     0.175157             3.270264                0.034481   
1  0.000078     0.127419             3.240312                0.040663   
2  0.000045     0.477437             3.255116                0.031493   
3  0.000178     0.162887             3.140661                0.056633   
4  0.000089     0.216644             3.242801                0.035025   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.083165               0.013287            0.040835   
1              0.091113               0.011048            0.080317   
2   

# RQ1

In [15]:
rq1= feat_dataset.return_subset_given_research_question(1)
train_feat_dataset, _, test_feat_dataset= rq1.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

Counts and Percentages:
Class 1: Count = 3394, Percentage = 50.74%
Class 0: Count = 3295, Percentage = 49.26%
Counts and Percentages:
Class 0: Count = 852, Percentage = 50.93%
Class 1: Count = 821, Percentage = 49.07%


In [16]:
experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

Running experiments for svm
F1 Score: 0.32919005613472335
Accuracy: 0.4907352062163778
Precision: 0.2453676031081889
Recall: 0.5
[[  0 852]
 [  0 821]]
F1 Score: 0.3540247115471972
Accuracy: 0.4919306634787806
Precision: 0.5059551282051282
Recall: 0.5006640533415678
[[ 25 827]
 [ 23 798]]
F1 Score: 0.3946324818647506
Accuracy: 0.4967124925283921
Precision: 0.5152454103750255
Recall: 0.5044946904324853
[[ 72 780]
 [ 62 759]]
F1 Score: 0.3978277179525698
Accuracy: 0.49731022115959356
Precision: 0.5162398385274892
Recall: 0.5050150680779766
[[ 76 776]
 [ 65 756]]
F1 Score: 0.40136646885274674
Accuracy: 0.4931261207411835
Precision: 0.5015449988407512
Recall: 0.5005525438461055
[[ 85 767]
 [ 81 740]]
F1 Score: 0.4034925935314118
Accuracy: 0.4913329348475792
Precision: 0.4963765677234076
Recall: 0.4986147089602168
[[ 90 762]
 [ 89 732]]
F1 Score: 0.5131398999383574
Accuracy: 0.5146443514644351
Precision: 0.5161172161172161
Recall: 0.5158515036626581
[[384 468]
 [344 477]]
Running experiment

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:32: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.6976056054037705
Accuracy: 0.6999402271368799
Precision: 0.7096517882868032
Recall: 0.7018093130443236
[[512 340]
 [162 659]]
F1 Score: 0.701010761341444
Accuracy: 0.702928870292887
Precision: 0.711334963137491
Recall: 0.7046549495919896
[[521 331]
 [166 655]]
F1 Score: 0.7068251287001288
Accuracy: 0.7083084279737
Precision: 0.715365983903574
Recall: 0.709870162918232
[[533 319]
 [169 652]]
F1 Score: 0.7111135790439068
Accuracy: 0.7118947997609085
Precision: 0.7162773894194356
Recall: 0.7131032234821842
[[552 300]
 [182 639]]
F1 Score: 0.7052603083480862
Accuracy: 0.7059175134488942
Precision: 0.7096396652007377
Recall: 0.7070352484374374
[[551 301]
 [191 630]]
Running experiments for extratrees
F1 Score: 0.6614619531797447
Accuracy: 0.661685594739988
Precision: 0.6615556185047842
Recall: 0.6614364424468042
[[575 277]
 [289 532]]
F1 Score: 0.6878068246412843
Accuracy: 0.689181111775254
Precision: 0.6950426337881912
Recall: 0.6906476414312102
[[521 331]
 [189 632]]
F1 Score:

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

In [17]:
experiment.print_best_result(metric='accuracy')

Best accuracy result:
Model: randomforest, Parameter: 100, F1: 0.7111513449892728, Accuracy: 0.71249252839211, Precision: 0.7191798372383822, Recall: 0.7140003030770903


# RQ2

In [18]:
rq2= feat_dataset.return_subset_given_research_question(2)
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

Counts and Percentages:
Class 0: Count = 1007, Percentage = 33.91%
Class 1: Count = 993, Percentage = 33.43%
Class 2: Count = 970, Percentage = 32.66%
Counts and Percentages:
Class 2: Count = 259, Percentage = 34.86%
Class 0: Count = 242, Percentage = 32.57%
Class 1: Count = 242, Percentage = 32.57%


In [ ]:
experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

Running experiments for svm
F1 Score: 0.16379018612521154
Accuracy: 0.32570659488559894
Precision: 0.10856886496186631
Recall: 0.3333333333333333
[[242   0   0]
 [242   0   0]
 [259   0   0]]
F1 Score: 0.16379018612521154
Accuracy: 0.32570659488559894
Precision: 0.10856886496186631
Recall: 0.3333333333333333
[[242   0   0]
 [242   0   0]
 [259   0   0]]
F1 Score: 0.2834333215266094
Accuracy: 0.3620457604306864
Precision: 0.2399368052506924
Recall: 0.3705234159779614
[[ 88 154   0]
 [ 61 181   0]
 [100 159   0]]
F1 Score: 0.2869548542625466
Accuracy: 0.3633916554508748
Precision: 0.24153311754953818
Recall: 0.37190082644628103
[[ 95 147   0]
 [ 67 175   0]
 [103 156   0]]
F1 Score: 0.28067911980074695
Accuracy: 0.34993270524899056
Precision: 0.31562604126617966
Recall: 0.35803631258176716
[[ 98 143   1]
 [ 79 161   2]
 [112 146   1]]
F1 Score: 0.33100626504047764
Accuracy: 0.360699865410498
Precision: 0.363226769904331
Recall: 0.3620940893668166
[[ 34 139  69]
 [ 21 156  65]
 [ 38 143  

In [ ]:
experiment.print_best_result(metric='accuracy')

# RQ5

In [ ]:
rq5= feat_dataset.return_subset_given_research_question(5)
train_feat_dataset, _, test_feat_dataset= rq5.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

In [ ]:
experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

In [ ]:
experiment.print_best_result(metric='accuracy')

### RQ2

In [ ]:
rq2= feat_dataset.return_subset_given_research_question(2)
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

# Normalize features
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')

### RQ1

In [ ]:
rq1= feat_dataset.return_subset_given_research_question(1)
train_feat_dataset, _, test_feat_dataset= rq1.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

# Normalize features
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

experiment.print_best_result(metric='accuracy')