# Experiment Eurythmy Letter

In [1]:
from PlantReactivityAnalysis.features.features_dataset import FeaturesDataset
from PlantReactivityAnalysis.models.experiment import Experiment
from PlantReactivityAnalysis.config import PROCESSED_DATA_DIR

In [2]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
classifier_par_dict = {
            "svm": np.array([0.001, 0.01, 0.5, 1.0, 5.0, 10.0, 20.0]),
            "svm_rbf": np.array([0.001, 0.01, 0.5, 1.0, 5.0, 10.0, 20.0]),
            "randomforest": np.array([10, 25, 50, 100, 200, 500]),
            "gradientboosting": np.array([10, 25, 50, 100, 200, 500]),
            "extratrees": np.array([10, 25, 50, 100, 200, 500])
        }

# Preparation

In [4]:
norm_letters_signal_dataset_path= r"..\data\processed\feat_norm_letters_1_1_dataset.pkl"
feat_dataset = FeaturesDataset.load(file_path=norm_letters_signal_dataset_path)

In [5]:
feat_dataset.features.shape

(8390, 187)

In [6]:
feat_dataset.features.head()

id_measurement  id_performance    datetime  plant  generation  \
0               1               1  2023-04-29  salad           1   
1               1               1  2023-04-29  salad           1   
2               1               1  2023-04-29  salad           1   
3               1               1  2023-04-29  salad           1   
4               1               1  2023-04-29  salad           1   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             1              A1      -85.835655       90.291260   
1             1              G1      -96.628212       83.604851   
2             1              D1     -109.998672       89.973495   
3             1              A2      -83.306580       89.631935   
4             1              G2      -65.591743       89.487083   

   lib_mfcc_3_avg  lib_mfcc_4_avg  lib_mfcc_5_avg  lib_mfcc_6_avg  \
0       27.150677       24.450397       17.381523       14.476572   
1       26.647131       23.880787       17.142712       14.166664   
2       27.083378       24.341211       17.288652       14.374680   
3       26.564987       23.834097       16.861643       14.067777   
4       26.376032       23.637720       16.882397       13.740993   

   lib_mfcc_7_avg  lib_mfcc_8_avg  lib_mfcc_9_avg  lib_mfcc_10_avg  \
0       11.628652       10.253779        9.009523         8.263220   
1       11.311499        9.815317        8.509996         7.710995   
2       11.574939       10.197500        8.994436         8.182779   
3       11.136328        9.779285        8.568973         7.687598   
4       10.826669        9.959647        8.586371         7.815620   

   lib_mfcc_11_avg  lib_mfcc_12_avg  lib_mfcc_13_avg  lib_mfcc_1_std  \
0         7.481691         6.924080         6.325689       87.071404   
1         6.942698         6.384663         5.894090      107.289284   
2         7.339973         6.694422         6.222746       45.244011   
3         6.993852         6.350812         5.871837       39.551929   
4         6.835242         6.490175         5.785554       57.464516   

   lib_mfcc_2_std  lib_mfcc_3_std  lib_mfcc_4_std  lib_mfcc_5_std  \
0        0.980359        0.953386        0.947235        0.955398   
1       17.435492        0.894234        0.777028        1.745475   
2        0.859658        0.939066        0.948810        0.866550   
3        0.491159        0.504996        0.560510        0.462185   
4        0.788460        1.222857        1.200740        0.515309   

   lib_mfcc_6_std  lib_mfcc_7_std  lib_mfcc_8_std  lib_mfcc_9_std  \
0        0.965027        0.979433        0.972912        0.969672   
1        1.486925        1.322912        0.952002        0.781681   
2        0.917197        0.897436        0.912217        0.878173   
3        0.536993        0.503689        0.455105        0.462463   
4        0.505040        0.743336        0.627253        1.033373   

   lib_mfcc_10_std  lib_mfcc_11_std  lib_mfcc_12_std  lib_mfcc_13_std  \
0         0.946374         0.945209         0.952646         0.956299   
1         0.693320         0.757019         0.842326         0.944447   
2         0.894446         0.902890         0.967887         0.915868   
3         0.449083         0.490654         0.456090         0.447698   
4         0.488459         0.632174         0.794163         0.601958   

   zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0  0.000111     0.175157             3.270264                0.034481   
1  0.000078     0.127419             3.240312                0.040663   
2  0.000045     0.477437             3.255116                0.031493   
3  0.000178     0.162887             3.140661                0.056633   
4  0.000089     0.216644             3.242801                0.035025   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.083165               0.013287            0.040835   
1              0.091113               0.011048            0.080317   
2   

In [7]:
feat_dataset.prepare_dataset(drop_constant= True, drop_flatness_columns= True, drop_nan_columns= True)

No columns with NaN values found.


In [8]:
feat_dataset.features.shape

(8362, 181)

In [9]:
feat_dataset.features.head()

id_measurement  id_performance    datetime  plant  generation  \
0               1               1  2023-04-29  salad           1   
1               1               1  2023-04-29  salad           1   
2               1               1  2023-04-29  salad           1   
3               1               1  2023-04-29  salad           1   
4               1               1  2023-04-29  salad           1   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             1              A1      -85.835655       90.291260   
1             1              G1      -96.628212       83.604851   
2             1              D1     -109.998672       89.973495   
3             1              A2      -83.306580       89.631935   
4             1              G2      -65.591743       89.487083   

   lib_mfcc_3_avg  lib_mfcc_4_avg  lib_mfcc_5_avg  lib_mfcc_6_avg  \
0       27.150677       24.450397       17.381523       14.476572   
1       26.647131       23.880787       17.142712       14.166664   
2       27.083378       24.341211       17.288652       14.374680   
3       26.564987       23.834097       16.861643       14.067777   
4       26.376032       23.637720       16.882397       13.740993   

   lib_mfcc_7_avg  lib_mfcc_8_avg  lib_mfcc_9_avg  lib_mfcc_10_avg  \
0       11.628652       10.253779        9.009523         8.263220   
1       11.311499        9.815317        8.509996         7.710995   
2       11.574939       10.197500        8.994436         8.182779   
3       11.136328        9.779285        8.568973         7.687598   
4       10.826669        9.959647        8.586371         7.815620   

   lib_mfcc_11_avg  lib_mfcc_12_avg  lib_mfcc_13_avg  lib_mfcc_1_std  \
0         7.481691         6.924080         6.325689       87.071404   
1         6.942698         6.384663         5.894090      107.289284   
2         7.339973         6.694422         6.222746       45.244011   
3         6.993852         6.350812         5.871837       39.551929   
4         6.835242         6.490175         5.785554       57.464516   

   lib_mfcc_2_std  lib_mfcc_3_std  lib_mfcc_4_std  lib_mfcc_5_std  \
0        0.980359        0.953386        0.947235        0.955398   
1       17.435492        0.894234        0.777028        1.745475   
2        0.859658        0.939066        0.948810        0.866550   
3        0.491159        0.504996        0.560510        0.462185   
4        0.788460        1.222857        1.200740        0.515309   

   lib_mfcc_6_std  lib_mfcc_7_std  lib_mfcc_8_std  lib_mfcc_9_std  \
0        0.965027        0.979433        0.972912        0.969672   
1        1.486925        1.322912        0.952002        0.781681   
2        0.917197        0.897436        0.912217        0.878173   
3        0.536993        0.503689        0.455105        0.462463   
4        0.505040        0.743336        0.627253        1.033373   

   lib_mfcc_10_std  lib_mfcc_11_std  lib_mfcc_12_std  lib_mfcc_13_std  \
0         0.946374         0.945209         0.952646         0.956299   
1         0.693320         0.757019         0.842326         0.944447   
2         0.894446         0.902890         0.967887         0.915868   
3         0.449083         0.490654         0.456090         0.447698   
4         0.488459         0.632174         0.794163         0.601958   

   zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0  0.000111     0.175157             3.270264                0.034481   
1  0.000078     0.127419             3.240312                0.040663   
2  0.000045     0.477437             3.255116                0.031493   
3  0.000178     0.162887             3.140661                0.056633   
4  0.000089     0.216644             3.242801                0.035025   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.083165               0.013287            0.040835   
1              0.091113               0.011048            0.080317   
2   

# RQ1

In [10]:
rq1= feat_dataset.return_subset_given_research_question(1)
train_feat_dataset, _, test_feat_dataset= rq1.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

# Reduce the features that are correlated in the training data
train_cols, feat_stats= train_feat_dataset.reduce_features_based_on_target(corr_threshold=0.8)
test_feat_dataset.keep_only_specified_variable_columns(train_cols)

# Normalize features
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

Reduced variable features from initial count to 48.
Variable features were properly normalized using 'zscore' method.
Applied z-score normalization.
Counts and Percentages:
Class 1: Count = 3394, Percentage = 50.74%
Class 0: Count = 3295, Percentage = 49.26%
Counts and Percentages:
Class 0: Count = 852, Percentage = 50.93%
Class 1: Count = 821, Percentage = 49.07%


In [11]:
feat_stats.head(10)

0          1        p_value
mfcc_1_std        15.420095  22.152635  2.350091e-204
mfcc_2_std         0.525291   0.745020  9.918619e-203
mfcc_2_mean        1.888856   1.516630  2.186149e-189
delta mfcc_1_std  20.767961  29.596046  4.081181e-186
delta mfcc_2_std   0.716534   1.000642  8.973147e-184
mfcc_4_mean        0.334685   0.270271  2.816353e-183
mfcc_6_mean        0.160148   0.129038  1.552175e-181
mfcc_3_mean        0.235893   0.190567  4.143878e-180
mfcc_1_mean      -42.967170 -53.446919  2.469814e-175
mfcc_8_mean        0.087352   0.070636  5.281282e-165

In [12]:
train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

Running experiments for svm
F1 Score: 0.32919005613472335
Accuracy: 0.4907352062163778
Precision: 0.2453676031081889
Recall: 0.5
[[  0 852]
 [  0 821]]
F1 Score: 0.6649628099098461
Accuracy: 0.6706515242080096
Precision: 0.6878768153004449
Recall: 0.6732971928199322
[[452 400]
 [151 670]]
F1 Score: 0.6871845184466467
Accuracy: 0.6903765690376569
Precision: 0.7022594533207549
Recall: 0.6924861184974238
[[493 359]
 [159 662]]
F1 Score: 0.6899671479582123
Accuracy: 0.6927674835624626
Precision: 0.7035584402389427
Recall: 0.6947670595231968
[[500 352]
 [162 659]]
F1 Score: 0.6907839368931429
Accuracy: 0.6921697549312612
Precision: 0.6981861835675283
Recall: 0.6936483905462822
[[523 329]
 [186 635]]
F1 Score: 0.6882989944851465
Accuracy: 0.689181111775254
Precision: 0.6933560971643933
Recall: 0.6904038931110006
[[532 320]
 [200 621]]
F1 Score: 0.6893241921789244
Accuracy: 0.6897788404064554
Precision: 0.6923971607067659
Recall: 0.690724840312684
[[545 307]
 [212 609]]
Running experiments fo

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:34: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.6837142668192508
Accuracy: 0.6855947399880454
Precision: 0.6929529558725613
Recall: 0.6872594682998519
[[509 343]
 [183 638]]
F1 Score: 0.6920338492243334
Accuracy: 0.6933652121936641
Precision: 0.6992398922778669
Recall: 0.69482209946647
[[525 327]
 [186 635]]
F1 Score: 0.688528471391936
Accuracy: 0.6897788404064554
Precision: 0.6952435873103932
Recall: 0.6911901780149022
[[524 328]
 [191 630]]
F1 Score: 0.6995486632495888
Accuracy: 0.7005379557680813
Precision: 0.7054226684126291
Recall: 0.7018421940493959
[[538 314]
 [187 634]]
F1 Score: 0.6892347931964915
Accuracy: 0.6897788404064554
Precision: 0.6927393988059305
Recall: 0.6907913171272866
[[542 310]
 [209 612]]
Running experiments for extratrees
F1 Score: 0.6526918759807122
Accuracy: 0.653317393903168
Precision: 0.6533778701561181
Recall: 0.6527551423032716
[[582 270]
 [310 511]]
F1 Score: 0.688005526631815
Accuracy: 0.6885833831440527
Precision: 0.6916494720233037
Recall: 0.6896176082070988
[[540 312]
 [209 612]]
F1 S

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

In [13]:
experiment.print_best_result(metric='accuracy')

Best accuracy result:
Model: extratrees, Parameter: 100, F1: 0.7120407583672557, Accuracy: 0.7130902570233114, Precision: 0.7186210213361315, Recall: 0.7144542039079789


In [14]:
experiment.print_best_result_by_model(metric='accuracy')

Best accuracy result for svm:
Parameter: 1.0, F1: 0.6899671479582123, Accuracy: 0.6927674835624626, Precision: 0.7035584402389427, Recall: 0.6947670595231968

Best accuracy result for svm_rbf:
Parameter: 1.0, F1: 0.6899671479582123, Accuracy: 0.6927674835624626, Precision: 0.7035584402389427, Recall: 0.6947670595231968

Best accuracy result for randomforest:
Parameter: 200, F1: 0.7016857026511653, Accuracy: 0.702928870292887, Precision: 0.7088490532959326, Recall: 0.7043668833953785

Best accuracy result for gradientboosting:
Parameter: 200, F1: 0.6995486632495888, Accuracy: 0.7005379557680813, Precision: 0.7054226684126291, Recall: 0.7018421940493959

Best accuracy result for extratrees:
Parameter: 100, F1: 0.7120407583672557, Accuracy: 0.7130902570233114, Precision: 0.7186210213361315, Recall: 0.7144542039079789



# RQ2

In [15]:
rq2= feat_dataset.return_subset_given_research_question(2)
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

# Reduce the features that are correlated in the training data
train_cols, feat_stats= train_feat_dataset.reduce_features_based_on_target(corr_threshold=0.8)
test_feat_dataset.keep_only_specified_variable_columns(train_cols)

# Normalize features
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

Reduced variable features from initial count to 47.
Variable features were properly normalized using 'zscore' method.
Applied z-score normalization.
Counts and Percentages:
Class 0: Count = 1007, Percentage = 33.91%
Class 1: Count = 993, Percentage = 33.43%
Class 2: Count = 970, Percentage = 32.66%
Counts and Percentages:
Class 2: Count = 259, Percentage = 34.86%
Class 0: Count = 242, Percentage = 32.57%
Class 1: Count = 242, Percentage = 32.57%


In [16]:
feat_stats.head(10)

1          2          0   p_value
delta chroma_11_std       0.002279   0.002419   0.002284  0.074853
chroma_11_std             0.001652   0.001749   0.001660  0.087699
chroma_5_std              0.017150   0.018078   0.017419  0.099979
spectral_centroid_std     0.031012   0.032001   0.031324  0.100747
delta chroma_1_std        0.000402   0.000425   0.000401  0.127592
delta chroma_5_std        0.023193   0.024372   0.023468  0.138535
chroma_7_std              0.029758   0.031368   0.030372  0.140458
lib_mfcc_3_avg           26.102055  25.914446  25.854143  0.141840
chroma_1_std              0.000291   0.000306   0.000290  0.145890
root_mean_square_energy   0.816939   0.791267   0.773305  0.150621

In [17]:
train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

Running experiments for svm
F1 Score: 0.16379018612521154
Accuracy: 0.32570659488559894
Precision: 0.10856886496186631
Recall: 0.3333333333333333
[[242   0   0]
 [242   0   0]
 [259   0   0]]
F1 Score: 0.16379018612521154
Accuracy: 0.32570659488559894
Precision: 0.10856886496186631
Recall: 0.3333333333333333
[[242   0   0]
 [242   0   0]
 [259   0   0]]
F1 Score: 0.3969170099307086
Accuracy: 0.40107671601615075
Precision: 0.4006418336831101
Recall: 0.4040492676856314
[[115  76  51]
 [ 73 112  57]
 [ 90  98  71]]
F1 Score: 0.3829944950990242
Accuracy: 0.3835800807537012
Precision: 0.38366240774325006
Recall: 0.38496761224033954
[[ 98  76  68]
 [ 72 103  67]
 [ 83  92  84]]
F1 Score: 0.3795785477708005
Accuracy: 0.3795423956931359
Precision: 0.3799051440437851
Recall: 0.3797504706595616
[[91 77 74]
 [69 95 78]
 [75 88 96]]
F1 Score: 0.3686633605889154
Accuracy: 0.36877523553162855
Precision: 0.3686099294005023
Recall: 0.36873118691300505
[[93 70 79]
 [75 85 82]
 [77 86 96]]
F1 Score: 0.3

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:34: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.38505646772245955
Accuracy: 0.38627187079407804
Precision: 0.3953860640301318
Recall: 0.38609506791324977
[[109  39  94]
 [ 82  76  84]
 [104  53 102]]
F1 Score: 0.3866176663058627
Accuracy: 0.38627187079407804
Precision: 0.3902199954077366
Recall: 0.38681834136379595
[[104  59  79]
 [ 77  89  76]
 [107  58  94]]
F1 Score: 0.3902425305255733
Accuracy: 0.39030955585464333
Precision: 0.39207763020623404
Recall: 0.39058893604348155
[[103  63  76]
 [ 76  89  77]
 [ 98  63  98]]
F1 Score: 0.3859170051941019
Accuracy: 0.38627187079407804
Precision: 0.38693321078431375
Recall: 0.38672793218247764
[[106  65  71]
 [ 66  86  90]
 [100  64  95]]
F1 Score: 0.3569026969978974
Accuracy: 0.3566621803499327
Precision: 0.35807997435919253
Recall: 0.3570577661486752
[[ 92  68  82]
 [ 79  85  78]
 [101  70  88]]
Running experiments for extratrees
F1 Score: 0.2970865537812029
Accuracy: 0.3001345895020188
Precision: 0.29719668072335487
Recall: 0.30137634683089226
[[ 98  68  76]
 [ 93  61  88]
 

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

In [18]:
experiment.print_best_result(metric='accuracy')

Best accuracy result:
Model: svm, Parameter: 0.5, F1: 0.3969170099307086, Accuracy: 0.40107671601615075, Precision: 0.4006418336831101, Recall: 0.4040492676856314


In [19]:
experiment.print_best_result_by_model(metric='accuracy')

Best accuracy result for svm:
Parameter: 0.5, F1: 0.3969170099307086, Accuracy: 0.40107671601615075, Precision: 0.4006418336831101, Recall: 0.4040492676856314

Best accuracy result for svm_rbf:
Parameter: 0.5, F1: 0.3969170099307086, Accuracy: 0.40107671601615075, Precision: 0.4006418336831101, Recall: 0.4040492676856314

Best accuracy result for randomforest:
Parameter: 25, F1: 0.38141675676726733, Accuracy: 0.3822341857335128, Precision: 0.3842769101652433, Recall: 0.38422306604124784

Best accuracy result for gradientboosting:
Parameter: 100, F1: 0.3902425305255733, Accuracy: 0.39030955585464333, Precision: 0.39207763020623404, Recall: 0.39058893604348155

Best accuracy result for extratrees:
Parameter: 200, F1: 0.3806973458293957, Accuracy: 0.38088829071332436, Precision: 0.3813255360623782, Recall: 0.3819415637597456



# RQ5

In [20]:
rq5= feat_dataset.return_subset_given_research_question(5)
train_feat_dataset, _, test_feat_dataset= rq5.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

# Reduce the features that are correlated in the training data
train_cols, feat_stats= train_feat_dataset.reduce_features_based_on_target(corr_threshold=0.8)
test_feat_dataset.keep_only_specified_variable_columns(train_cols)

# Normalize features
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

Reduced variable features from initial count to 49.
Variable features were properly normalized using 'zscore' method.
Applied z-score normalization.
Counts and Percentages:
Class 0: Count = 2570, Percentage = 38.42%
Class 2: Count = 2120, Percentage = 31.69%
Class 1: Count = 1999, Percentage = 29.88%
Counts and Percentages:
Class 0: Count = 622, Percentage = 37.18%
Class 2: Count = 528, Percentage = 31.56%
Class 1: Count = 523, Percentage = 31.26%


In [21]:
feat_stats.head(10)

2          0          1       p_value
lib_mfcc_7_avg          10.516035  10.771236  10.790774  1.515754e-14
lib_mfcc_9_avg           8.302979   8.449220   8.520979  6.704931e-13
spectral_centroid_mean   0.048237   0.044935   0.044247  7.798461e-13
spectral_spread_mean     0.114847   0.109315   0.106701  1.165185e-12
delta chroma_7_std       0.049895   0.044768   0.044583  5.540267e-12
chroma_7_std             0.036581   0.033039   0.032861  1.401801e-11
delta chroma_5_std       0.028013   0.025227   0.025339  2.080040e-11
delta chroma_3_std       0.013579   0.012035   0.012295  3.594329e-11
chroma_5_std             0.020616   0.018668   0.018725  3.874251e-11
chroma_7_mean            0.019064   0.016515   0.016025  6.885859e-11

In [22]:
experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

Running experiments for svm
F1 Score: 0.16379018612521154
Accuracy: 0.32570659488559894
Precision: 0.10856886496186631
Recall: 0.3333333333333333
[[242   0   0]
 [242   0   0]
 [259   0   0]]
F1 Score: 0.16379018612521154
Accuracy: 0.32570659488559894
Precision: 0.10856886496186631
Recall: 0.3333333333333333
[[242   0   0]
 [242   0   0]
 [259   0   0]]
F1 Score: 0.3969170099307086
Accuracy: 0.40107671601615075
Precision: 0.4006418336831101
Recall: 0.4040492676856314
[[115  76  51]
 [ 73 112  57]
 [ 90  98  71]]
F1 Score: 0.3829944950990242
Accuracy: 0.3835800807537012
Precision: 0.38366240774325006
Recall: 0.38496761224033954
[[ 98  76  68]
 [ 72 103  67]
 [ 83  92  84]]
F1 Score: 0.3795785477708005
Accuracy: 0.3795423956931359
Precision: 0.3799051440437851
Recall: 0.3797504706595616
[[91 77 74]
 [69 95 78]
 [75 88 96]]
F1 Score: 0.3686633605889154
Accuracy: 0.36877523553162855
Precision: 0.3686099294005023
Recall: 0.36873118691300505
[[93 70 79]
 [75 85 82]
 [77 86 96]]
F1 Score: 0.3

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:34: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.386813791982587
Accuracy: 0.3876177658142665
Precision: 0.39550891895410906
Recall: 0.38792452428816065
[[112  38  92]
 [ 82  79  81]
 [104  58  97]]
F1 Score: 0.3858787890568091
Accuracy: 0.38492597577388965
Precision: 0.3888493475682088
Recall: 0.38580256762074944
[[103  57  82]
 [ 69  93  80]
 [109  60  90]]
F1 Score: 0.3886618150003977
Accuracy: 0.38896366083445494
Precision: 0.39130706977092516
Recall: 0.38948275311911673
[[107  57  78]
 [ 79  87  76]
 [100  64  95]]
F1 Score: 0.372705224645062
Accuracy: 0.3728129205921938
Precision: 0.37501281692797955
Recall: 0.3734962825871917
[[102  64  76]
 [ 79  86  77]
 [106  64  89]]
F1 Score: 0.36231798437146107
Accuracy: 0.3620457604306864
Precision: 0.36347959290032456
Recall: 0.3625674080219535
[[ 94  67  81]
 [ 78  87  77]
 [101  70  88]]
Running experiments for extratrees
F1 Score: 0.3412351229624753
Accuracy: 0.34185733512786004
Precision: 0.3429114796660624
Recall: 0.3430815703542976
[[ 93  86  63]
 [ 82  86  74]
 [106 

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

In [23]:
experiment.print_best_result(metric='accuracy')

Best accuracy result:
Model: svm, Parameter: 0.5, F1: 0.3969170099307086, Accuracy: 0.40107671601615075, Precision: 0.4006418336831101, Recall: 0.4040492676856314


In [24]:
experiment.print_best_result_by_model(metric='accuracy')

Best accuracy result for svm:
Parameter: 0.5, F1: 0.3969170099307086, Accuracy: 0.40107671601615075, Precision: 0.4006418336831101, Recall: 0.4040492676856314

Best accuracy result for svm_rbf:
Parameter: 0.5, F1: 0.3969170099307086, Accuracy: 0.40107671601615075, Precision: 0.4006418336831101, Recall: 0.4040492676856314

Best accuracy result for randomforest:
Parameter: 100, F1: 0.37539342691475136, Accuracy: 0.3755047106325707, Precision: 0.3778052277460262, Recall: 0.37643192188646735

Best accuracy result for gradientboosting:
Parameter: 100, F1: 0.3886618150003977, Accuracy: 0.38896366083445494, Precision: 0.39130706977092516, Recall: 0.38948275311911673

Best accuracy result for extratrees:
Parameter: 25, F1: 0.37235520126628047, Accuracy: 0.3728129205921938, Precision: 0.374005841346355, Recall: 0.37412914685641957

