# Experiment Eurythmy Letter

In [1]:
from PlantReactivityAnalysis.features.features_dataset import FeaturesDataset
from PlantReactivityAnalysis.models.experiment import Experiment
from PlantReactivityAnalysis.config import PROCESSED_DATA_DIR

In [2]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
classifier_par_dict = {
            "svm": np.array([0.001, 0.01, 0.5, 1.0, 5.0, 10.0, 20.0]),
            "svm_rbf": np.array([0.001, 0.01, 0.5, 1.0, 5.0, 10.0, 20.0]),
            "randomforest": np.array([10, 25, 50, 100, 200, 500]),
            "gradientboosting": np.array([10, 25, 50, 100, 200, 500]),
            "extratrees": np.array([10, 25, 50, 100, 200, 500])
        }

# Preparation

In [4]:
norm_letters_signal_dataset_path= r"..\data\processed\feat_raw_letters_1_1_dataset.pkl"
feat_dataset = FeaturesDataset.load(file_path=norm_letters_signal_dataset_path)

In [5]:
feat_dataset.features.shape

(8390, 187)

In [6]:
feat_dataset.features.head()

id_measurement  id_performance    datetime  plant  generation  \
0               1               1  2023-04-29  salad           1   
1               1               1  2023-04-29  salad           1   
2               1               1  2023-04-29  salad           1   
3               1               1  2023-04-29  salad           1   
4               1               1  2023-04-29  salad           1   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             1              A1     -875.934448       90.174561   
1             1              G1     -881.704285       82.757996   
2             1              D1     -910.192993       89.565781   
3             1              A2     -882.572571       89.329361   
4             1              G2     -857.099609       89.547325   

   lib_mfcc_3_avg  lib_mfcc_4_avg  lib_mfcc_5_avg  lib_mfcc_6_avg  \
0       27.036600       24.335978       17.266857       14.362387   
1       25.871546       23.203876       16.568825       13.680217   
2       26.833704       24.053741       17.038734       14.083481   
3       26.286102       23.565893       16.590597       13.793759   
4       26.392532       23.654797       16.990082       13.819170   

   lib_mfcc_7_avg  lib_mfcc_8_avg  lib_mfcc_9_avg  lib_mfcc_10_avg  \
0       11.513890       10.139982        8.895366         8.150114   
1       10.881258        9.404713        8.086088         7.254086   
2       11.297335        9.914130        8.742417         7.914444   
3       10.865271        9.511434        8.298739         7.412407   
4       10.877643       10.073779        8.636995         7.913766   

   lib_mfcc_11_avg  lib_mfcc_12_avg  lib_mfcc_13_avg  lib_mfcc_1_std  \
0         7.367686         6.810772         6.211969       80.213020   
1         6.448022         5.861232         5.357966      105.766289   
2         7.067588         6.395854         5.967819       28.670700   
3         6.718295         6.080798         5.607462       41.493301   
4         6.902275         6.574956         5.858723       47.930656   

   lib_mfcc_2_std  lib_mfcc_3_std  lib_mfcc_4_std  lib_mfcc_5_std  \
0        0.964405        0.915351        0.899567        0.918060   
1       19.532993        1.066367        0.911629        0.475148   
2        1.105085        0.961518        1.005593        0.891455   
3        0.539670        0.533153        0.578260        0.479409   
4        0.891346        1.438288        1.419913        0.598312   

   lib_mfcc_6_std  lib_mfcc_7_std  lib_mfcc_8_std  lib_mfcc_9_std  \
0        0.936695        0.952802        0.939777        0.936986   
1        0.472212        0.470265        0.211643        0.215753   
2        0.980889        0.943527        0.966510        0.908136   
3        0.545013        0.519312        0.465926        0.469057   
4        0.560690        0.867479        0.715572        1.146438   

   lib_mfcc_10_std  lib_mfcc_11_std  lib_mfcc_12_std  lib_mfcc_13_std  \
0         0.912120         0.908604         0.910060         0.925049   
1         0.384701         0.433127         0.414579         0.361710   
2         0.934234         0.942631         1.036578         0.945394   
3         0.469288         0.504040         0.476202         0.459609   
4         0.558412         0.738493         0.856107         0.679622   

   zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0  0.000111     0.173058             3.270264                0.034481   
1  0.000078     0.125596             3.240312                0.040663   
2  0.000045     0.464907             3.255116                0.031493   
3  0.000178     0.159426             3.140661                0.056633   
4  0.000089     0.214079             3.242801                0.035025   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.083165               0.013287            0.040835   
1              0.091113               0.011048            0.080317   
2   

In [7]:
feat_dataset.prepare_dataset(drop_constant= True, drop_flatness_columns= True, drop_nan_columns= True)

No columns with NaN values found.


In [8]:
feat_dataset.features.shape

(8362, 181)

In [9]:
feat_dataset.features.head()

id_measurement  id_performance    datetime  plant  generation  \
0               1               1  2023-04-29  salad           1   
1               1               1  2023-04-29  salad           1   
2               1               1  2023-04-29  salad           1   
3               1               1  2023-04-29  salad           1   
4               1               1  2023-04-29  salad           1   

   num_eurythmy eurythmy_letter  lib_mfcc_1_avg  lib_mfcc_2_avg  \
0             1              A1     -875.934448       90.174561   
1             1              G1     -881.704285       82.757996   
2             1              D1     -910.192993       89.565781   
3             1              A2     -882.572571       89.329361   
4             1              G2     -857.099609       89.547325   

   lib_mfcc_3_avg  lib_mfcc_4_avg  lib_mfcc_5_avg  lib_mfcc_6_avg  \
0       27.036600       24.335978       17.266857       14.362387   
1       25.871546       23.203876       16.568825       13.680217   
2       26.833704       24.053741       17.038734       14.083481   
3       26.286102       23.565893       16.590597       13.793759   
4       26.392532       23.654797       16.990082       13.819170   

   lib_mfcc_7_avg  lib_mfcc_8_avg  lib_mfcc_9_avg  lib_mfcc_10_avg  \
0       11.513890       10.139982        8.895366         8.150114   
1       10.881258        9.404713        8.086088         7.254086   
2       11.297335        9.914130        8.742417         7.914444   
3       10.865271        9.511434        8.298739         7.412407   
4       10.877643       10.073779        8.636995         7.913766   

   lib_mfcc_11_avg  lib_mfcc_12_avg  lib_mfcc_13_avg  lib_mfcc_1_std  \
0         7.367686         6.810772         6.211969       80.213020   
1         6.448022         5.861232         5.357966      105.766289   
2         7.067588         6.395854         5.967819       28.670700   
3         6.718295         6.080798         5.607462       41.493301   
4         6.902275         6.574956         5.858723       47.930656   

   lib_mfcc_2_std  lib_mfcc_3_std  lib_mfcc_4_std  lib_mfcc_5_std  \
0        0.964405        0.915351        0.899567        0.918060   
1       19.532993        1.066367        0.911629        0.475148   
2        1.105085        0.961518        1.005593        0.891455   
3        0.539670        0.533153        0.578260        0.479409   
4        0.891346        1.438288        1.419913        0.598312   

   lib_mfcc_6_std  lib_mfcc_7_std  lib_mfcc_8_std  lib_mfcc_9_std  \
0        0.936695        0.952802        0.939777        0.936986   
1        0.472212        0.470265        0.211643        0.215753   
2        0.980889        0.943527        0.966510        0.908136   
3        0.545013        0.519312        0.465926        0.469057   
4        0.560690        0.867479        0.715572        1.146438   

   lib_mfcc_10_std  lib_mfcc_11_std  lib_mfcc_12_std  lib_mfcc_13_std  \
0         0.912120         0.908604         0.910060         0.925049   
1         0.384701         0.433127         0.414579         0.361710   
2         0.934234         0.942631         1.036578         0.945394   
3         0.469288         0.504040         0.476202         0.459609   
4         0.558412         0.738493         0.856107         0.679622   

   zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0  0.000111     0.173058             3.270264                0.034481   
1  0.000078     0.125596             3.240312                0.040663   
2  0.000045     0.464907             3.255116                0.031493   
3  0.000178     0.159426             3.140661                0.056633   
4  0.000089     0.214079             3.242801                0.035025   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.083165               0.013287            0.040835   
1              0.091113               0.011048            0.080317   
2   

# RQ1

In [10]:
rq1= feat_dataset.return_subset_given_research_question(1)
train_feat_dataset, _, test_feat_dataset= rq1.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

# Reduce the features that are correlated in the training data
train_cols, feat_stats= train_feat_dataset.reduce_features_based_on_target(corr_threshold=0.8)
test_feat_dataset.keep_only_specified_variable_columns(train_cols)

# Normalize features
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

Reduced variable features from initial count to 46.
Variable features were properly normalized using 'zscore' method.
Applied z-score normalization.
Counts and Percentages:
Class 1: Count = 3394, Percentage = 50.74%
Class 0: Count = 3295, Percentage = 49.26%
Counts and Percentages:
Class 0: Count = 852, Percentage = 50.93%
Class 1: Count = 821, Percentage = 49.07%


In [11]:
feat_stats.head(10)

0          1        p_value
mfcc_1_std        15.416838  22.146003  2.646781e-204
mfcc_2_std         0.525290   0.745021  9.891848e-203
mfcc_2_mean        1.888856   1.516630  2.184455e-189
delta mfcc_1_std  20.763484  29.587048  4.499103e-186
delta mfcc_2_std   0.716534   1.000642  8.950038e-184
mfcc_4_mean        0.334685   0.270270  2.790184e-183
mfcc_6_mean        0.160148   0.129038  1.549882e-181
mfcc_3_mean        0.235894   0.190567  4.109378e-180
mfcc_1_mean      -42.974151 -53.456395  2.173009e-175
mfcc_8_mean        0.087352   0.070636  5.356263e-165

In [12]:
train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

Running experiments for svm
F1 Score: 0.32919005613472335
Accuracy: 0.4907352062163778
Precision: 0.2453676031081889
Recall: 0.5
[[  0 852]
 [  0 821]]
F1 Score: 0.6635916086077077
Accuracy: 0.667065152420801
Precision: 0.6778665067441029
Recall: 0.6691777747279455
[[473 379]
 [178 643]]
F1 Score: 0.6795814001480776
Accuracy: 0.6838015540944411
Precision: 0.6983017500258879
Recall: 0.6861636730655962
[[476 376]
 [153 668]]
F1 Score: 0.6854171488081463
Accuracy: 0.689181111775254
Precision: 0.7027993578968093
Recall: 0.6914453632064412
[[485 367]
 [153 668]]
F1 Score: 0.6931358363607452
Accuracy: 0.694560669456067
Precision: 0.700807658405592
Recall: 0.6960622852012603
[[524 328]
 [183 638]]
F1 Score: 0.6966518170690106
Accuracy: 0.6975493126120741
Precision: 0.7020032249161086
Recall: 0.6987971270579221
[[538 314]
 [192 629]]
F1 Score: 0.6870372735034389
Accuracy: 0.6873879258816498
Precision: 0.6895647980190608
Recall: 0.6882444688431033
[[547 305]
 [218 603]]
Running experiments for 

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:34: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.6929811109886088
Accuracy: 0.694560669456067
Precision: 0.7013444931696635
Recall: 0.6961287620158629
[[521 331]
 [180 641]]
F1 Score: 0.6952431359386788
Accuracy: 0.6963538553496712
Precision: 0.7015535735105515
Recall: 0.6977120538905377
[[532 320]
 [188 633]]
F1 Score: 0.6995068699416527
Accuracy: 0.7005379557680813
Precision: 0.7055798209215987
Recall: 0.7018643529875968
[[537 315]
 [186 635]]
F1 Score: 0.6917736237519284
Accuracy: 0.6927674835624626
Precision: 0.6974365911199932
Recall: 0.6940579735007691
[[532 320]
 [194 627]]
F1 Score: 0.7031820523092773
Accuracy: 0.7035265989240884
Precision: 0.705876084990698
Recall: 0.7043997644004507
[[560 292]
 [204 617]]
Running experiments for extratrees
F1 Score: 0.6708398796901248
Accuracy: 0.671249252839211
Precision: 0.6712305112919867
Recall: 0.6708261138083066
[[591 261]
 [289 532]]
F1 Score: 0.6909509312269628
Accuracy: 0.6915720263000598
Precision: 0.6948551208747986
Recall: 0.6926405162603718
[[541 311]
 [205 616]]
F1

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

In [13]:
experiment.print_best_result(metric='accuracy')

Best accuracy result:
Model: randomforest, Parameter: 500, F1: 0.7179565723927366, Accuracy: 0.7190675433353257, Precision: 0.7250726782368084, Recall: 0.720477861076324


In [14]:
experiment.print_best_result_by_model(metric='accuracy')

Best accuracy result for svm:
Parameter: 10.0, F1: 0.6966518170690106, Accuracy: 0.6975493126120741, Precision: 0.7020032249161086, Recall: 0.6987971270579221

Best accuracy result for svm_rbf:
Parameter: 10.0, F1: 0.6966518170690106, Accuracy: 0.6975493126120741, Precision: 0.7020032249161086, Recall: 0.6987971270579221

Best accuracy result for randomforest:
Parameter: 500, F1: 0.7179565723927366, Accuracy: 0.7190675433353257, Precision: 0.7250726782368084, Recall: 0.720477861076324

Best accuracy result for gradientboosting:
Parameter: 500, F1: 0.7031820523092773, Accuracy: 0.7035265989240884, Precision: 0.705876084990698, Recall: 0.7043997644004507

Best accuracy result for extratrees:
Parameter: 50, F1: 0.716299466801755, Accuracy: 0.7166766288105201, Precision: 0.7193585346169367, Recall: 0.7175986287191276



# RQ2

In [15]:
rq2= feat_dataset.return_subset_given_research_question(2)
train_feat_dataset, _, test_feat_dataset= rq2.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

# Reduce the features that are correlated in the training data
train_cols, feat_stats= train_feat_dataset.reduce_features_based_on_target(corr_threshold=0.8)
test_feat_dataset.keep_only_specified_variable_columns(train_cols)

# Normalize features
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

Reduced variable features from initial count to 44.
Variable features were properly normalized using 'zscore' method.
Applied z-score normalization.
Counts and Percentages:
Class 0: Count = 1007, Percentage = 33.91%
Class 1: Count = 993, Percentage = 33.43%
Class 2: Count = 970, Percentage = 32.66%
Counts and Percentages:
Class 2: Count = 259, Percentage = 34.86%
Class 0: Count = 242, Percentage = 32.57%
Class 1: Count = 242, Percentage = 32.57%


In [16]:
feat_stats.head(10)

1          2          0   p_value
delta chroma_11_std     0.002279   0.002419   0.002284  0.074853
chroma_11_std           0.001652   0.001749   0.001660  0.087699
chroma_5_std            0.017150   0.018078   0.017419  0.099979
spectral_centroid_std   0.031012   0.032001   0.031324  0.100747
delta chroma_1_std      0.000402   0.000425   0.000401  0.127592
delta chroma_5_std      0.023193   0.024372   0.023468  0.138535
chroma_7_std            0.029758   0.031368   0.030372  0.140458
chroma_1_std            0.000291   0.000306   0.000290  0.145890
chroma_10_std           0.000345   0.000363   0.000346  0.167406
lib_mfcc_3_avg         27.515858  27.264891  27.176241  0.168311

In [17]:
train_df= train_feat_dataset.objective_features
test_df= test_feat_dataset.objective_features

experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

Running experiments for svm
F1 Score: 0.16379018612521154
Accuracy: 0.32570659488559894
Precision: 0.10856886496186631
Recall: 0.3333333333333333
[[242   0   0]
 [242   0   0]
 [259   0   0]]
F1 Score: 0.16379018612521154
Accuracy: 0.32570659488559894
Precision: 0.10856886496186631
Recall: 0.3333333333333333
[[242   0   0]
 [242   0   0]
 [259   0   0]]
F1 Score: 0.35965130726340666
Accuracy: 0.38627187079407804
Precision: 0.384621257144439
Recall: 0.3923333014242105
[[111 104  27]
 [ 73 143  26]
 [125 101  33]]
F1 Score: 0.3771342233042854
Accuracy: 0.3835800807537012
Precision: 0.38122278854695485
Recall: 0.3870470234106598
[[105  85  52]
 [ 70 119  53]
 [112  86  61]]
F1 Score: 0.35958838219112194
Accuracy: 0.35935397039030953
Precision: 0.35989907601160803
Recall: 0.3594509503600413
[[83 77 82]
 [72 92 78]
 [98 69 92]]
F1 Score: 0.36426946117074643
Accuracy: 0.36473755047106327
Precision: 0.36431523926780457
Recall: 0.3642373187827734
[[ 82  82  78]
 [ 75  89  78]
 [ 87  72 100]]
F

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:34: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.420863516154996
Accuracy: 0.423956931359354
Precision: 0.42437707587940343
Recall: 0.4266515630151994
[[109  72  61]
 [ 70 126  46]
 [ 99  80  80]]
F1 Score: 0.4151029758976848
Accuracy: 0.4158815612382234
Precision: 0.41651781462208
Recall: 0.41766382675473585
[[105  73  64]
 [ 67 116  59]
 [101  70  88]]
F1 Score: 0.4129279741519644
Accuracy: 0.41318977119784656
Precision: 0.41451536237583
Recall: 0.41463777827414194
[[104  70  68]
 [ 73 112  57]
 [ 97  71  91]]
F1 Score: 0.3874066115900086
Accuracy: 0.3876177658142665
Precision: 0.3877891016044022
Recall: 0.3889190252826617
[[ 99  68  75]
 [ 75 103  64]
 [ 93  80  86]]
F1 Score: 0.3925628964814834
Accuracy: 0.39300134589502017
Precision: 0.39407734172629033
Recall: 0.3944286671559399
[[100  72  70]
 [ 78 106  58]
 [ 95  78  86]]
Running experiments for extratrees
F1 Score: 0.34110705920277207
Accuracy: 0.3445491251682369
Precision: 0.3437401027920544
Recall: 0.34637884637884636
[[110  69  63]
 [ 97  77  68]
 [106  84  69

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

In [18]:
experiment.print_best_result(metric='accuracy')

Best accuracy result:
Model: gradientboosting, Parameter: 10, F1: 0.4204034839427191, Accuracy: 0.423956931359354, Precision: 0.4277730327264102, Recall: 0.4269227905591542


In [19]:
experiment.print_best_result_by_model(metric='accuracy')

Best accuracy result for svm:
Parameter: 0.5, F1: 0.35965130726340666, Accuracy: 0.38627187079407804, Precision: 0.384621257144439, Recall: 0.3923333014242105

Best accuracy result for svm_rbf:
Parameter: 0.5, F1: 0.35965130726340666, Accuracy: 0.38627187079407804, Precision: 0.384621257144439, Recall: 0.3923333014242105

Best accuracy result for randomforest:
Parameter: 50, F1: 0.3887754830609465, Accuracy: 0.3916554508748318, Precision: 0.39347948569170094, Recall: 0.39431698522607617

Best accuracy result for gradientboosting:
Parameter: 10, F1: 0.4204034839427191, Accuracy: 0.423956931359354, Precision: 0.4277730327264102, Recall: 0.4269227905591542

Best accuracy result for extratrees:
Parameter: 500, F1: 0.38337947297591696, Accuracy: 0.3835800807537012, Precision: 0.3837782882185925, Recall: 0.38487720305902123



# RQ5

In [20]:
rq5= feat_dataset.return_subset_given_research_question(5)
train_feat_dataset, _, test_feat_dataset= rq5.split_dataset(split_by_wav= False,test_size= 0.2, val_size= 0, random_state= 42)

# Reduce the features that are correlated in the training data
train_cols, feat_stats= train_feat_dataset.reduce_features_based_on_target(corr_threshold=0.8)
test_feat_dataset.keep_only_specified_variable_columns(train_cols)

# Normalize features
normalization_params= train_feat_dataset.normalize_features()
test_feat_dataset.apply_normalization(normalization_params)

train_feat_dataset.print_target_distribution()
test_feat_dataset.print_target_distribution()

Reduced variable features from initial count to 47.
Variable features were properly normalized using 'zscore' method.
Applied z-score normalization.
Counts and Percentages:
Class 0: Count = 2570, Percentage = 38.42%
Class 2: Count = 2120, Percentage = 31.69%
Class 1: Count = 1999, Percentage = 29.88%
Counts and Percentages:
Class 0: Count = 622, Percentage = 37.18%
Class 2: Count = 528, Percentage = 31.56%
Class 1: Count = 523, Percentage = 31.26%


In [21]:
feat_stats.head(10)

2          0          1       p_value
lib_mfcc_7_avg          11.270679  11.729932  11.517247  1.666365e-20
lib_mfcc_9_avg           9.055580   9.379057   9.226300  3.016026e-16
lib_mfcc_8_avg          10.091898  10.439283  10.256968  2.733032e-15
lib_mfcc_5_avg          16.456202  17.005356  16.697735  4.263622e-14
lib_mfcc_6_avg          13.704960  14.136619  13.908072  8.658430e-14
spectral_centroid_mean   0.048237   0.044935   0.044247  7.798463e-13
spectral_spread_mean     0.114847   0.109315   0.106701  1.165186e-12
delta chroma_7_std       0.049895   0.044768   0.044583  5.540247e-12
chroma_7_std             0.036581   0.033039   0.032861  1.401797e-11
delta chroma_5_std       0.028013   0.025227   0.025339  2.080028e-11

In [22]:
experiment = Experiment(train_df, test_df, 'target')
experiment.run_all_models(classifier_par_dict)

Running experiments for svm
F1 Score: 0.16379018612521154
Accuracy: 0.32570659488559894
Precision: 0.10856886496186631
Recall: 0.3333333333333333
[[242   0   0]
 [242   0   0]
 [259   0   0]]
F1 Score: 0.16379018612521154
Accuracy: 0.32570659488559894
Precision: 0.10856886496186631
Recall: 0.3333333333333333
[[242   0   0]
 [242   0   0]
 [259   0   0]]
F1 Score: 0.35965130726340666
Accuracy: 0.38627187079407804
Precision: 0.384621257144439
Recall: 0.3923333014242105
[[111 104  27]
 [ 73 143  26]
 [125 101  33]]
F1 Score: 0.3771342233042854
Accuracy: 0.3835800807537012
Precision: 0.38122278854695485
Recall: 0.3870470234106598
[[105  85  52]
 [ 70 119  53]
 [112  86  61]]
F1 Score: 0.35958838219112194
Accuracy: 0.35935397039030953
Precision: 0.35989907601160803
Recall: 0.3594509503600413
[[83 77 82]
 [72 92 78]
 [98 69 92]]
F1 Score: 0.36426946117074643
Accuracy: 0.36473755047106327
Precision: 0.36431523926780457
Recall: 0.3642373187827734
[[ 82  82  78]
 [ 75  89  78]
 [ 87  72 100]]
F

C:\Users\alvar\Documents\GitHub\Plant-Reactivity-Analysis\src\PlantReactivityAnalysis\models\experiment.py:34: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


F1 Score: 0.420863516154996
Accuracy: 0.423956931359354
Precision: 0.42437707587940343
Recall: 0.4266515630151994
[[109  72  61]
 [ 70 126  46]
 [ 99  80  80]]
F1 Score: 0.4136410034677431
Accuracy: 0.414535666218035
Precision: 0.415211155856565
Recall: 0.4163768254677345
[[105  73  64]
 [ 68 116  58]
 [101  71  87]]
F1 Score: 0.4157394475906975
Accuracy: 0.4158815612382234
Precision: 0.4172788434806784
Recall: 0.4173021900294627
[[105  68  69]
 [ 73 112  57]
 [ 97  70  92]]
F1 Score: 0.3862198923614419
Accuracy: 0.38627187079407804
Precision: 0.38651892053439146
Recall: 0.3875416148143421
[[ 98  66  78]
 [ 75 103  64]
 [ 94  79  86]]
F1 Score: 0.3926604161327177
Accuracy: 0.39300134589502017
Precision: 0.39398407420847814
Recall: 0.3943382579746216
[[101  70  71]
 [ 79 104  59]
 [ 93  79  87]]
Running experiments for extratrees
F1 Score: 0.3385583847272815
Accuracy: 0.3405114401076716
Precision: 0.34050300937718153
Recall: 0.34224661497388764
[[102  72  68]
 [ 90  82  70]
 [110  80  6

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

In [23]:
experiment.print_best_result(metric='accuracy')

Best accuracy result:
Model: gradientboosting, Parameter: 10, F1: 0.4204034839427191, Accuracy: 0.423956931359354, Precision: 0.4277730327264102, Recall: 0.4269227905591542


In [24]:
experiment.print_best_result_by_model(metric='accuracy')

Best accuracy result for svm:
Parameter: 0.5, F1: 0.35965130726340666, Accuracy: 0.38627187079407804, Precision: 0.384621257144439, Recall: 0.3923333014242105

Best accuracy result for svm_rbf:
Parameter: 0.5, F1: 0.35965130726340666, Accuracy: 0.38627187079407804, Precision: 0.384621257144439, Recall: 0.3923333014242105

Best accuracy result for randomforest:
Parameter: 500, F1: 0.3966435614637643, Accuracy: 0.3983849259757739, Precision: 0.3981468626567454, Recall: 0.40048076411712774

Best accuracy result for gradientboosting:
Parameter: 10, F1: 0.4204034839427191, Accuracy: 0.423956931359354, Precision: 0.4277730327264102, Recall: 0.4269227905591542

Best accuracy result for extratrees:
Parameter: 500, F1: 0.38161992550642604, Accuracy: 0.3822341857335128, Precision: 0.38207730449405597, Recall: 0.3836806109533382

